"""Layer L3 overlays - Sector profiles and sector process catalogues.
Retention anchors carry a confidence flag: 'high' = well-established; 'verify' = confirm the
current text before relying on it in a client deliverable (laws/circulars get amended).
Process tuple format is identical to data_processes_common.COMMON.
"""

SECTORS = []
def sector(code, name, covers, regulators, laws, localisation, retention, hotspots, stuck, principals, processes):
    SECTORS.append(dict(code=code, name=name, covers=covers, regulators=regulators, laws=laws,
                        localisation=localisation, retention=retention, hotspots=hotspots,
                        stuck=stuck, principals=principals, processes=processes))

# 1 ---------------------------------------------------------------- BANKING
sector("BNK", "Banking", "Scheduled commercial banks, small finance banks, payments banks, co-operative banks",
 ["RBI", "FIU-IND", "NPCI (for payment systems)", "CERT-In", "Banking Ombudsman (RBI Integrated Ombudsman)"],
 [("Banking Regulation Act 1949", "Licensing; customer confidentiality expectations"),
  ("RBI Master Direction - KYC 2016 (as amended)", "CDD, V-CIP, periodic KYC updation, record keeping"),
  ("PMLA 2002 & PML (Maintenance of Records) Rules 2005", "Transaction & identity records; STR/CTR reporting to FIU-IND"),
  ("RBI - Storage of Payment System Data (Apr 2018) + FAQs", "Entire payment data stored only in India"),
  ("RBI Master Direction - IT Governance, Risk, Controls & Assurance Practices 2023", "IT/cyber governance, incident reporting"),
  ("RBI Master Direction - Outsourcing of IT Services 2023", "Vendor oversight incl. cloud; right to audit; data location"),
  ("RBI Cyber Security Framework for Banks 2016 & later circulars", "Cyber incident reporting to RBI (within 2-6 hours per circulars)"),
  ("Credit Information Companies (Regulation) Act 2005 & Rules 2006", "Bureau reporting accuracy, access & correction"),
  ("RBI Master Direction - NBFC-Account Aggregator 2016", "Consent artefacts for financial data sharing"),
  ("RBI Card-on-File Tokenisation directions", "Merchants/PAs may not store card data (CoF) - tokens"),
  ("Payment and Settlement Systems Act 2007", "Payment system operator obligations")],
 "Payment system data must be stored only in India (RBI 2018). Outsourcing/cloud: RBI supervisory access regardless of location. DPDP s.16(2) keeps these stricter rules alive.",
 [("KYC & transaction records", "5 years after end of business relationship / transaction", "PMLA Rules r.3 & 9; RBI KYC MD", "high"),
  ("Payment system data", "Stored in India; retention as per RBI & PMLA", "RBI Apr 2018", "high"),
  ("Books of account", "8 years", "Companies Act s.128(5)", "high"),
  ("Call recordings (telesales/collections)", "Per RBI/internal policy - commonly >= 3 months to years", "RBI fair practices / internal", "verify"),
  ("CCTV at branches/ATMs", "Per RBI/State police guidance - commonly 90 days", "RBI circulars / police orders", "verify")],
 ["Legacy customers with no DPDP-grade consent (massive s.5(2) legacy notice)", "Cross-sell/marketing using KYC data without separate consent", "DSA/DST/agents and fintech partners acting as processors or co-DFs", "Account Aggregator & bureau sharing (s.8(3) accuracy)", "Children: minor accounts & guardian consent", "Nominee data (nominee is a DP)", "Collection agents misuse of contact lists"],
 ["PMLA/KYC retention overrides erasure requests - document 'retention required by law' responses", "Core banking has no purpose-level consent flags - implement consent layer outside CBS", "Hundreds of vendors - tier them; start with those holding bulk PD", "Paper account-opening forms in branches digitised by back office - map the digitisation point"],
 ["Customer", "Prospect", "Minor customer & guardian", "Nominee", "Guarantor / co-applicant", "Beneficiary / payee", "Merchant", "Employee"],
 [("BNK-01", "Retail Banking", "Account opening & KYC (branch, digital, V-CIP)", ["Lead capture", "CKYC search/download", "Aadhaar e-KYC/OVD", "Video KYC", "Account creation in CBS", "Welcome kit"], ["Customer", "Minor & guardian", "Nominee"], ["identity", "gov_id", "biometric", "contact", "financial", "images_av"], ["CBS", "LOS", "CKYC", "V-CIP platform"], ["CKYC registry", "UIDAI (AUA/KUA)", "V-CIP vendor", "Courier"], ["s7d", "consent"], ["processor", "children", "legacy_data", "decision_or_disclosure", "gov_id", "biometric", "online_presence"], "Aadhaar: use only as permitted, mask, store in Aadhaar Data Vault."),
  ("BNK-02", "Retail Banking", "Deposits, payments & transactions", ["Fund transfers (UPI/IMPS/NEFT/RTGS)", "Standing instructions", "Statements", "Alerts"], ["Customer", "Payee"], ["financial", "transaction", "contact"], ["CBS", "Payment switch", "UPI"], ["NPCI", "SMS gateway"], ["s7a", "s7d"], ["processor", "financial"], "Payee data is a third party's PD."),
  ("BNK-03", "Lending", "Loan origination, underwriting & disbursal", ["Application", "Bureau pull", "Income/bank statement analysis", "Scorecard/AI decision", "Sanction & disbursal"], ["Applicant", "Co-applicant", "Guarantor"], ["identity", "gov_id", "financial", "employment", "credit_history"], ["LOS", "BRE/scorecard", "Bureau APIs", "AA"], ["Credit bureaus", "AA/FIU", "DSA", "Valuers", "Legal vendors"], ["consent", "s7d"], ["processor", "decision_or_disclosure", "ai", "financial"], "s.8(3) accuracy for credit decisions; DSA as processor."),
  ("BNK-04", "Lending", "Collections & recovery", ["Reminders", "Field visits", "Agency allocation", "Legal notices", "Skip tracing"], ["Borrower", "Guarantor", "References"], ["contact", "financial", "location"], ["Collection system", "Dialer"], ["Collection agencies"], ["s7a", "ex17_1a", "ex17_1f"], ["processor", "location"], "No harassment/contact-list misuse; references are third-party DPs."),
  ("BNK-05", "Cards", "Credit/debit card issuance & usage", ["Card application", "Card personalisation", "Tokenisation", "Rewards", "Chargebacks"], ["Cardholder", "Add-on cardholder"], ["identity", "financial", "payment_card", "transaction"], ["Card management system"], ["Card network", "Card personaliser", "Rewards partner"], ["consent", "s7a"], ["processor", "cross_border", "financial"], "Card network processing abroad - foreign leg permitted per RBI FAQ."),
  ("BNK-06", "Risk & Compliance", "AML monitoring & regulatory reporting", ["Transaction monitoring", "Sanctions screening", "STR/CTR filing", "Fraud monitoring"], ["Customer", "Counterparties"], ["financial", "transaction", "identity"], ["AML system", "FRM"], ["FIU-IND", "Screening data vendors"], ["s7d", "ex17_1c"], ["processor", "decision_or_disclosure", "ai"], ""),
  ("BNK-07", "Wealth & Third-party products", "Insurance, MF & investment distribution", ["Needs analysis", "Product sourcing", "Data sharing with insurer/AMC"], ["Customer"], ["identity", "financial", "health"], ["Distribution platform"], ["Insurers", "AMCs"], ["consent"], ["decision_or_disclosure", "health", "marketing"], "Bank and insurer are separate DFs."),
  ("BNK-08", "Branch Ops", "Branch operations, lockers & walk-ins", ["Token/queue", "Locker access registers", "Cash transactions", "CCTV"], ["Customer", "Visitor"], ["identity", "images_av", "biometric"], ["Queue mgmt", "Locker system", "CCTV"], ["Security agency"], ["s7a", "s7d"], ["cctv", "biometric"], "")])

# 2 ---------------------------------------------------------------- NBFC / FINTECH / PAYMENTS
sector("FIN", "NBFC, Fintech & Payments", "NBFCs, digital lenders & LSPs, payment aggregators/gateways, PPI wallets, account aggregators, BNPL, neo-banks",
 ["RBI", "NPCI", "FIU-IND", "CERT-In"],
 [("RBI (Digital Lending) Directions 2025", "Need-based data collection with explicit consent; no access to contacts/media/call logs; data storage in India; LSP accountability (verify current text)"),
  ("RBI Master Direction - Payment Aggregators & Payment Gateways", "Merchant KYC, no card storage, data localisation"),
  ("RBI Master Direction - PPIs", "Wallet KYC levels"),
  ("RBI Master Direction - KYC 2016", "CDD"),
  ("PMLA 2002", "Records & reporting"),
  ("RBI - Storage of Payment System Data 2018", "Localisation"),
  ("RBI NBFC-AA Master Direction", "Consent artefact framework for FIPs/FIUs")],
 "Payment data and digital-lending data stored in India. LSPs/partners must follow RE's data policy.",
 [("KYC & transaction records", "5 years after relationship ends", "PMLA Rules", "high"),
  ("Digital-lending borrower data", "As per RE policy; delete on request subject to law", "RBI Digital Lending Directions", "verify")],
 ["App permissions (contacts, SMS, location, media)", "LSP/partner apps acting as processors but using data for own purposes", "Alternate-data credit scoring & AI (s.8(3), profiling)", "SDK sprawl in apps (analytics, attribution, fraud)", "Co-lending: two DFs"],
 ["Reading SMS for underwriting - needs explicit consent & minimisation", "Partners' consent screens not controlled by RE", "Fraud/risk use as s.7 vs consent debate - document legitimacy under law (PMLA/RBI)"],
 ["Borrower", "Wallet user", "Merchant & merchant staff", "Payer/payee", "Co-borrower"],
 [("FIN-01", "Onboarding", "Digital onboarding & KYC in app", ["App install & permissions", "OTP", "e-KYC / CKYC", "Selfie liveness", "Bank account verification (penny drop)"], ["Customer"], ["identity", "gov_id", "biometric", "device_online", "financial", "contact"], ["Mobile app", "KYC stack"], ["KYC vendors", "UIDAI", "Liveness vendor", "Cloud"], ["consent", "s7d"], ["processor", "online_presence", "cross_border", "biometric", "gov_id"], ""),
  ("FIN-02", "Lending", "Underwriting with alternate data", ["Bank statement parsing", "AA fetch", "Device & SMS signals", "Scorecard/ML", "Decision"], ["Applicant"], ["financial", "device_online", "behavioural", "credit_history"], ["BRE", "ML platform", "AA"], ["Bureau", "AA", "Analytics vendors"], ["consent"], ["processor", "decision_or_disclosure", "ai"], ""),
  ("FIN-03", "Lending", "Servicing, repayment & collections", ["EMI/NACH", "Reminders", "Recovery agents"], ["Borrower", "References"], ["financial", "contact", "location"], ["LMS", "Dialer"], ["Collection agencies", "NACH sponsor bank"], ["s7a", "ex17_1a"], ["processor"], ""),
  ("FIN-04", "Payments", "Merchant onboarding & settlement", ["Merchant KYC", "Beneficial owner checks", "Settlement", "Chargeback"], ["Merchant proprietor", "Merchant staff"], ["identity", "gov_id", "financial"], ["PA platform"], ["Acquiring bank"], ["s7d", "s7a"], ["processor", "financial"], ""),
  ("FIN-05", "Payments", "Payment processing & tokenisation", ["Checkout", "Token vault", "Fraud scoring", "Refunds"], ["Payer"], ["payment_card", "financial", "device_online"], ["Gateway", "Token vault", "FRM"], ["Card networks", "Issuing banks"], ["s7a"], ["processor", "cross_border", "financial", "ai"], ""),
  ("FIN-06", "Wallets / AA", "Wallet / Account Aggregator consent flows", ["Consent artefact creation", "Data fetch", "Consent revocation"], ["Customer"], ["financial", "transaction"], ["AA platform"], ["FIPs", "FIUs"], ["consent"], ["consent_manager_used", "decision_or_disclosure"], "AA consent model is a template for DPDP Consent Managers.")])

# 3 ---------------------------------------------------------------- INSURANCE
sector("INS", "Insurance", "Life, general & health insurers, TPAs, brokers, web aggregators, corporate agents, POSPs",
 ["IRDAI", "CERT-In", "Insurance Ombudsman", "FIU-IND"],
 [("Insurance Act 1938", "Licensing"),
  ("IRDAI (Maintenance of Insurance Records) Regulations 2015", "Records incl. electronic maintained in data centres located in India (verify current)"),
  ("IRDAI Information & Cyber Security Guidelines 2023", "Security controls, incident reporting, audits"),
  ("IRDAI (Protection of Policyholders' Interests...) Regulations 2024 & Master Circular", "Disclosure, claims, grievance, confidentiality"),
  ("IRDAI TPA / health services regulations", "Health claims data handling"),
  ("PMLA 2002 (life insurers)", "KYC & records")],
 "Policyholder records to be maintained in India (IRDAI records regulations). Health data flows to TPAs/hospitals.",
 [("Policy & claim records", "Policy term + period prescribed (often 10 yrs after claim settlement/expiry in many insurers' policies)", "IRDAI records regs", "verify"),
  ("KYC records (life)", "5 years after relationship", "PMLA", "high")],
 ["Health data in underwriting & claims (proposal forms, medical reports)", "Agents/POSPs/brokers - who is DF?", "Web aggregators & lead sharing", "Group policies: employer supplies employee/dependant data", "Children dependants"],
 ["Group health data received from employers without notice to members - use employer as notice channel", "Old policy files (paper) digitised in bulk", "Reinsurers abroad - cross-border & s.16(2)"],
 ["Proposer", "Life assured", "Nominee", "Beneficiary", "Claimant", "Dependant (child)", "Agent/POSP", "Hospital staff"],
 [("INS-01", "Distribution", "Lead generation & quote (web aggregator, agents, bancassurance)", ["Quote request", "Lead sharing", "Agent follow-up"], ["Prospect"], ["identity", "contact", "health", "financial"], ["Quote engine", "CRM"], ["Web aggregators", "Brokers", "Corporate agents"], ["consent"], ["processor", "marketing", "online_presence", "health"], ""),
  ("INS-02", "Underwriting", "Proposal, medicals & underwriting", ["Proposal form", "Medical tests", "Financial underwriting", "Risk decision"], ["Proposer", "Life assured", "Nominee"], ["identity", "gov_id", "health", "financial", "lifestyle"], ["Policy admin system", "UW engine"], ["Diagnostic centres", "Reinsurers", "Medical examiners"], ["consent"], ["processor", "decision_or_disclosure", "health", "cross_border", "ai"], ""),
  ("INS-03", "Policy Servicing", "Issuance, renewals & endorsements", ["Policy issuance", "Premium collection", "Renewal reminders", "Endorsements"], ["Policyholder", "Nominee"], ["identity", "financial", "contact"], ["PAS", "Payment gateway"], ["Printing & dispatch", "PG"], ["s7a", "consent"], ["processor"], ""),
  ("INS-04", "Claims", "Claims intimation, TPA & settlement", ["Claim intimation", "Cashless pre-auth", "Hospital documents", "Investigation", "Settlement"], ["Claimant", "Patient", "Nominee"], ["health", "identity", "financial"], ["Claims system", "TPA portal"], ["TPAs", "Hospitals", "Investigators", "Surveyors"], ["s7a", "consent"], ["processor", "decision_or_disclosure", "health", "children"], ""),
  ("INS-05", "Group Business", "Group/employee benefit policies", ["Member data upload from employer", "Enrolment", "Claims"], ["Employee members", "Dependants incl. children"], ["identity", "health", "family"], ["Group portal"], ["Employer (DF)", "TPA"], ["s7a", "consent"], ["children", "health", "decision_or_disclosure"], "")])

# 4 ---------------------------------------------------------------- CAPITAL MARKETS
sector("CAP", "Capital Markets", "Stock brokers, depository participants, AMCs/MFs, RTAs, investment advisers, PMS, KRAs, listed companies",
 ["SEBI", "Stock exchanges", "Depositories (NSDL/CDSL)", "FIU-IND", "CERT-In"],
 [("SEBI Cybersecurity & Cyber Resilience Framework (CSCRF) 2024", "Cyber controls; data localisation expectations for REs"),
  ("SEBI KYC / KRA regulations", "KYC via KRAs"),
  ("SEBI (Prohibition of Insider Trading) Regulations 2015", "Structured Digital Database of UPSI sharing - preserve >= 8 years"),
  ("SEBI LODR 2015", "Shareholder communication"),
  ("PMLA 2002", "Records & reporting"),
  ("SEBI intermediary record-keeping requirements", "Retention periods for brokers/DPs (verify current)")],
 "SEBI CSCRF expects REs to keep regulated data within India (verify scope for your RE category).",
 [("Client KYC & transaction records", "5 years after relationship (PMLA); SEBI may prescribe longer", "PMLA / SEBI", "verify"),
  ("PIT Structured Digital Database", ">= 8 years", "SEBI PIT Regs", "high"),
  ("Call recordings of orders", "Per SEBI/exchange circulars", "Exchange circulars", "verify")],
 ["Order call recordings", "Nominee & joint holders", "Algorithmic advice (robo-advisers)", "Investor grievance via SCORES vs DPDP grievance"],
 ["KRA/CKYC data reused for marketing", "Distributor networks (MFDs, sub-brokers) as DFs vs processors"],
 ["Investor", "Joint holder", "Nominee", "Authorised person", "Designated person (PIT)"],
 [("CAP-01", "Onboarding", "Account opening (trading/demat/MF)", ["KYC/KRA", "e-sign", "In-person verification", "Bank mapping"], ["Investor", "Nominee"], ["identity", "gov_id", "financial", "images_av"], ["Back office", "KRA", "e-sign"], ["KRA", "Depositories", "e-sign provider"], ["s7d", "consent"], ["processor", "online_presence", "decision_or_disclosure", "gov_id"], ""),
  ("CAP-02", "Trading", "Order management & call recording", ["Order placement", "Call-and-trade recording", "Contract notes"], ["Investor"], ["financial", "voice", "transaction"], ["OMS", "Voice logger"], ["Exchanges"], ["s7d", "s7a"], ["decision_or_disclosure"], ""),
  ("CAP-03", "Advisory", "Research, advisory & robo-advice", ["Risk profiling", "Suitability", "Recommendations"], ["Investor"], ["financial", "behavioural"], ["Advisory engine"], [], ["consent", "s7d"], ["ai", "decision_or_disclosure"], ""),
  ("CAP-04", "Corporate", "Insider trading compliance (listed cos.)", ["Designated persons & relatives data", "Trading pre-clearance", "SDD entries"], ["Designated persons", "Immediate relatives", "UPSI recipients"], ["identity", "gov_id", "financial"], ["PIT tool"], [], ["s7d"], ["decision_or_disclosure"], "Relatives' data - notice via designated person.")])

# 5 ---------------------------------------------------------------- HEALTHCARE
sector("HLT", "Healthcare", "Hospitals, clinics, diagnostics labs, telemedicine, health-tech apps, pharmacies",
 ["MoHFW", "NMC", "State health departments / Clinical Establishments authorities", "NHA (ABDM)", "CERT-In"],
 [("Clinical Establishments (Registration & Regulation) Act 2010 & State Acts", "Registration, standard treatment, record maintenance"),
  ("IMC (Professional Conduct, Etiquette & Ethics) Regulations 2002", "Maintain indoor patient records 3 years; confidentiality"),
  ("Telemedicine Practice Guidelines 2020", "Consent, records, identity of patient/doctor"),
  ("ABDM Health Data Management Policy", "Consent artefacts via HIE-CM, ABHA, federated records"),
  ("PCPNDT Act 1994 & Rules", "Form F records for ultrasound; strict confidentiality (retain >= 2 years)"),
  ("MTP Act 1971 & Regulations", "Confidentiality of women undergoing termination"),
  ("Mental Healthcare Act 2017 s.23", "Confidentiality of mental health information"),
  ("HIV and AIDS (Prevention & Control) Act 2017", "Informed consent & confidentiality"),
  ("Drugs & Cosmetics Rules 1945 (Schedule H1)", "Pharmacy H1 register maintained 3 years")],
 "No general localisation; ABDM-integrated systems follow NHA norms; Government hospital data via MeitY-empanelled cloud.",
 [("Indoor patient medical records", "3 years from commencement of treatment (min.)", "IMC Regs 2002 reg 1.3.1", "high"),
  ("Medico-legal case records", "Until case disposal / as per court & State rules (often long)", "State rules / court orders", "verify"),
  ("PCPNDT Form F & records", "2 years (longer if proceedings)", "PCPNDT Rules r.9", "high"),
  ("Schedule H1 drug register", "3 years", "Drugs & Cosmetics Rules", "high"),
  ("NABH accreditation standards", "Retention policy as defined by hospital (commonly 5-10 yrs IPD)", "NABH", "verify")],
 ["Health context everywhere; emergency (s.7(f)) vs consent", "Children (paediatrics) - Fourth Schedule Part A exemption only for health services", "Labs, radiology, insurers/TPAs, pharmacies, ABDM", "Doctors as consultants (visiting) - independent DFs?", "WhatsApp sharing of reports", "Paper case sheets & MRD"],
 ["Registration uses paper then HIS - map both", "Doctors share images on personal phones", "Legacy MRD archives with no index - erasure/access impossible", "Insurance TPA cashless flows - who notifies patient"],
 ["Patient", "Attendant/relative", "Minor patient & parent", "Doctor/visiting consultant", "Donor", "Employee"],
 [("HLT-01", "Patient Services", "Registration & appointments", ["Online/phone booking", "Front-desk registration", "UHID creation", "ABHA linking"], ["Patient", "Attendant", "Minor & parent"], ["identity", "contact", "demographic", "gov_id"], ["HIS", "Appointment app", "ABDM gateway"], ["HIS vendor", "SMS provider", "Cloud"], ["consent", "s7a", "s7f"], ["processor", "children", "online_presence", "legacy_data", "health"], ""),
  ("HLT-02", "Clinical", "OPD/IPD consultation & EMR", ["Clinical notes", "Orders", "Prescriptions", "Discharge summary"], ["Patient"], ["health", "identity"], ["EMR/HIS"], ["EMR vendor"], ["consent", "s7a", "s7f"], ["processor", "children", "health", "decision_or_disclosure"], ""),
  ("HLT-03", "Clinical", "Emergency & trauma", ["Unidentified patient registration", "MLC intimation to police", "Emergency treatment"], ["Patient"], ["health", "identity", "images_av"], ["HIS"], ["Police (LEA)"], ["s7f", "s7d"], ["health", "decision_or_disclosure"], "s.7(f) emergency; MLC disclosure s.7(d)."),
  ("HLT-04", "Diagnostics", "Laboratory & radiology", ["Sample collection (home/centre)", "LIS/PACS", "Report delivery (WhatsApp/email/app)"], ["Patient"], ["health", "images_av", "genetic"], ["LIS", "PACS"], ["Outsourced labs", "Home collection partners", "Teleradiology (may be abroad)"], ["consent", "s7a"], ["processor", "cross_border", "health"], ""),
  ("HLT-05", "Pharmacy", "Pharmacy dispensing & e-pharmacy", ["Prescription validation", "H1 register", "Home delivery"], ["Patient"], ["health", "identity", "contact", "financial"], ["Pharmacy system"], ["Delivery partners"], ["s7a", "s7d"], ["processor", "health"], ""),
  ("HLT-06", "Finance", "Billing, insurance & TPA", ["Estimates", "Pre-auth", "Claim documents", "Corporate/PSU billing"], ["Patient", "Policyholder"], ["health", "financial", "identity"], ["Billing", "TPA portals"], ["TPAs", "Insurers", "Corporate clients"], ["s7a", "consent"], ["processor", "health", "decision_or_disclosure"], ""),
  ("HLT-07", "Digital Health", "Telemedicine & health apps", ["Video consults", "e-prescription", "Wearable data", "Health content"], ["Patient", "App user"], ["health", "images_av", "device_online", "biometric"], ["Telemedicine platform", "App"], ["Video SDK", "Cloud"], ["consent"], ["processor", "cross_border", "online_presence", "tracking_ads", "children", "health"], ""),
  ("HLT-08", "Medical Records", "MRD, record requests & research", ["Record retrieval", "Copies to patient/insurer/court", "Retrospective research"], ["Patient"], ["health"], ["MRD", "Archive"], ["Scanning vendor", "Storage vendor"], ["s7a", "s7e", "ex17_2b"], ["processor", "research", "health"], "")])

# 6 ---------------------------------------------------------------- PHARMA & LIFE SCIENCES
sector("PHA", "Pharma, Medical Devices & Clinical Research", "Pharma manufacturers, CROs, medical device companies, biobanks",
 ["CDSCO/DCGI", "Ethics Committees", "ICMR", "NPPA", "CERT-In"],
 [("New Drugs and Clinical Trials Rules 2019", "Trial conduct, informed consent (incl. audio-video consent for vulnerable), record retention"),
  ("ICMR National Ethical Guidelines for Biomedical & Health Research 2017", "Consent, privacy, biobanking"),
  ("Pharmacovigilance Programme of India (PvPI)", "Adverse event reports"),
  ("Uniform Code for Pharmaceutical Marketing Practices 2024", "HCP engagement records"),
  ("Medical Devices Rules 2017", "Device vigilance")],
 "Trial data often shared with global sponsors - cross-border hotspot.",
 [("Clinical trial records", "Per NDCT Rules (e.g. >= 5 years after trial completion)", "NDCT Rules 2019", "verify"),
  ("Pharmacovigilance case records", "Per PvPI / company SOPs", "PvPI", "verify")],
 ["Trial participants' health & genetic data sent abroad", "Patient support programmes (PSPs) via hubs/vendors", "HCP (doctor) data for marketing", "Medical reps' CRM & call notes", "Adverse event reports from social media"],
 ["Global sponsor dictates data model; Indian affiliate is still DF or processor - resolve role", "Research exemption (s.17(2)(b)) does not cover identifiable trial conduct"],
 ["Trial participant", "Patient in PSP", "Healthcare professional", "Medical representative", "Reporter of adverse events"],
 [("PHA-01", "Clinical", "Clinical trial conduct", ["Screening & informed consent", "Case report forms", "Samples & biobanking", "Data transfer to sponsor"], ["Trial participant", "LAR"], ["health", "genetic", "identity", "images_av"], ["EDC", "CTMS"], ["CRO", "Sites", "Central labs", "Global sponsor"], ["consent"], ["processor", "cross_border", "health", "pwd", "children", "research"], ""),
  ("PHA-02", "Safety", "Pharmacovigilance & adverse events", ["AE intake (call centre, social, HCP)", "Case processing", "Regulatory submission"], ["Patient", "Reporter"], ["health", "identity", "contact"], ["Safety database"], ["PV vendor", "Global safety"], ["s7d", "s7g"], ["processor", "cross_border", "health"], ""),
  ("PHA-03", "Commercial", "HCP engagement & field force CRM", ["HCP master", "Call notes", "Samples", "Events & honoraria"], ["HCP"], ["identity", "contact", "professional", "financial"], ["CRM"], ["CRM SaaS", "Event agencies"], ["consent", "s7a"], ["processor", "cross_border", "marketing"], ""),
  ("PHA-04", "Patient Services", "Patient support programmes", ["Enrolment", "Adherence calls", "Financial assistance"], ["Patient", "Caregiver"], ["health", "financial", "contact"], ["PSP platform"], ["Hub vendor", "Nurses"], ["consent"], ["processor", "health"], "")])

# 7 ---------------------------------------------------------------- EDUCATION & EDTECH
sector("EDU", "Education & EdTech", "Schools, colleges, universities, coaching institutes, edtech platforms, test-prep",
 ["Ministry of Education", "UGC", "AICTE", "CBSE/State Boards", "NCPCR", "CERT-In"],
 [("RTE Act 2009", "Admissions incl. 25% EWS quota data"),
  ("UDISE+ / APAAR ID framework", "Student registry & APAAR ID creation (parental consent)"),
  ("POCSO Act 2012", "Mandatory reporting; child protection"),
  ("Juvenile Justice Act 2015", "Confidentiality of children in need of care"),
  ("DPDP Fourth Schedule Part A(3)", "Educational institutions exempt from s.9(1),(3) ONLY for tracking/behavioural monitoring for educational activities or safety")],
 "No localisation; edtech apps often use foreign SaaS/analytics.",
 [("Admission & academic records", "Permanent for transcripts/degrees; others per board/university rules", "Board/University rules", "verify"),
  ("CCTV in schools", "Per State/CBSE safety guidelines (commonly 15-30+ days)", "CBSE circulars", "verify")],
 ["Children = default population (verifiable parental consent)", "EdTech platforms are NOT 'educational institutions' - Fourth Schedule may not help", "Proctoring (face, screen, audio) = biometric & monitoring", "Ad-tech/analytics on children's apps (s.9(3))", "Student wellbeing/counselling data"],
 ["Parent verification at scale for existing student base", "Teachers using personal WhatsApp groups", "Alumni databases built on child-era data"],
 ["Student (minor)", "Parent/guardian", "Adult student", "Teacher", "Applicant", "Alumni"],
 [("EDU-01", "Admissions", "Enquiry, application & admission", ["Enquiry forms", "Entrance tests", "Document verification", "Fee payment", "Admission"], ["Applicant (child)", "Parent"], ["identity", "contact", "education", "gov_id", "financial", "family"], ["ERP", "Admission portal"], ["Payment gateway", "Test vendors"], ["consent"], ["processor", "children", "online_presence", "marketing"], ""),
  ("EDU-02", "Academics", "Attendance, assessment & report cards", ["Attendance (incl. biometric/face)", "Assessments", "Report cards", "Parent portal"], ["Student", "Parent"], ["education", "biometric", "behavioural"], ["ERP/LMS"], ["ERP vendor"], ["consent", "s7a"], ["processor", "children", "decision_or_disclosure", "biometric"], "Sch4 A(3) exemption for tracking for educational activity/safety."),
  ("EDU-03", "Student Welfare", "Health, counselling & special needs", ["Health checkups", "Counselling notes", "IEPs for special needs"], ["Student", "Parent"], ["health", "behavioural"], ["Health records"], ["Doctors", "Counsellors"], ["consent", "s7f"], ["children", "health", "pwd"], ""),
  ("EDU-04", "Transport & Safety", "School transport & campus safety", ["Bus GPS tracking", "RFID attendance", "CCTV", "Visitor control"], ["Student", "Parent", "Visitor"], ["location", "images_av"], ["GPS/Transport app", "CCTV"], ["Transport contractor"], ["s7a", "consent"], ["processor", "children", "cctv", "location"], "Sch4 A(5) child transport exemption for location during travel."),
  ("EDU-05", "EdTech", "Online learning platform", ["Account creation", "Content consumption tracking", "Adaptive learning", "Live classes", "Proctored exams"], ["Learner (child/adult)", "Parent"], ["identity", "behavioural", "images_av", "biometric", "device_online"], ["LMS", "Video platform", "Proctoring"], ["Cloud", "Video SDK", "Analytics", "Proctoring vendor"], ["consent"], ["processor", "children", "tracking_ads", "online_presence", "cross_border", "ai"], ""),
  ("EDU-06", "Placements & Alumni", "Placements & alumni relations", ["Resume database", "Recruiter sharing", "Alumni portal"], ["Student", "Alumni"], ["identity", "education", "contact"], ["Placement portal"], ["Recruiters"], ["consent"], ["decision_or_disclosure"], "")])

# 8 ---------------------------------------------------------------- E-COMMERCE & RETAIL
sector("ECR", "E-commerce & Retail", "Marketplaces, D2C brands, quick-commerce, omnichannel retail, FMCG consumer programmes",
 ["Department of Consumer Affairs / CCPA", "RBI (payments)", "CERT-In"],
 [("Consumer Protection (E-Commerce) Rules 2020", "Seller info, grievance officer, no manipulation"),
  ("Guidelines for Prevention & Regulation of Dark Patterns 2023", "Consent & UI design"),
  ("DPDP Third Schedule", "E-commerce >= 2 crore registered users in India: 3-year inactivity erasure + 48h notice"),
  ("RBI Card-on-File tokenisation", "No card storage by merchants"),
  ("CGST Act s.36 & Income-tax", "Invoice retention"),
  ("TRAI TCCCPR", "Promotional SMS/voice")],
 "Payment data via RBI-regulated PAs; many SaaS tools abroad.",
 [("Invoices & tax records", "72 months from due date of annual return (GST)", "CGST s.36", "high"),
  ("Inactive user data (large platforms)", "Erase after 3 years inactivity (except account access/wallet)", "DPDP Third Schedule", "high"),
  ("Transaction logs & PD (all DFs)", "Min 1 year", "DPDP R8(3)", "high")],
 ["Ad-tech, pixels, retargeting & marketplace data sharing with sellers", "Seller/merchant access to buyer data (processor or DF?)", "Loyalty & phone-number-at-billing in stores", "Reviews & UGC", "Children buying on platform", "Delivery partners & address/phone masking"],
 ["Sellers get buyer addresses - contractually limit to fulfilment", "Omnichannel identity stitching across POS/app/web without clear notice"],
 ["Customer", "Guest checkout buyer", "Gift recipient", "Seller (individual)", "Delivery partner", "Store visitor"],
 [("ECR-01", "Platform", "Customer registration & profile", ["Sign-up", "Addresses", "Saved payments (tokens)", "Wishlist"], ["Customer"], ["identity", "contact", "financial", "preferences"], ["Platform backend"], ["Cloud", "OTP provider"], ["consent", "s7a"], ["processor", "online_presence", "third_schedule", "children", "legacy_data"], ""),
  ("ECR-02", "Orders", "Order, payment, fulfilment & returns", ["Checkout", "Payment", "Seller fulfilment", "Last-mile delivery", "Returns & refunds"], ["Customer", "Gift recipient"], ["identity", "contact", "financial", "location", "transaction"], ["OMS", "WMS", "PG"], ["Sellers", "Logistics partners", "PG"], ["s7a"], ["processor", "third_schedule", "financial"], ""),
  ("ECR-03", "Marketing", "Personalisation, ads & retargeting", ["Browsing tracking", "Recommendation", "Ad audiences to platforms", "Affiliate tracking"], ["Customer", "Visitor"], ["behavioural", "device_online", "transaction"], ["CDP", "Ad platforms"], ["Ad networks", "Affiliates"], ["consent"], ["processor", "tracking_ads", "cross_border", "children", "marketing"], ""),
  ("ECR-04", "Stores", "In-store POS, loyalty & CCTV", ["Phone at billing", "Loyalty enrolment", "Footfall analytics", "CCTV"], ["Customer", "Visitor"], ["contact", "transaction", "images_av"], ["POS", "Loyalty", "CCTV/VMS"], ["Loyalty vendor", "Analytics vendor"], ["consent", "s7a"], ["processor", "marketing", "cctv"], ""),
  ("ECR-05", "Trust & Safety", "Fraud prevention & reviews", ["Device fingerprinting", "Return-abuse scoring", "Review moderation"], ["Customer", "Reviewer"], ["device_online", "behavioural"], ["FRM", "Moderation"], ["Fraud vendors"], ["s7a", "consent"], ["processor", "ai", "decision_or_disclosure"], "")])

# 9 ---------------------------------------------------------------- SOCIAL MEDIA, PLATFORMS & GAMING
sector("SMG", "Social Media, Online Platforms & Gaming", "Social networks, messaging, dating, content/creator platforms, online gaming, marketplaces for services",
 ["MeitY", "CERT-In", "Online gaming authority (under 2025 Act, as notified)"],
 [("IT Act 2000 & IT (Intermediary Guidelines and Digital Media Ethics Code) Rules 2021", "Due diligence; retain user info 180 days after deletion; SSMI (>= 50 lakh users) obligations incl. grievance, compliance officer"),
  ("Promotion and Regulation of Online Gaming Act 2025", "Prohibits online money games; regulates e-sports/social games (verify rules)"),
  ("DPDP Third Schedule", "Social media >= 2 crore / online gaming >= 50 lakh users: 3-year inactivity erasure"),
  ("DPDP s.10", "Strong SDF candidates")],
 "Global platforms: cross-border default; watch s.16 negative list and SDF localisation (R13(4)).",
 [("User info after account deletion", "180 days", "IT Rules 2021 r.3(1)(h)", "high"),
  ("Inactive user data", "3 years then erase (48h notice)", "DPDP Third Schedule", "high")],
 ["Children & age assurance at scale", "Behavioural advertising & recommender algorithms (R13(3))", "UGC containing third-party PD", "Law-enforcement data requests & traceability", "Deceased users' accounts (nomination)"],
 ["IT Rules 180-day retention vs DPDP erasure on withdrawal - document legal retention", "Friend/contact uploads = PD of non-users"],
 ["User", "Minor user & parent", "Non-user in contacts/UGC", "Creator", "Advertiser contact"],
 [("SMG-01", "Platform", "Account creation & age assurance", ["Sign-up", "Age declaration/verification", "Parental consent", "Contact upload"], ["User", "Minor & parent", "Non-user contacts"], ["identity", "contact", "device_online", "biometric"], ["Platform"], ["Cloud", "Age-assurance vendor"], ["consent"], ["processor", "children", "online_presence", "third_schedule", "cross_border"], ""),
  ("SMG-02", "Platform", "Feed, recommendations & ads", ["Engagement tracking", "Ranking", "Ad targeting", "Measurement"], ["User"], ["behavioural", "device_online", "location", "inferences"], ["Recommender", "Ad server"], ["Ad partners", "Measurement vendors"], ["consent"], ["processor", "tracking_ads", "children", "ai", "cross_border"], ""),
  ("SMG-03", "Trust & Safety", "Content moderation & LEA requests", ["Reports", "Automated moderation", "Human review", "LEA disclosure"], ["User", "Reported person"], ["communication_content", "images_av"], ["Moderation stack"], ["Moderation BPO", "LEAs"], ["s7d", "s7e", "ex17_1c"], ["processor", "ai", "decision_or_disclosure"], ""),
  ("SMG-04", "Gaming", "Game accounts, wallets & fair play", ["Player accounts", "In-game purchases", "Anti-cheat", "KYC (where required)"], ["Player", "Minor player"], ["identity", "financial", "device_online", "behavioural"], ["Game backend", "Wallet"], ["PG", "Anti-cheat vendor"], ["consent", "s7a"], ["processor", "children", "third_schedule", "tracking_ads"], "")])

# 10 ---------------------------------------------------------------- TELECOM
sector("TEL", "Telecom & Internet Service Providers", "Telcos, ISPs, VNOs, CPaaS, data centres",
 ["DoT", "TRAI", "CERT-In", "TEC"],
 [("Telecommunications Act 2023", "Authorisation, user identification, interception"),
  ("Telecom Cyber Security Rules 2024", "Security obligations, incident reporting"),
  ("DoT Unified Licence / authorisation conditions", "CDR/IPDR retention (2 years), subscriber data restrictions abroad"),
  ("Telecom (Procedures & Safeguards for Lawful Interception) Rules 2024", "Interception records"),
  ("TRAI TCCCPR 2018 (as amended)", "Commercial communications, DLT, consent registers"),
  ("CERT-In Directions 2022", "Data centre/VPS/cloud/VPN providers: subscriber KYC records 5 years")],
 "Licence conditions restrict transfer of subscriber/user accounting information outside India (verify clause).",
 [("CDR / IPDR", "2 years", "DoT UL amendment Dec 2021", "high"),
  ("Customer Acquisition Forms / KYC", "Per DoT instructions", "DoT", "verify"),
  ("VPN/cloud subscriber KYC", "5 years after cancellation", "CERT-In Directions 2022", "high")],
 ["Subscriber KYC (Aadhaar e-KYC) at POS/retailers", "Location & traffic data", "Lawful interception secrecy", "CPaaS acting for enterprises (processor)", "Spam/fraud analytics on calls"],
 ["Retailer network collecting KYC - processor contracts at scale", "Consent registers under TCCCPR vs DPDP consent ledger - unify"],
 ["Subscriber", "Retailer/POS", "Called/calling party", "Enterprise end-users"],
 [("TEL-01", "Sales", "SIM/connection activation & KYC", ["Digital KYC at POS", "Aadhaar e-KYC", "Activation", "Re-verification"], ["Subscriber"], ["identity", "gov_id", "biometric", "images_av"], ["KYC app", "BSS"], ["Retailers/POS", "UIDAI"], ["s7d", "consent"], ["processor", "gov_id", "biometric", "legacy_data"], ""),
  ("TEL-02", "Network", "Network operations, CDR/IPDR & location", ["Call/data records", "Cell location", "Lawful interception"], ["Subscriber", "Other party"], ["location", "traffic", "communication_metadata"], ["Mediation", "LI systems"], ["LEAs"], ["s7d", "s7c", "ex17_1c"], ["decision_or_disclosure", "location"], ""),
  ("TEL-03", "Commercial", "Billing, plans & value-added services", ["Usage billing", "VAS subscriptions", "Collections"], ["Subscriber"], ["financial", "transaction"], ["Billing"], ["VAS partners"], ["s7a", "consent"], ["processor", "marketing"], ""),
  ("TEL-04", "Enterprise", "CPaaS/SMS/voice for enterprises", ["Message routing", "DLT scrubbing", "Delivery reports"], ["End recipients"], ["contact", "communication_content"], ["SMSC", "DLT"], ["Aggregators"], ["s7a"], ["processor"], "Usually processor for enterprise customers.")])

# 11 ---------------------------------------------------------------- IT / ITeS / SaaS / BPO
sector("ITS", "IT, ITeS, SaaS & BPO", "IT services, GCCs, SaaS product companies, BPO/KPO, cloud & data centres",
 ["MeitY", "CERT-In", "STPI/SEZ authorities", "Clients' regulators (indirect)"],
 [("DPDP s.17(1)(d)", "Processing of non-India principals' data under contract with foreign person exempt (except s.8(1),(5))"),
  ("IT Act s.43A & SPDI Rules 2011", "Until Phase 3"),
  ("CERT-In Directions 2022", "6h reporting, 180-day logs, cloud/VPN KYC"),
  ("MeitY cloud empanelment / GI Cloud", "For Government workloads"),
  ("Client contracts (GDPR SCCs, HIPAA BAAs etc.)", "Contractual privacy obligations")],
 "Processor for Indian clients' data; DF for own employees & marketing; s.17(1)(d) for foreign clients' foreign principals.",
 [("ICT logs", "Rolling 180 days in India", "CERT-In", "high")],
 ["Role clarity per engagement (processor vs DF)", "SaaS using customer data for product analytics/AI training = own purpose -> DF", "Offshore delivery centres serving Indian clients (cross-border)", "Sub-processor chains", "BPO agents' access to customer screens"],
 ["Clients push their DPAs - maintain clause library & obligations register per client", "India-principal data mixed with foreign-principal data in same tenant (partial s.17(1)(d))"],
 ["Client end-customers", "Client employees", "Own employees", "Leads"],
 [("ITS-01", "Delivery", "Client data processing (managed services/BPO)", ["Access to client systems", "Transaction processing", "Customer support on behalf of client"], ["Client's customers/employees"], ["any"], ["Client systems", "VDI"], ["Sub-processors"], ["ex17_1d", "s7a"], ["processor", "cross_border"], "Record whether principals are in India or abroad."),
  ("ITS-02", "Product", "SaaS multi-tenant platform", ["Tenant data hosting", "Support access", "Product telemetry", "AI features"], ["Customer users", "Customer's end-users"], ["any", "device_online"], ["SaaS platform", "Cloud"], ["Cloud", "Sub-processors", "LLM providers"], ["s7a", "consent"], ["processor", "cross_border", "online_presence", "ai"], "Telemetry/AI training = DF for that purpose."),
  ("ITS-03", "Sales", "B2B demand generation", ["Account-based marketing", "Events", "Intent data"], ["Prospect contacts"], ["contact", "professional", "behavioural"], ["CRM", "MAP"], ["Intent data vendors"], ["consent"], ["processor", "marketing", "cross_border"], "")])

# 12 ---------------------------------------------------------------- GOVERNMENT & PSU
sector("GOV", "Government, PSUs & Public Bodies", "Ministries, departments, State agencies, municipal bodies, PSUs, statutory boards",
 ["MeitY", "UIDAI", "CAG", "CERT-In", "NIC"],
 [("DPDP s.7(b),(c), s.17(2)(a), s.17(4), Rule 5 & Second Schedule", "State processing standards & exemptions"),
  ("Aadhaar Act 2016 & Authentication Regulations 2021", "Purpose limitation, auth logs, Aadhaar Data Vault"),
  ("Aadhaar Authentication for Good Governance Rules 2020 (as amended)", "Aadhaar auth for notified purposes"),
  ("RTI Act 2005 s.8(1)(j) (amended by DPDP s.44(3))", "Personal information exempt from disclosure"),
  ("Public Records Act 1993", "Record retention & destruction"),
  ("MeitY GI Cloud / empanelled CSPs", "Hosting of Government data")],
 "Government data typically on NIC/MeitY-empanelled clouds in India.",
 [("Aadhaar authentication logs", "2 years online, then archived 5 years (verify)", "Aadhaar Auth Regulations", "verify"),
  ("Public records", "Per department record retention schedules", "Public Records Act/Rules", "verify")],
 ["Scheme beneficiary databases (DBT) - s.7(b) + Second Schedule", "Aadhaar seeding & masking", "Data sharing across departments", "RTI disclosures now exempt personal info", "PSU commercial activities are NOT State functions - consent applies"],
 ["Legacy scheme data with no notice/intimation", "Outsourced data-entry operators & CSCs"],
 ["Citizen", "Beneficiary", "Applicant", "Employee/pensioner"],
 [("GOV-01", "Schemes", "Beneficiary registration & DBT", ["Application", "Eligibility verification", "Aadhaar seeding", "DBT payment", "Grievance"], ["Beneficiary", "Family members"], ["identity", "gov_id", "financial", "family", "demographic"], ["Scheme portal", "PFMS", "Aadhaar"], ["CSCs", "Banks", "NIC"], ["s7b"], ["processor", "gov_id", "decision_or_disclosure"], ""),
  ("GOV-02", "Services", "Certificates, licences & permits", ["Application", "Verification", "Issuance", "DigiLocker push"], ["Applicant"], ["identity", "gov_id", "property"], ["e-District", "DigiLocker"], ["NIC"], ["s7b", "s7c"], ["decision_or_disclosure"], ""),
  ("GOV-03", "Enforcement", "Regulatory inspection & enforcement", ["Inspections", "Notices", "Penalties"], ["Regulated persons"], ["identity", "any"], ["Case systems"], [], ["s7c", "ex17_1b"], ["decision_or_disclosure"], ""),
  ("GOV-04", "PSU Commercial", "PSU customer business (e.g. banking, energy retail)", ["Customer onboarding", "Billing", "Marketing"], ["Customer"], ["identity", "financial", "contact"], ["CRM/Billing"], ["Vendors"], ["consent", "s7a"], ["processor", "online_presence", "marketing"], "Commercial activity - full DF obligations.")])

# 13 ---------------------------------------------------------------- MANUFACTURING & AUTOMOTIVE
sector("MFG", "Manufacturing, Industrial & Automotive", "Factories, industrial goods, consumer durables, automotive OEMs & dealers, connected products",
 ["Ministry of Labour (Labour Codes)", "State factory inspectorates", "MoRTH (vehicles)", "CERT-In"],
 [("Four Labour Codes (Wages, IR, Social Security, OSH) - in force from 21 Nov 2025 (verify)", "Worker registers, medical examinations, contract labour"),
  ("Factories Act 1948 (as subsumed)", "Health registers for hazardous processes"),
  ("Motor Vehicles Act / AIS standards", "Vehicle telematics, VLTD for commercial vehicles"),
  ("Consumer Protection Act 2019", "Warranty & product liability records")],
 "Connected products & telematics often cloud-hosted abroad by global OEM.",
 [("Worker & wage registers", "Per Labour Codes & rules", "Labour Codes", "verify"),
  ("Statutory medical examination records (hazardous)", "Long retention (often decades) per OSH rules", "OSH Code rules", "verify")],
 ["Large contract/temporary workforce - biometric attendance", "Occupational health records", "Dealer & distributor networks holding customer data", "Connected vehicles/devices (location, driving behaviour)", "Warranty registration & service history"],
 ["Dealers are independent businesses - DF-to-DF sharing vs processor", "Shop-floor paper registers"],
 ["Worker (permanent/contract)", "Dealer/distributor staff", "End customer", "Vehicle owner/driver", "Visitor"],
 [("MFG-01", "Plant HR", "Shop-floor workforce management", ["Contract labour onboarding", "Biometric attendance", "Canteen", "Safety induction"], ["Contract worker", "Employee"], ["identity", "gov_id", "biometric", "financial"], ["HRMS", "Biometric", "Gate system"], ["Manpower contractors"], ["s7i", "s7d"], ["processor", "biometric", "gov_id"], ""),
  ("MFG-02", "EHS", "Occupational health & safety", ["Pre-employment & periodic medicals", "Incident/injury records", "Hazard exposure monitoring"], ["Worker"], ["health", "identity"], ["OHC system"], ["Occupational health vendor"], ["s7i", "s7d", "s7f"], ["processor", "health"], ""),
  ("MFG-03", "Sales & Service", "Dealer network, warranty & service", ["Warranty registration", "Service history", "Customer feedback"], ["End customer"], ["identity", "contact", "vehicle", "transaction"], ["DMS", "CRM"], ["Dealers", "Call centre"], ["consent", "s7a"], ["processor", "marketing", "decision_or_disclosure"], ""),
  ("MFG-04", "Connected Products", "Telematics & IoT data", ["Device/vehicle data", "Location", "Driving behaviour", "OTA updates"], ["Owner", "Driver/user"], ["location", "behavioural", "device_online"], ["IoT cloud"], ["Global OEM cloud", "Telecom"], ["consent", "s7a"], ["processor", "cross_border", "location", "ai"], "")])

# 14 ---------------------------------------------------------------- HOSPITALITY, TRAVEL & AVIATION
sector("HTA", "Hospitality, Travel & Aviation", "Hotels, OTAs, travel agencies, airlines, airports, cruise, tour operators",
 ["Ministry of Tourism", "Bureau of Immigration/FRRO", "DGCA", "BCAS", "CBIC (Customs)", "CERT-In"],
 [("Immigration and Foreigners Act 2025 & rules", "Form C reporting of foreign guests by accommodation providers (verify)"),
  ("Local police orders", "Guest ID collection at hotels"),
  ("Customs (Passenger Name Record Information) Regulations 2022", "Airlines share PNR with Customs"),
  ("DGCA CARs / APIS", "Passenger data"),
  ("DigiYatra policy", "Face biometric, decentralised wallet (consent-based)")],
 "Airline/GDS systems global - cross-border inherent.",
 [("Guest registration records", "Per police/State orders", "Local orders", "verify"),
  ("PNR data (Customs)", "Per 2022 Regulations", "Customs PNR Regs", "verify")],
 ["ID/passport copies stored in email/WhatsApp", "Children travelling", "Loyalty programmes", "Facial recognition (DigiYatra, hotel check-in)", "GDS/cross-border"],
 ["Front desks photocopy Aadhaar - replace with masked/offline verification", "OTA vs hotel - both DFs for booking data"],
 ["Guest", "Accompanying guest (child)", "Passenger", "Loyalty member", "Corporate traveller"],
 [("HTA-01", "Front Office", "Reservation & check-in", ["Booking (direct/OTA)", "ID capture", "Form C for foreigners", "Room key", "Folio"], ["Guest", "Accompanying guests incl. children"], ["identity", "gov_id", "contact", "financial", "images_av"], ["PMS", "Channel manager"], ["OTAs", "Channel manager", "PG", "FRRO"], ["s7a", "s7d"], ["processor", "children", "gov_id", "cross_border"], ""),
  ("HTA-02", "Aviation", "Passenger booking, check-in & boarding", ["Booking", "APIS/PNR", "Check-in", "DigiYatra face boarding", "Special assistance"], ["Passenger", "Minor", "PwD passenger"], ["identity", "gov_id", "biometric", "health", "travel"], ["PSS", "DCS", "DigiYatra"], ["GDS", "Ground handlers", "Customs/BoI"], ["s7a", "s7d", "consent"], ["processor", "cross_border", "children", "pwd", "biometric"], ""),
  ("HTA-03", "Loyalty", "Loyalty & guest preferences", ["Enrolment", "Preference profile", "Partner earn/burn"], ["Member"], ["identity", "preferences", "transaction"], ["Loyalty platform"], ["Partners"], ["consent"], ["processor", "marketing", "cross_border"], "")])

# 15 ---------------------------------------------------------------- REAL ESTATE & HOUSING
sector("REH", "Real Estate, Housing & Property Management", "Developers, brokers, co-working, RWAs/housing societies, facility management, society apps",
 ["State RERA authorities", "Local police", "CERT-In"],
 [("RERA 2016", "Allottee records, project disclosures"),
  ("Local police tenant/domestic help verification orders", "Tenant & staff verification"),
  ("Registration Act 1908", "Property documents")],
 "Society apps often on global cloud.",
 [("Allottee & sale records", "Per RERA / contract / tax", "RERA", "verify")],
 ["Visitor & domestic staff data via society apps", "Tenant KYC shared with police", "Site-visit leads sold between brokers", "CCTV in common areas"],
 ["RWAs are DFs but lack capacity - app vendor as processor", "Brokers' WhatsApp lead forwarding"],
 ["Home buyer", "Tenant", "Resident", "Domestic help", "Visitor", "Broker"],
 [("REH-01", "Sales", "Lead, site visit & booking", ["Enquiry", "Site visit", "Booking & KYC", "Home loan tie-up"], ["Prospect", "Buyer", "Co-applicant"], ["identity", "gov_id", "financial", "contact"], ["CRM", "ERP"], ["Channel partners", "Banks/HFCs"], ["consent", "s7a"], ["processor", "marketing"], ""),
  ("REH-02", "Community", "Residential community & visitor management", ["Resident directory", "Visitor entry", "Domestic help KYC", "Tenant police verification"], ["Resident", "Visitor", "Domestic help", "Tenant"], ["identity", "gov_id", "images_av", "contact"], ["Society app", "CCTV"], ["Society app vendor", "Security agency", "Police"], ["s7a", "consent", "s7d"], ["processor", "gov_id", "cctv", "children"], "")])

# 16 ---------------------------------------------------------------- LOGISTICS & MOBILITY
sector("LOG", "Logistics, Mobility & Gig Platforms", "Courier/3PL, ride-hailing, food & grocery delivery, fleet operators, gig platforms",
 ["MoRTH", "State transport departments", "Ministry of Labour (gig workers)", "CERT-In"],
 [("Motor Vehicle Aggregator Guidelines 2025 (MoRTH)", "Driver verification, data handling, possibly data in India (verify)"),
  ("Code on Social Security 2020", "Aggregator obligations & gig worker registration"),
  ("Legal Metrology/Consumer Protection", "Consumer disputes")],
 "Aggregator guidelines have required data storage on Indian servers for a period (verify current).",
 [("Trip & rider data", "Per aggregator guidelines (verify)", "MoRTH guidelines", "verify")],
 ["Precise location of riders, drivers, recipients", "Driver/rider background checks", "Phone-number masking", "Proof-of-delivery photos/OTP", "Safety features (SOS, recording in cab)"],
 ["Driver = both DP and worker - s.7(i)? (gig workers may not be 'employees') - usually consent/contract basis", "Recipient isn't the customer - notice gap"],
 ["Rider/customer", "Recipient", "Driver/delivery partner", "Merchant"],
 [("LOG-01", "Supply", "Driver/delivery partner onboarding", ["Documents & licence", "Background verification", "Bank details", "Selfie authentication"], ["Driver/partner"], ["identity", "gov_id", "biometric", "financial", "background_check"], ["Partner app"], ["BGV vendors", "Insurers"], ["consent", "s7d"], ["processor", "biometric", "gov_id", "decision_or_disclosure"], ""),
  ("LOG-02", "Operations", "Trips/deliveries & live tracking", ["Booking", "Live location", "Number masking", "POD photos/OTP", "Ratings"], ["Rider", "Recipient", "Driver"], ["location", "contact", "images_av", "behavioural"], ["Dispatch", "Maps", "Telephony"], ["Maps provider", "Telephony masking vendor"], ["s7a", "consent"], ["processor", "location", "cross_border", "ai"], ""),
  ("LOG-03", "Safety", "Safety, incidents & insurance", ["SOS", "Trip audio/video recording", "Incident investigation", "Insurance claims"], ["Rider", "Driver"], ["images_av", "location", "health"], ["Safety platform"], ["Insurers", "Police"], ["s7f", "s7h", "consent"], ["processor", "health", "decision_or_disclosure"], "")])

# 17 ---------------------------------------------------------------- MEDIA, ENTERTAINMENT & OTT
sector("MED", "Media, Entertainment & OTT", "OTT platforms, broadcasters, publishers, music streaming, events & ticketing, ad-tech",
 ["MIB", "MeitY", "TRAI (broadcasting)", "CERT-In"],
 [("IT Rules 2021 Part III - Digital Media Ethics Code", "Age classification (U, U/A 7+, 13+, 16+, A), parental controls, age verification for A content"),
  ("Cable Television Networks (Regulation) Act 1995", "Subscriber management (broadcast)"),
  ("TRAI tariff/QoS regulations (broadcast)", "Subscriber data")],
 "Ad-tech and measurement often cross-border.",
 [("Subscriber records", "Per contract/tax", "Tax laws", "verify")],
 ["Profiles for kids", "Viewing-history profiling & ad targeting", "Contests & reality-show participant data", "Ticketing & event CCTV/face entry"],
 ["Shared household accounts - whose consent?", "Ad-tech bid-stream sharing - hundreds of recipients"],
 ["Subscriber", "Viewer/child profile", "Participant/contestant", "Event attendee"],
 [("MED-01", "Consumer", "Subscription, profiles & viewing", ["Sign-up & payment", "Profiles incl. kids", "Viewing history", "Recommendations"], ["Subscriber", "Child profile"], ["identity", "financial", "behavioural", "device_online"], ["OTT platform"], ["CDN", "PG", "Analytics"], ["consent", "s7a"], ["processor", "children", "tracking_ads", "online_presence", "cross_border"], ""),
  ("MED-02", "Monetisation", "Advertising & audience measurement", ["Ad serving", "Audience segments", "Measurement panels"], ["Viewer"], ["behavioural", "device_online", "inferences"], ["Ad server", "DMP"], ["Ad exchanges", "Measurement cos."], ["consent"], ["processor", "tracking_ads", "children", "cross_border"], ""),
  ("MED-03", "Events", "Ticketing, events & contests", ["Ticket booking", "Entry scanning/face entry", "Contest entries", "Winner publicity"], ["Attendee", "Participant"], ["identity", "contact", "images_av", "biometric"], ["Ticketing", "Contest platform"], ["Ticketing partner", "Security agency"], ["consent", "s7a"], ["processor", "marketing", "biometric", "children"], "")])

# 18 ---------------------------------------------------------------- NGO / NON-PROFIT
sector("NGO", "NGOs, Trusts & Non-profits", "NGOs, trusts, foundations, section 8 companies, CSR implementing agencies, child-care institutions",
 ["MHA (FCRA)", "Income Tax Department", "State Child Protection authorities", "Charity Commissioners"],
 [("FCRA 2010 & Rules", "Foreign contribution & donor records"),
  ("Income-tax (s.80G donor reporting - Form 10BD)", "Donor PAN & donation reporting"),
  ("Juvenile Justice Act 2015 s.74", "Prohibition on disclosure of identity of children"),
  ("Companies Act CSR rules", "Reporting to corporate funders")],
 "Foreign donors/partners - cross-border.",
 [("FCRA accounts & records", "Per FCRA Rules (commonly 6 years)", "FCRA Rules", "verify"),
  ("Donor records", "Per Income-tax & FCRA", "Income-tax", "verify")],
 ["Beneficiaries incl. children, persons with disabilities, patients - vulnerable", "Photos/stories of beneficiaries in fundraising", "Volunteers & field workers with paper forms", "Data sharing with CSR funders and Government"],
 ["Consent literacy in rural/vulnerable populations - oral/assisted consent records", "Excel/WhatsApp as primary systems"],
 ["Beneficiary", "Child beneficiary", "Donor", "Volunteer", "Field worker"],
 [("NGO-01", "Programmes", "Beneficiary enrolment & services", ["Field surveys", "Enrolment", "Service delivery", "Impact tracking"], ["Beneficiary", "Child", "Family"], ["identity", "gov_id", "health", "financial", "family", "location"], ["MIS", "Excel", "Survey apps"], ["Survey app vendor", "Funders"], ["consent"], ["processor", "children", "pwd", "health", "decision_or_disclosure"], ""),
  ("NGO-02", "Fundraising", "Donor management & communications", ["Donations", "80G receipts & 10BD", "Donor comms", "Beneficiary stories"], ["Donor", "Beneficiary in stories"], ["identity", "gov_id", "financial", "images_av"], ["Donor CRM", "PG"], ["PG", "Crowdfunding platforms"], ["consent", "s7d"], ["processor", "marketing", "children"], ""),
  ("NGO-03", "Volunteers", "Volunteer management", ["Registration", "Background checks for child-facing roles", "Assignments"], ["Volunteer"], ["identity", "contact", "background_check"], ["Volunteer platform"], [], ["consent"], ["decision_or_disclosure"], "")])

# 19 ---------------------------------------------------------------- ENERGY & UTILITIES
sector("UTL", "Energy, Utilities & Infrastructure", "Electricity discoms, gas distribution, water utilities, EV charging, renewable retail",
 ["CERC/SERCs", "CEA", "PNGRB", "CERT-In", "Ministry of Power"],
 [("Electricity Act 2003 & Electricity (Rights of Consumers) Rules 2020", "New connection KYC, metering, billing"),
  ("CEA cyber security guidelines/regulations for power sector", "Security controls (verify current instrument)"),
  ("Smart metering (RDSS) standards", "Interval consumption data"),
  ("LPG DBT (PAHAL) & subsidy schemes", "Aadhaar-linked subsidies")],
 "Critical infrastructure; data typically hosted in India.",
 [("Consumer & billing records", "Per SERC regulations / tax", "SERC", "verify")],
 ["Smart meter interval data reveals household behaviour", "Subsidy/DBT linkage", "Field staff with handheld devices", "EV charging location data"],
 ["Legacy consumer masters with no contact data - notice channel is the bill"],
 ["Consumer", "Applicant", "Field staff", "EV user"],
 [("UTL-01", "Customer", "New connection, billing & collections", ["Application & KYC", "Meter installation", "Billing", "Collections & disconnection"], ["Consumer"], ["identity", "gov_id", "financial", "property"], ["CIS/Billing", "Portal"], ["Billing vendor", "PG"], ["s7a", "s7b", "consent"], ["processor", "legacy_data", "online_presence"], ""),
  ("UTL-02", "Metering", "Smart metering & analytics", ["Interval reads", "Load analytics", "Theft detection"], ["Consumer"], ["behavioural", "location", "device_online"], ["MDM/HES"], ["AMISP"], ["s7a", "consent"], ["processor", "ai", "decision_or_disclosure"], "")])

# 20 ---------------------------------------------------------------- PROFESSIONAL SERVICES
sector("PRO", "Professional Services", "Law firms, CA/CS firms, consulting, audit, HR/recruitment consultancies, BGV agencies",
 ["BCI", "ICAI/ICSI/ICMAI", "FIU-IND (PMLA for specified transactions)", "CERT-In"],
 [("Advocates Act 1961 & BCI Rules / BSA 2023 privilege", "Client confidentiality"),
  ("ICAI Code of Ethics", "Confidentiality"),
  ("PMLA 2002 - CAs/CS/CMAs as reporting entities for specified client transactions (2023 notification)", "Client KYC & records"),
  ("DPDP s.17(1)(a)", "Processing for enforcing legal rights/claims")],
 "Global firms share data with network entities abroad.",
 [("Engagement working papers", "Per professional standards (e.g. SA 230: 7 years for audit docs)", "ICAI SA 230", "verify")],
 ["Mixed roles - DF for own clients, processor for client data (payroll, BGV, audit)", "Employee data of clients (payroll/HR outsourcing)", "BGV agencies processing criminal/court records", "Data rooms in M&A"],
 ["Clients send data over email/WhatsApp in bulk", "Working papers retained indefinitely"],
 ["Client (individual)", "Client's employees/customers", "Counterparties", "Candidates"],
 [("PRO-01", "Engagements", "Client intake, KYC & conflicts", ["Engagement letter", "KYC (PMLA where applicable)", "Conflict checks"], ["Client", "Client's beneficial owners"], ["identity", "gov_id", "financial"], ["Practice mgmt"], [], ["s7d", "s7a"], ["gov_id"], ""),
  ("PRO-02", "Delivery", "Processing client data (payroll, audit, BGV, legal)", ["Data receipt", "Working papers", "Deliverables", "Return/destruction"], ["Client's employees/customers", "Candidates"], ["any", "background_check"], ["DMS", "Data rooms"], ["Network firms", "Sub-contractors"], ["s7a", "ex17_1a", "ex17_1e"], ["processor", "cross_border", "decision_or_disclosure"], "")])
