"""Process catalogue - COMMON functions present in (almost) every organisation, any sector.
Tuple: (id, department, process, activities, data_principals, data_categories, typical_systems,
        typical_third_parties, typical_basis, flags, notes)
flags drive the applicability engine; context tags (health/financial/biometric/gov_id/cctv/location/ai)
drive risk scoring.
"""

COMMON = [
    # ---------- HR
    ("CMN-HR-01", "Human Resources", "Recruitment & applicant tracking", ["Job posting & application intake", "CV screening (manual/AI)", "Interview scheduling & notes", "Assessments / psychometric tests", "Offer & rejection communication", "Talent pool retention"], ["Job applicant", "Referrer"], ["identity", "contact", "education", "employment_history", "compensation_expectation", "assessment_results"], ["ATS", "Job portals", "Email", "Video interview tool"], ["Job portals", "Recruitment agencies", "Assessment vendors"], ["consent", "s7a"], ["processor", "online_presence", "decision_or_disclosure", "cross_border", "ai"], "Talent-pool retention beyond the role needs consent; AI screening = decision affecting DP (s.8(3))."),
    ("CMN-HR-02", "Human Resources", "Onboarding & background verification", ["Offer acceptance & joining forms", "KYC/ID collection", "Background verification (education, employment, criminal, address)", "Bank & statutory registration (PF/ESI/UAN)", "Emergency contact & nominee details"], ["Employee", "Employee family/nominee", "Emergency contact"], ["identity", "gov_id", "contact", "financial", "education", "employment_history", "family", "background_check"], ["HRMS", "Email", "BGV portal"], ["BGV agency", "EPFO/ESIC portals"], ["s7i", "s7d"], ["processor", "decision_or_disclosure", "gov_id"], "Family/nominee data belongs to other DPs - notice via employee. BGV agency usually processor."),
    ("CMN-HR-03", "Human Resources", "Payroll, tax & statutory compliance", ["Salary processing", "TDS & Form 16", "PF/ESI/PT/LWF filings", "Reimbursements", "Loans & advances"], ["Employee"], ["identity", "gov_id", "financial", "compensation", "tax"], ["Payroll system", "HRMS", "Banking portal"], ["Payroll outsourcer", "Bank", "Tax consultants"], ["s7i", "s7d"], ["processor", "decision_or_disclosure", "financial", "gov_id"], "Retention: Companies Act 8 yrs; tax laws; labour codes."),
    ("CMN-HR-04", "Human Resources", "Attendance, leave & biometric access", ["Biometric/face attendance", "Leave & shift management", "Geo-attendance for field staff"], ["Employee", "Contract worker"], ["identity", "biometric", "location", "attendance"], ["Biometric devices", "HRMS", "Mobile app"], ["Attendance device vendor"], ["s7i"], ["processor", "biometric", "location"], "Biometric = high-risk context; consider alternatives & strong security."),
    ("CMN-HR-05", "Human Resources", "Employee benefits & insurance", ["Group health/term insurance enrolment", "Dependant details", "Claims support", "Wellness programmes"], ["Employee", "Dependants incl. children"], ["identity", "family", "health", "financial"], ["HRMS", "Insurer/TPA portal"], ["Insurer", "TPA", "Broker", "Wellness vendor"], ["s7i", "consent"], ["processor", "children", "health", "decision_or_disclosure"], "Wellness apps and health-risk assessments are NOT core employment -> consent."),
    ("CMN-HR-06", "Human Resources", "Performance, learning & career", ["Appraisals & ratings", "360 feedback", "Training & certifications", "Promotion/PIP decisions"], ["Employee"], ["employment", "performance", "education"], ["HRMS", "LMS"], ["LMS vendor"], ["s7i"], ["processor", "decision_or_disclosure"], ""),
    ("CMN-HR-07", "Human Resources", "Employee monitoring & investigations", ["Email/DLP monitoring", "Endpoint & web monitoring", "Disciplinary investigations", "POSH complaints"], ["Employee", "Complainant", "Witness"], ["communication_content", "device_online", "employment", "sensitive_allegations"], ["DLP", "SIEM", "Case management"], ["Forensic firms", "External POSH member"], ["s7i"], ["decision_or_disclosure"], "POSH Act confidentiality; proportionality of monitoring."),
    ("CMN-HR-08", "Human Resources", "Exit, full & final and alumni", ["Resignation/termination", "F&F settlement", "Experience letters", "Reference checks", "Alumni network"], ["Ex-employee"], ["identity", "financial", "employment"], ["HRMS"], ["Reference check agencies"], ["s7i", "consent"], ["decision_or_disclosure"], "Alumni network & rehire pools need consent. Apply retention schedule to ex-employee files."),
    ("CMN-HR-09", "Human Resources", "Contract / gig / outsourced workforce", ["Contractor onboarding via agency", "Gate pass & ID", "Wage compliance verification"], ["Contract worker"], ["identity", "gov_id", "financial"], ["Contractor portal", "Access control"], ["Manpower agencies"], ["s7i", "s7d"], ["processor", "gov_id"], "Principal employer vs agency roles - often independent DFs."),
    # ---------- Finance
    ("CMN-FIN-01", "Finance", "Vendor onboarding & payments (individual vendors/consultants)", ["Vendor KYC (PAN, GST, bank)", "Invoice processing", "TDS", "Payments"], ["Individual vendor", "Consultant", "Vendor contact person"], ["identity", "gov_id", "financial", "contact"], ["ERP", "Vendor portal"], ["Bank"], ["s7a", "s7d"], ["financial", "gov_id"], "Contact persons of corporate vendors are DPs too."),
    ("CMN-FIN-02", "Finance", "Customer billing, collections & receivables", ["Invoicing", "Payment collection", "Reminders & collections", "Refunds", "Credit checks"], ["Customer"], ["identity", "contact", "financial", "transaction"], ["ERP", "Billing system", "Payment gateway"], ["Payment gateway", "Collection agency", "Credit bureau"], ["consent", "s7a"], ["processor", "financial", "decision_or_disclosure"], "Collection agency conduct; payment data localisation (RBI) via PG."),
    ("CMN-FIN-03", "Finance", "Expense reimbursement & travel", ["Expense claims with bills", "Travel booking", "Corporate cards"], ["Employee", "Travellers"], ["identity", "financial", "travel", "location"], ["Expense tool", "Travel portal"], ["Travel agency", "Card issuer"], ["s7i"], ["processor", "cross_border"], ""),
    ("CMN-FIN-04", "Finance", "Statutory audit, tax & regulatory filings", ["Books of account", "GST returns", "Income tax assessments", "Auditor access"], ["Customers", "Employees", "Vendors"], ["financial", "transaction", "gov_id"], ["ERP"], ["Statutory auditor", "Tax consultant"], ["s7d", "s7e"], ["decision_or_disclosure"], "Retention: Companies Act 8 yrs; CGST 72 months from annual return due date; Income-tax Act."),
    # ---------- Sales & marketing
    ("CMN-MKT-01", "Marketing", "Website & app analytics, cookies & SDKs", ["Cookie consent banner", "Analytics tracking", "Ad pixels / retargeting", "A/B testing", "Crash & performance SDKs"], ["Website visitor", "App user"], ["device_online", "behavioural", "location"], ["CMP", "Analytics", "Tag manager", "Ad platforms"], ["Analytics providers", "Ad networks", "SDK vendors"], ["consent"], ["processor", "cross_border", "online_presence", "tracking_ads", "children"], "Most common hidden cross-border & children tracking risk. Inventory every SDK/pixel."),
    ("CMN-MKT-02", "Marketing", "Lead generation & CRM", ["Web forms / landing pages", "Purchased/rented lists", "Event & webinar registrations", "Lead scoring", "Sales follow-up"], ["Prospect", "Event attendee"], ["identity", "contact", "professional", "behavioural"], ["CRM", "Marketing automation", "Webinar tool"], ["Lead vendors", "Event platforms"], ["consent"], ["processor", "cross_border", "online_presence", "marketing", "legacy_data"], "Purchased lists: obtain proof of consent from source or don't use."),
    ("CMN-MKT-03", "Marketing", "Email, SMS, WhatsApp & voice campaigns", ["Segmentation", "Campaign dispatch", "Unsubscribe / DND handling"], ["Customer", "Prospect"], ["contact", "preferences", "behavioural"], ["Marketing automation", "SMS gateway", "WhatsApp BSP"], ["SMS aggregator", "Email ESP", "WhatsApp BSP"], ["consent"], ["processor", "cross_border", "marketing", "legacy_data"], "TRAI TCCCPR/DLT; withdrawal propagation to all tools."),
    ("CMN-MKT-04", "Marketing", "Loyalty, referral & contests", ["Loyalty enrolment", "Points & rewards", "Referral programmes (friend's data)", "Contests & testimonials"], ["Customer", "Referred person", "Winner"], ["identity", "contact", "transaction", "images_av"], ["Loyalty platform", "CRM"], ["Loyalty vendor", "Gift fulfilment"], ["consent"], ["processor", "marketing", "online_presence"], "Referred friends did not give consent - use single-use invite only."),
    ("CMN-MKT-05", "Marketing", "Social media & community management", ["Social listening", "Responding to DMs/comments", "Influencer programmes", "User-generated content reuse"], ["Social media users", "Influencers"], ["identity", "contact", "communication_content", "images_av"], ["Social tools"], ["Social platforms", "Agencies"], ["consent", "s7a"], ["processor", "cross_border"], "Publicly available data made public by DP is excluded (s.3(c)(ii)) - but scraping/profiling beyond that is not."),
    # ---------- Customer service
    ("CMN-CS-01", "Customer Service", "Contact centre & call recording", ["Inbound/outbound calls", "IVR", "Call recording", "QA sampling", "Speech analytics"], ["Customer", "Caller"], ["identity", "contact", "voice", "communication_content"], ["Telephony", "CRM", "Recording store"], ["BPO", "Telephony provider"], ["consent", "s7a"], ["processor", "cross_border"], "Recording disclosure at call start; retention of recordings."),
    ("CMN-CS-02", "Customer Service", "Ticketing, chat & chatbots", ["Email/chat/ticket intake", "Chatbot/LLM assistant", "Escalations", "Feedback surveys (CSAT/NPS)"], ["Customer"], ["identity", "contact", "communication_content"], ["Helpdesk", "Chat platform", "LLM API"], ["Helpdesk SaaS", "AI providers"], ["consent", "s7a"], ["processor", "cross_border", "ai"], "LLM providers: check training-on-data terms and location."),
    ("CMN-CS-03", "Customer Service", "Complaints & grievance redressal", ["Complaint intake", "Investigation", "Resolution & closure", "Regulatory ombudsman escalations"], ["Customer", "Complainant"], ["identity", "contact", "communication_content"], ["CRM", "Grievance portal"], [], ["s7a", "s7d"], ["online_presence"], "Also the DPDP grievance channel (s.13, R14(3) 90 days)."),
    # ---------- IT
    ("CMN-IT-01", "IT", "User accounts, IAM & directory", ["Account provisioning", "SSO/MFA", "Access reviews", "Deprovisioning"], ["Employee", "Contractor", "Customer users"], ["identity", "credential", "device_online"], ["AD/Entra ID", "IAM"], ["IAM SaaS"], ["s7i", "s7a"], ["processor", "cross_border"], ""),
    ("CMN-IT-02", "IT", "Email, collaboration & file sharing", ["Mailboxes", "Chat/Teams/Slack", "File shares/OneDrive/Drive", "External sharing"], ["Employee", "Customers", "Any"], ["communication_content", "any"], ["M365 / Google Workspace"], ["Cloud productivity provider"], ["s7i", "s7a"], ["processor", "cross_border"], "Largest unstructured PD store - shadow registers, Excel exports."),
    ("CMN-IT-03", "IT", "Endpoint, MDM & helpdesk", ["Device management", "Remote support sessions", "Asset tagging"], ["Employee"], ["device_online", "location", "identity"], ["MDM", "EDR", "ITSM"], ["MSP"], ["s7i"], ["processor", "location"], "Remote support may expose customer data on screens."),
    ("CMN-IT-04", "IT", "Security logging, SOC & SIEM", ["Log collection", "Threat monitoring", "Incident investigation"], ["Employee", "Customer", "Any"], ["device_online", "identity", "behavioural"], ["SIEM", "EDR", "Firewall"], ["MSSP"], ["s7i", "s7d"], ["processor", "cross_border"], "CERT-In 180-day India logs; MSSP location."),
    ("CMN-IT-05", "IT", "Backup, DR & archival", ["Backups", "DR replication", "Archives/tapes"], ["Any"], ["any"], ["Backup software", "DR site", "Cloud storage"], ["Backup vendor", "Cloud"], ["s7a", "s7d"], ["processor", "cross_border"], "Erasure in backups: document expiry-based approach."),
    ("CMN-IT-06", "IT", "Development, testing & data engineering", ["Test data provisioning", "Data lake / warehouse", "Analytics & BI", "AI/ML model training"], ["Customer", "Employee"], ["any"], ["Data lake", "BI tools", "ML platform"], ["Cloud", "Dev outsourcer"], ["consent", "s7a"], ["processor", "cross_border", "ai", "decision_or_disclosure"], "Data lakes break purpose limitation & erasure - key finding area."),
    # ---------- Admin / facilities
    ("CMN-ADM-01", "Admin & Facilities", "CCTV surveillance", ["Camera recording", "Footage review", "Footage sharing with police", "Retention & overwrite"], ["Visitor", "Employee", "Customer"], ["images_av", "location"], ["NVR/VMS"], ["Security agency", "CCTV AMC vendor"], ["s7i", "s7a", "s7e"], ["processor", "cctv"], "Signage as notice; retention (commonly 30-90 days) per policy/law; police requests log."),
    ("CMN-ADM-02", "Admin & Facilities", "Visitor management", ["Visitor register/kiosk", "ID capture", "Photo capture", "Host notification"], ["Visitor"], ["identity", "contact", "gov_id", "images_av"], ["VMS", "Paper register"], ["Security agency", "VMS SaaS"], ["s7a", "consent"], ["processor", "gov_id"], "Don't photocopy/store full Aadhaar - mask; paper registers are in scope once digitised."),
    ("CMN-ADM-03", "Admin & Facilities", "Physical access control", ["Access cards", "Biometric/face readers", "Access logs"], ["Employee", "Contractor"], ["identity", "biometric", "location"], ["PACS"], ["PACS vendor"], ["s7i"], ["processor", "biometric"], ""),
    ("CMN-ADM-04", "Admin & Facilities", "Transport, cafeteria & events", ["Employee transport with GPS", "Cafeteria wallets", "Event photos"], ["Employee"], ["identity", "location", "financial", "images_av"], ["Transport app", "Wallet"], ["Transport vendor", "Caterer"], ["s7i", "consent"], ["processor", "location"], "Women-safety transport tracking vs minimisation."),
    # ---------- Legal & compliance
    ("CMN-LEG-01", "Legal & Compliance", "Litigation, disputes & legal claims", ["Case files", "Evidence collection", "Legal hold"], ["Counterparties", "Employees", "Customers"], ["any"], ["DMS", "Email"], ["Law firms"], ["ex17_1a"], ["processor"], "s.17(1)(a) exemption: s.8(1),(5) still apply."),
    ("CMN-LEG-02", "Legal & Compliance", "Whistle-blower & ethics hotline", ["Anonymous reports", "Investigations"], ["Whistle-blower", "Accused", "Witness"], ["identity", "communication_content", "sensitive_allegations"], ["Hotline platform"], ["Hotline vendor"], ["s7i", "s7d"], ["processor", "cross_border"], "Protect whistle-blower identity; access rights may be restricted."),
    ("CMN-LEG-03", "Legal & Compliance", "Regulatory reporting & law-enforcement requests", ["Regulatory returns", "Police/agency requests", "Court orders"], ["Customer", "Employee"], ["any"], ["Case register"], ["Regulators", "LEAs"], ["s7c", "s7d", "s7e", "ex17_1c"], ["decision_or_disclosure"], "Maintain disclosure register (supports s.11 recipient listing)."),
    ("CMN-LEG-04", "Legal & Compliance", "Contract management", ["Contract repository", "Signatory details", "e-sign"], ["Signatories", "Counterparty contacts"], ["identity", "contact", "signature"], ["CLM", "e-sign"], ["e-sign provider"], ["s7a"], ["processor", "cross_border"], ""),
    # ---------- Corporate
    ("CMN-CORP-01", "Corporate Secretarial", "Shareholder, director & KMP registers", ["Register of members", "Director KYC (DIR-3)", "Dividend processing", "AGM/e-voting"], ["Shareholder", "Director", "KMP"], ["identity", "gov_id", "financial", "contact"], ["RTA systems", "MCA portal"], ["Registrar & Transfer Agent", "Depositories"], ["s7d"], ["processor", "financial"], ""),
    ("CMN-CORP-02", "CSR & Sustainability", "CSR programmes & beneficiaries", ["Beneficiary registration", "Scholarships", "Health camps", "Impact surveys"], ["Beneficiary", "Children", "Community members"], ["identity", "contact", "health", "financial", "education"], ["CSR portal", "Excel"], ["Implementing NGOs"], ["consent"], ["processor", "children", "health"], "NGO partners: often joint/independent DFs; children & health data frequent."),
    ("CMN-CORP-03", "Procurement", "Supplier & partner management", ["Supplier registration", "Due diligence", "Performance"], ["Supplier contacts"], ["identity", "contact", "professional"], ["Procurement suite"], [], ["s7a"], [], ""),
    # ---------- Digital customer platform (generic)
    ("CMN-DIG-01", "Digital / Product", "Customer account registration & login", ["Sign-up (email/mobile/OTP/social login)", "Profile management", "KYC (if needed)", "Account deletion"], ["Customer / User"], ["identity", "contact", "credential", "device_online"], ["Web/app backend", "Auth provider", "OTP gateway"], ["Cloud", "OTP/SMS provider", "Social login providers"], ["consent", "s7a"], ["processor", "cross_border", "online_presence", "children", "legacy_data"], "Children sign-up risk if service is not age-restricted."),
    ("CMN-DIG-02", "Digital / Product", "Push notifications & in-app messaging", ["Device token registration", "Transactional vs promotional messages"], ["App user"], ["device_online", "behavioural"], ["Push service"], ["Push SDK provider"], ["consent", "s7a"], ["processor", "cross_border", "marketing"], ""),
    ("CMN-DIG-03", "Digital / Product", "Personalisation & recommendations", ["Behavioural profiling", "Recommendation engine", "Segmentation"], ["Customer / User"], ["behavioural", "transaction", "device_online", "location"], ["CDP", "Recommendation engine"], ["CDP vendor"], ["consent"], ["processor", "tracking_ads", "children", "ai"], ""),
]
