"""Layer L1 - Atomic obligation register.

Trigger language (evaluated by the engine against a Processing Activity + Entity Profile):
  always: True                      -> applies to every in-scope activity of a Data Fiduciary
  role:  [data_fiduciary|sdf|consent_manager|state|processor]   (entity profile)
  basis: [consent, s7a, ...]        -> activity.lawful_basis intersects
  flags: [children, pwd, processor, cross_border, third_schedule, decision_or_disclosure,
          legacy_data, online_presence, consent_manager_used, tracking_ads, research]
All listed keys must be satisfied (AND). Values inside a list are OR.
sec = Act section number, used for s.17 exemption logic.
"""

DOMAINS = [
    ("D01", "Governance & Accountability", "Programme ownership, DPO/contact, policies, TOMs, training, accountability of the Data Fiduciary."),
    ("D02", "Scoping, Applicability & Roles", "Territorial/material scope, role determination (DF/Processor/SDF/CM/State), exemptions register."),
    ("D03", "Data Inventory & Mapping", "Processing activity register (RoPA), data flows, systems, data element catalogue. The graph."),
    ("D04", "Lawful Basis & Purpose", "Purpose register; consent vs s.7 legitimate use per purpose; minimisation."),
    ("D05", "Notice", "s.5 / Rule 3 notices incl. legacy notice and language."),
    ("D06", "Consent Lifecycle", "Capture, record, proof, withdrawal, Consent Manager integration."),
    ("D07", "Children & Persons with Disability", "Age-gating, verifiable parental/guardian consent, no tracking/targeted ads, Fourth Schedule."),
    ("D08", "Data Quality", "Completeness, accuracy and consistency for decisions/disclosures."),
    ("D09", "Security Safeguards", "Rule 6 minimum safeguards and supporting ISMS."),
    ("D10", "Breach Management", "Detection, triage, DP intimation, Board 72h report, CERT-In 6h."),
    ("D11", "Retention & Erasure", "Purpose-end erasure, Third Schedule, 48h notice, 1-year log floor, sector retention conflicts."),
    ("D12", "Rights & Grievance", "Access, correction, erasure, nomination, grievance within 90 days."),
    ("D13", "Processor & Third-Party Management", "Contracts, due diligence, oversight, sub-processors, cessation/erasure flow-down."),
    ("D14", "Cross-Border Transfer & Localisation", "Negative list, sectoral localisation, R15 foreign-State access conditions."),
    ("D15", "Significant Data Fiduciary", "DPO in India, independent auditor, annual DPIA & audit, algorithmic due diligence, localisation."),
    ("D16", "Regulatory Interface", "Board inquiries, Govt information calls, voluntary undertaking, appeals, change tracking."),
    ("D17", "State & Research Processing", "Rule 5 / Rule 16 with Second Schedule standards."),
    ("D18", "Consent Manager Operations", "Only for entities registering as Consent Managers (First Schedule)."),
]

# id, domain, title, requirement, act, rule, schedule, actor, phase, penalty, trigger, evidence, sec
OBLIGATIONS = [
    # ---- D01 Governance
    ("OBL-GOV-01", "D01", "Accountability irrespective of processors", "Data Fiduciary remains responsible for compliance for all processing by it or on its behalf, irrespective of any agreement to the contrary or DP failure to perform duties.", "s.8(1)", "", "", "data_fiduciary", 3, "P7", {"always": True}, ["Board-approved privacy policy", "Accountability/RACI matrix", "Management review minutes"], 8.1),
    ("OBL-GOV-02", "D01", "Technical & organisational measures for compliance", "Implement appropriate technical and organisational measures to ensure effective observance of the Act and Rules.", "s.8(4)", "", "", "data_fiduciary", 3, "P7", {"always": True}, ["Privacy programme charter", "Policy suite", "Training records", "Control library with owners"], 8.4),
    ("OBL-GOV-03", "D01", "Publish contact of DPO / responsible person", "Prominently publish on website/app the business contact information of the DPO (if SDF) or a person able to answer DP questions on processing.", "s.8(9)", "R9", "", "data_fiduciary", 3, "P7", {"always": True}, ["Website/app screenshot of contact", "Designation letter"], 8.9),
    ("OBL-GOV-04", "D01", "Contact in every rights response", "Mention the DPO/responsible person contact in every response to a communication from a DP for exercise of rights.", "s.8(9)", "R9", "", "data_fiduciary", 3, "P7", {"always": True}, ["Response templates", "Sample responses"], 8.9),
    ("OBL-GOV-05", "D01", "Lawful purpose only", "Process personal data only for a lawful purpose (not expressly forbidden by law) and only on consent or a s.7 legitimate use.", "s.4(1)", "", "", "data_fiduciary", 3, "P7", {"always": True}, ["Purpose register with lawful basis per purpose"], 4),
    # ---- D02 Scoping
    ("OBL-SCP-01", "D02", "Determine applicability of the Act", "Determine whether processing is of digital personal data in India or outside India in connection with offering goods/services to DPs in India; record exclusions (personal/domestic; publicly made available by DP or under law).", "s.3", "", "", "any", 3, "", {"always": True}, ["Applicability assessment memo"], 3),
    ("OBL-SCP-02", "D02", "Determine role per processing activity", "Determine for each activity whether the entity acts as Data Fiduciary, Data Processor, joint DF, Consent Manager or State; document rationale (who determines purpose and means).", "s.2(i),(k)", "", "", "any", 3, "", {"always": True}, ["Role determination record per activity/contract"], 2),
    ("OBL-SCP-03", "D02", "Document and justify exemptions", "Where s.17 exemption is relied on, document the specific clause, scope, conditions and residual obligations (s.8(1), 8(5) always remain under s.17(1)).", "s.17", "R16", "SCH2", "data_fiduciary", 3, "", {"basis": ["ex17_1a", "ex17_1b", "ex17_1c", "ex17_1d", "ex17_1e", "ex17_1f", "ex17_2a", "ex17_2b", "ex17_3"]}, ["Exemption register entry with legal opinion"], 17),
    ("OBL-SCP-04", "D02", "Monitor SDF notification", "Monitor Central Govt notifications under s.10(1) for designation as SDF (entity or class) and trigger SDF programme on notification.", "s.10(1)", "", "", "data_fiduciary", 3, "", {"always": True}, ["Regulatory change log entry"], 10),
    # ---- D03 Inventory (enabling)
    ("OBL-MAP-01", "D03", "Maintain processing activity register", "Maintain a register of processing activities (purpose, basis, principals, data, systems, recipients, transfers, retention) sufficient to discharge burden of proof and accountability.", "s.6(10), s.8(1),(4)", "", "", "data_fiduciary", 3, "", {"always": True}, ["RoPA / activity register", "Data flow diagrams"], 8.4),
    ("OBL-MAP-02", "D03", "Identify digitised non-digital data", "Identify data collected in non-digital form and subsequently digitised (brought in scope by s.3(a)(ii)) and the point of digitisation.", "s.3(a)", "", "", "data_fiduciary", 3, "", {"always": True}, ["Data event map showing digitisation step"], 3),
    # ---- D04 Lawful basis
    ("OBL-LB-01", "D04", "Specified purpose defined per activity", "Define and record the specified purpose for each processing activity; processing beyond it needs a new basis.", "s.2(za), s.4, s.6(1)", "R3(b)", "", "data_fiduciary", 3, "P7", {"always": True}, ["Purpose register"], 4),
    ("OBL-LB-02", "D04", "Data minimisation for consent", "Consent-based processing limited to personal data necessary for the specified purpose.", "s.6(1)", "", "", "data_fiduciary", 3, "P7", {"basis": ["consent"]}, ["Data element necessity review"], 6),
    ("OBL-LB-03", "D04", "s.7(a) voluntary provision conditions", "Rely on s.7(a) only where DP voluntarily provided data for the specified purpose and has not indicated non-consent to its use.", "s.7(a)", "", "", "data_fiduciary", 3, "P7", {"basis": ["s7a"]}, ["Legitimate-use assessment memo", "Objection handling record"], 7),
    ("OBL-LB-04", "D04", "s.7(c)-(e) legal source identified", "For State function, legal disclosure or court order bases, identify the specific law/order and limit processing to it.", "s.7(c),(d),(e)", "", "", "data_fiduciary", 3, "P7", {"basis": ["s7c", "s7d", "s7e"]}, ["Legal mapping of statute/order to activity"], 7),
    ("OBL-LB-05", "D04", "s.7(f)-(h) emergency use bounded", "Processing for medical emergency, epidemic, disaster or public order is limited to the emergency and documented.", "s.7(f),(g),(h)", "", "", "data_fiduciary", 3, "P7", {"basis": ["s7f", "s7g", "s7h"]}, ["Emergency processing log"], 7),
    ("OBL-LB-06", "D04", "s.7(i) employment use bounded", "Employee data processed without consent only for purposes of employment or safeguarding employer from loss/liability (e.g. espionage, trade secrets, benefits); other uses need consent.", "s.7(i)", "", "", "data_fiduciary", 3, "P7", {"basis": ["s7i"]}, ["Employee purpose register", "HR privacy notice"], 7),
    # ---- D05 Notice
    ("OBL-NOT-01", "D05", "Notice with every consent request", "Every consent request accompanied or preceded by a notice.", "s.5(1)", "R3", "", "data_fiduciary", 3, "P7", {"basis": ["consent"]}, ["Notice versions", "UI screenshots", "Consent flow recording"], 5),
    ("OBL-NOT-02", "D05", "Notice standalone & plain", "Notice presented and understandable independently of other information; clear and plain language.", "s.5(1)", "R3(a),(b)", "", "data_fiduciary", 3, "P7", {"basis": ["consent"]}, ["Notice readability review"], 5),
    ("OBL-NOT-03", "D05", "Itemised data and specified purpose", "Notice gives itemised description of personal data and specified purpose(s) with description of goods/services/uses enabled.", "s.5(1)(i)", "R3(b)", "", "data_fiduciary", 3, "P7", {"basis": ["consent"]}, ["Notice-to-RoPA reconciliation"], 5),
    ("OBL-NOT-04", "D05", "Means to withdraw, exercise rights, complain", "Notice gives the particular communication link/means to withdraw consent (comparable ease), exercise rights and make a complaint to the Board.", "s.5(1)(ii),(iii)", "R3(c)", "", "data_fiduciary", 3, "P7", {"basis": ["consent"]}, ["Notice text", "Working link test"], 5),
    ("OBL-NOT-05", "D05", "Language option", "DP given option to access notice in English or any Eighth Schedule language.", "s.5(3)", "", "", "data_fiduciary", 3, "P7", {"basis": ["consent"]}, ["Language versions", "Language selector screenshot"], 5),
    ("OBL-NOT-06", "D05", "Legacy consent notice", "For consent given before commencement, give notice as soon as reasonably practicable; processing may continue until consent withdrawn.", "s.5(2)", "R3", "", "data_fiduciary", 3, "P7", {"basis": ["consent"], "flags": ["legacy_data"]}, ["Legacy notice campaign plan & delivery logs"], 5),
    # ---- D06 Consent
    ("OBL-CON-01", "D06", "Valid consent standard", "Consent free, specific, informed, unconditional, unambiguous, with clear affirmative action (no pre-ticked boxes, no bundling of unrelated purposes).", "s.6(1)", "", "", "data_fiduciary", 3, "P7", {"basis": ["consent"]}, ["Consent UI review", "Consent per purpose design"], 6),
    ("OBL-CON-02", "D06", "No infringing consent terms", "Consent terms that infringe the Act, Rules or other law are invalid to that extent (e.g. waivers of right to complain).", "s.6(2)", "", "", "data_fiduciary", 3, "P7", {"basis": ["consent"]}, ["Legal review of T&Cs / consent language"], 6),
    ("OBL-CON-03", "D06", "Consent request language & contact", "Consent request in clear plain language, English/Eighth Schedule option, with contact details of DPO or authorised person.", "s.6(3)", "", "", "data_fiduciary", 3, "P7", {"basis": ["consent"]}, ["Consent request screenshots"], 6),
    ("OBL-CON-04", "D06", "Withdrawal with comparable ease", "DP can withdraw consent at any time with ease comparable to giving it.", "s.6(4)", "R3(c)(i)", "", "data_fiduciary", 3, "P7", {"basis": ["consent"]}, ["Withdrawal journey test (clicks/steps vs giving)"], 6),
    ("OBL-CON-05", "D06", "Cease processing after withdrawal", "On withdrawal, cease processing (and cause processors to cease) within reasonable time unless other basis/law requires.", "s.6(6)", "", "", "data_fiduciary", 3, "P7", {"basis": ["consent"]}, ["Withdrawal propagation logs", "Processor instructions"], 6),
    ("OBL-CON-06", "D06", "Proof of notice and consent", "Be able to prove notice was given and consent obtained (burden of proof on DF).", "s.6(10)", "", "", "data_fiduciary", 3, "P7", {"basis": ["consent"]}, ["Consent ledger (who, when, notice version, purpose, channel)"], 6),
    ("OBL-CON-07", "D06", "Accept Consent Manager instructions", "Where DP uses a registered Consent Manager, accept consent/withdrawal via the CM and integrate.", "s.6(7),(8)", "R4", "SCH1", "data_fiduciary", 3, "P7", {"basis": ["consent"], "flags": ["consent_manager_used"]}, ["CM integration spec", "CM event logs"], 6),
    # ---- D07 Children & PwD
    ("OBL-CHD-01", "D07", "Verifiable parental consent", "Obtain verifiable consent of parent before processing a child's (under 18) personal data.", "s.9(1)", "R10", "", "data_fiduciary", 3, "P3", {"flags": ["children"]}, ["Parental consent flow", "Consent records linked to parent identity"], 9),
    ("OBL-CHD-02", "D07", "Verify parent is identifiable adult", "Due diligence that the person claiming to be parent is an identifiable adult using reliable details held, voluntarily provided details, or virtual token from authorised entity (e.g. DigiLocker).", "s.9(1)", "R10(1)", "", "data_fiduciary", 3, "P3", {"flags": ["children"]}, ["Age/identity verification method & logs"], 9),
    ("OBL-CHD-03", "D07", "Age-gating / child identification", "Have a mechanism to determine whether a DP is a child (risk-based age assurance).", "s.9", "R10", "SCH4-B6", "data_fiduciary", 3, "P3", {"flags": ["children"]}, ["Age-gate design", "Risk assessment"], 9),
    ("OBL-CHD-04", "D07", "No detrimental processing", "Do not process children's data in a manner likely to cause detrimental effect on well-being.", "s.9(2)", "", "", "data_fiduciary", 3, "P3", {"flags": ["children"]}, ["Child impact assessment"], 9),
    ("OBL-CHD-05", "D07", "No tracking, behavioural monitoring, targeted ads", "Do not undertake tracking or behavioural monitoring of children or targeted advertising directed at children (unless Fourth Schedule exemption).", "s.9(3)", "R12", "SCH4", "data_fiduciary", 3, "P3", {"flags": ["children"]}, ["Ad-tech/analytics configuration for child accounts", "SDK inventory"], 9),
    ("OBL-CHD-06", "D07", "Fourth Schedule exemption conditions", "Where relying on Fourth Schedule class/purpose, restrict processing strictly to the stated condition (e.g. health services, educational safety, transport location).", "s.9(4)", "R12", "SCH4", "data_fiduciary", 3, "P3", {"flags": ["children"]}, ["Exemption register entry mapped to Sch4 item"], 9),
    ("OBL-PWD-01", "D07", "Verifiable guardian consent (PwD)", "Obtain verifiable consent of lawful guardian for a person with disability who cannot take legally binding decisions.", "s.9(1)", "R11", "", "data_fiduciary", 3, "P3", {"flags": ["pwd"]}, ["Guardian consent records"], 9),
    ("OBL-PWD-02", "D07", "Verify guardian appointment", "Verify guardian appointed by court, designated authority (RPwD Act s.15) or local level committee (National Trust Act s.13).", "s.9(1)", "R11", "", "data_fiduciary", 3, "P3", {"flags": ["pwd"]}, ["Copy of appointment order", "Verification checklist"], 9),
    # ---- D08 Data quality
    ("OBL-DQ-01", "D08", "Accuracy for decisions & disclosures", "Ensure completeness, accuracy and consistency where personal data is used to make a decision affecting the DP or is disclosed to another Data Fiduciary.", "s.8(3)", "", "", "data_fiduciary", 3, "P7", {"flags": ["decision_or_disclosure"]}, ["Data quality rules", "Reconciliation reports"], 8.3),
    # ---- D09 Security
    ("OBL-SEC-01", "D09", "Reasonable security safeguards", "Protect personal data in possession/control, including processing by processors, by reasonable security safeguards to prevent personal data breach.", "s.8(5)", "R6(1)", "", "data_fiduciary", 3, "P1", {"always": True}, ["ISMS scope", "Risk assessment", "Security policy"], 8.5),
    ("OBL-SEC-02", "D09", "Encryption / masking / tokenisation", "Secure personal data through encryption, obfuscation, masking or virtual tokens mapped to it.", "s.8(5)", "R6(1)(a)", "", "data_fiduciary", 3, "P1", {"always": True}, ["Encryption standard", "Key mgmt", "DB/storage config evidence"], 8.5),
    ("OBL-SEC-03", "D09", "Access control to computer resources", "Appropriate measures to control access to computer resources used by DF or processor.", "s.8(5)", "R6(1)(b)", "", "data_fiduciary", 3, "P1", {"always": True}, ["IAM policy", "Access reviews", "PAM logs"], 8.5),
    ("OBL-SEC-04", "D09", "Logging, monitoring & review", "Visibility on access through logs, monitoring and review to detect unauthorised access, investigate and remediate.", "s.8(5)", "R6(1)(c)", "", "data_fiduciary", 3, "P1", {"always": True}, ["Log source inventory", "SIEM use cases", "Review evidence"], 8.5),
    ("OBL-SEC-05", "D09", "Continuity (backups)", "Reasonable measures for continued processing if confidentiality, integrity or availability is compromised, e.g. backups.", "s.8(5)", "R6(1)(d)", "", "data_fiduciary", 3, "P1", {"always": True}, ["Backup policy", "Restore test reports", "BCP/DR"], 8.5),
    ("OBL-SEC-06", "D09", "Retain logs & data 1 year for investigation", "Retain logs and personal data for 1 year (unless other law requires otherwise) for detection, investigation, remediation and continuity.", "s.8(5)", "R6(1)(e)", "", "data_fiduciary", 3, "P1", {"always": True}, ["Log retention config"], 8.5),
    ("OBL-SEC-07", "D09", "Security clauses in processor contracts", "Appropriate provision in DF-processor contract for reasonable security safeguards.", "s.8(5)", "R6(1)(f)", "", "data_fiduciary", 3, "P1", {"flags": ["processor"]}, ["DPA / contract clauses"], 8.5),
    ("OBL-SEC-08", "D09", "TOMs for security observance", "Appropriate technical and organisational measures to ensure effective observance of safeguards.", "s.8(5)", "R6(1)(g)", "", "data_fiduciary", 3, "P1", {"always": True}, ["Security governance", "Audits", "Training"], 8.5),
    # ---- D10 Breach
    ("OBL-BRE-01", "D10", "Intimate affected Data Principals", "On becoming aware of a personal data breach, intimate each affected DP without delay via user account/registered communication: description (nature, extent, timing), likely consequences, mitigation, safety measures, contact.", "s.8(6)", "R7(1)", "", "data_fiduciary", 3, "P2", {"always": True}, ["DP notification template", "Breach register"], 8.6),
    ("OBL-BRE-02", "D10", "Initial intimation to Board", "Without delay: description incl. nature, extent, timing, location and likely impact.", "s.8(6)", "R7(2)(a)", "", "data_fiduciary", 3, "P2", {"always": True}, ["Board intimation template", "Submission acknowledgement"], 8.6),
    ("OBL-BRE-03", "D10", "Detailed report to Board within 72 hours", "Within 72 hours of awareness (or longer as Board allows on written request): updated details, circumstances, mitigation, cause findings, remedial measures, report on DP intimations.", "s.8(6)", "R7(2)(b)", "", "data_fiduciary", 3, "P2", {"always": True}, ["72h report", "RCA"], 8.6),
    ("OBL-BRE-04", "D10", "Breach awareness capability", "Capability to detect and escalate breaches (incl. from processors) so the 'without delay' and 72-hour clocks can be met.", "s.8(5),(6)", "R6(1)(c), R7", "", "data_fiduciary", 3, "P2", {"always": True}, ["IR plan", "Escalation matrix", "Processor breach SLA"], 8.6),
    # ---- D11 Retention & erasure
    ("OBL-RET-01", "D11", "Erase at purpose end or withdrawal", "Erase personal data when DP withdraws consent or as soon as it is reasonable to assume the specified purpose is no longer served, whichever earlier, unless retention needed for compliance with law.", "s.8(7)(a)", "", "", "data_fiduciary", 3, "P7", {"always": True}, ["Retention schedule", "Deletion job logs"], 8.7),
    ("OBL-RET-02", "D11", "Processors erase too", "Cause processors to erase personal data made available to them.", "s.8(7)(b)", "", "", "data_fiduciary", 3, "P7", {"flags": ["processor"]}, ["Erasure certificates from processors"], 8.7),
    ("OBL-RET-03", "D11", "Third Schedule inactivity erasure", "E-commerce (>=2 cr users), online gaming (>=50 lakh), social media (>=2 cr): erase after 3 years from last approach/commencement (except account access & virtual tokens) unless law requires retention.", "s.8(8)", "R8(1)", "SCH3", "data_fiduciary", 3, "P7", {"flags": ["third_schedule"]}, ["Inactivity job config", "User count evidence"], 8.8),
    ("OBL-RET-04", "D11", "48-hour pre-erasure intimation", "At least 48 hours before Third Schedule erasure, inform DP that data will be erased unless they log in/contact.", "s.8(8)", "R8(2)", "SCH3", "data_fiduciary", 3, "P7", {"flags": ["third_schedule"]}, ["Notification template", "Send logs"], 8.8),
    ("OBL-RET-05", "D11", "1-year floor for data, traffic data & logs", "Retain personal data, associated traffic data and processing logs for minimum 1 year from processing for Seventh Schedule purposes, then erase unless other law requires.", "s.8(7)", "R8(3)", "SCH7", "data_fiduciary", 3, "P7", {"always": True}, ["Retention config", "Archive design"], 8.7),
    ("OBL-RET-06", "D11", "Reconciled retention schedule", "Maintain a retention schedule reconciling DPDP erasure with sector/tax/labour retention laws, per data category and purpose.", "s.8(7)", "R8", "", "data_fiduciary", 3, "", {"always": True}, ["Retention schedule with legal citations"], 8.7),
    # ---- D12 Rights
    ("OBL-RGT-01", "D12", "Publish means & identifiers for rights", "Prominently publish on website/app the means to make rights requests and identifiers required (e.g. customer no., mobile, email).", "s.11-14", "R14(1),(5)", "", "data_fiduciary", 3, "P7", {"flags": ["online_presence"]}, ["Rights page screenshot"], 11),
    ("OBL-RGT-02", "D12", "Right to access", "Provide summary of personal data and processing activities, identities of other DFs and processors shared with and description of data shared.", "s.11(1)", "R14(2)", "", "data_fiduciary", 3, "P7", {"basis": ["consent", "s7a"]}, ["Access request SOP", "Response samples"], 11),
    ("OBL-RGT-03", "D12", "Right to correction, completion, updating", "Correct inaccurate/misleading, complete incomplete and update personal data on request.", "s.12(1),(2)", "R14(2)", "", "data_fiduciary", 3, "P7", {"basis": ["consent", "s7a"]}, ["Correction SOP", "Change logs"], 12),
    ("OBL-RGT-04", "D12", "Right to erasure", "Erase on request unless retention necessary for specified purpose or compliance with law.", "s.12(3)", "R14(2)", "", "data_fiduciary", 3, "P7", {"basis": ["consent", "s7a"]}, ["Erasure SOP", "Legal-hold check", "Completion evidence"], 12),
    ("OBL-RGT-05", "D12", "Grievance redressal within 90 days", "Readily available grievance redressal; respond within a period not exceeding 90 days; publish the period; implement TOMs.", "s.8(10), s.13", "R14(3)", "", "data_fiduciary", 3, "P7", {"always": True}, ["Grievance log with ageing", "Published SLA"], 13),
    ("OBL-RGT-06", "D12", "Right to nominate", "Enable DP to nominate individual(s) to exercise rights on death/incapacity, per terms of service and law.", "s.14", "R14(4)", "", "data_fiduciary", 3, "P7", {"basis": ["consent", "s7a"]}, ["Nomination form/flow", "Nominee verification SOP"], 14),
    ("OBL-RGT-07", "D12", "Requester identification", "Verify requester via identifier issued by DF before acting on rights requests.", "s.11-14", "R14(2),(5)", "", "data_fiduciary", 3, "P7", {"always": True}, ["Identity verification SOP"], 11),
    ("OBL-RGT-08", "D12", "Handle requests considering Data Principal duties", "Handle requests in light of DP duties (no false/frivolous grievances, authentic info for correction).", "s.15", "", "SCH-ACT-5", "data_principal", 3, "P5", {"always": True}, ["Rejection reasons log"], 15),
    # ---- D13 Processors
    ("OBL-PRC-01", "D13", "Processor only under valid contract", "Engage/appoint/use a Data Processor only under a valid contract for activities related to offering goods/services.", "s.8(2)", "", "", "data_fiduciary", 3, "P7", {"flags": ["processor"]}, ["Executed contract/DPA"], 8.2),
    ("OBL-PRC-02", "D13", "Processor oversight", "Due diligence and ongoing oversight of processors proportionate to risk (DF remains accountable).", "s.8(1),(5)", "R6(1)(f)", "", "data_fiduciary", 3, "P1", {"flags": ["processor"]}, ["Vendor risk assessment", "Audit/SOC reports"], 8.1),
    ("OBL-PRC-03", "D13", "Flow-down withdrawal & erasure", "Contract/instructions require processor to cease processing on withdrawal and erase at purpose end.", "s.6(6), s.8(7)(b)", "", "", "data_fiduciary", 3, "P7", {"flags": ["processor"]}, ["DPA clauses", "Instruction logs"], 8.7),
    ("OBL-PRC-04", "D13", "Processor breach notification to DF", "Processor must notify DF of breaches promptly (contractual SLA) so DF can meet R7 clocks.", "s.8(6)", "R7", "", "data_fiduciary", 3, "P2", {"flags": ["processor"]}, ["DPA breach clause with SLA"], 8.6),
    # ---- D14 Cross-border
    ("OBL-XB-01", "D14", "No transfer to restricted countries", "Do not transfer personal data to any country/territory restricted by Central Govt notification (negative list).", "s.16(1)", "", "", "data_fiduciary", 3, "P7", {"flags": ["cross_border"]}, ["Transfer register", "Restricted list check"], 16),
    ("OBL-XB-02", "D14", "Foreign-State access conditions", "Meet Central Govt requirements (general/special order) on making personal data available to a foreign State or entity under its control.", "s.16", "R15", "", "data_fiduciary", 3, "P7", {"flags": ["cross_border"]}, ["Transfer impact note", "Order compliance record"], 16),
    ("OBL-XB-03", "D14", "Sectoral localisation prevails", "Comply with sector laws imposing higher protection or localisation (e.g. RBI payment data, IRDAI, SEBI, Govt/MeitY cloud, telecom).", "s.16(2)", "", "", "data_fiduciary", 3, "P7", {"flags": ["cross_border"]}, ["Sector localisation assessment"], 16),
    # ---- D15 SDF
    ("OBL-SDF-01", "D15", "Appoint DPO based in India", "Appoint DPO representing SDF, based in India, responsible to Board of Directors/governing body, point of contact for grievance redressal.", "s.10(2)(a)", "", "", "sdf", 3, "P4", {"role": ["sdf"]}, ["Board resolution", "DPO appointment letter"], 10),
    ("OBL-SDF-02", "D15", "Appoint independent data auditor", "Appoint independent data auditor to evaluate compliance.", "s.10(2)(b)", "", "", "sdf", 3, "P4", {"role": ["sdf"]}, ["Auditor engagement letter", "Independence declaration"], 10),
    ("OBL-SDF-03", "D15", "Annual DPIA", "Conduct DPIA (description of rights, purposes, risk assessment & management) every 12 months from notification.", "s.10(2)(c)(i)", "R13(1)", "", "sdf", 3, "P4", {"role": ["sdf"]}, ["DPIA reports"], 10),
    ("OBL-SDF-04", "D15", "Annual audit", "Conduct audit every 12 months to ensure compliance.", "s.10(2)(c)(ii)", "R13(1)", "", "sdf", 3, "P4", {"role": ["sdf"]}, ["Audit report"], 10),
    ("OBL-SDF-05", "D15", "Report significant observations to Board", "Person conducting DPIA/audit furnishes report of significant observations to the Board.", "s.10(2)", "R13(2)", "", "sdf", 3, "P4", {"role": ["sdf"]}, ["Submission acknowledgement"], 10),
    ("OBL-SDF-06", "D15", "Algorithmic due diligence", "Verify technical measures incl. algorithmic software for hosting, display, upload, modification, publishing, transmission, storage, updating or sharing are not likely to risk DP rights.", "s.10(2)(c)(iii)", "R13(3)", "", "sdf", 3, "P4", {"role": ["sdf"]}, ["Algorithm inventory", "Model risk assessments"], 10),
    ("OBL-SDF-07", "D15", "Localisation of specified data", "Ensure personal data specified by Central Govt (on committee recommendation) and its traffic data is processed within India / not transferred out.", "s.10(2)(c)(iii)", "R13(4)", "", "sdf", 3, "P4", {"role": ["sdf"]}, ["Data residency architecture", "Transfer register"], 10),
    # ---- D16 Regulatory interface
    ("OBL-REG-01", "D16", "Furnish information to Central Govt", "Furnish information to authorised person for Seventh Schedule purposes within the time specified.", "s.36", "R23(1)", "SCH7", "data_fiduciary", 3, "P7", {"always": True}, ["Govt request register", "Response SOP"], 36),
    ("OBL-REG-02", "D16", "Confidentiality of Govt requests", "Do not disclose a Govt information request where so directed (sovereignty/security) without written permission.", "s.36", "R23(2)", "", "data_fiduciary", 3, "P7", {"always": True}, ["Restricted handling SOP"], 36),
    ("OBL-REG-03", "D16", "Cooperate with Board inquiry & directions", "Respond to Board inquiries (digital office), comply with directions/urgent measures and interim orders.", "s.27, s.28", "R20", "", "data_fiduciary", 3, "P7", {"always": True}, ["Regulator correspondence log"], 27),
    ("OBL-REG-04", "D16", "Honour voluntary undertakings", "Comply with any voluntary undertaking accepted by the Board.", "s.32", "", "SCH-ACT-6", "data_fiduciary", 3, "P6", {"always": True}, ["Undertaking tracker"], 32),
    ("OBL-REG-05", "D16", "Appeal within 60 days", "Appeal Board orders to TDSAT within 60 days (digital filing).", "s.29", "R22", "", "data_fiduciary", 3, "", {"always": True}, ["Litigation calendar"], 29),
    # ---- D17 State & research
    ("OBL-STA-01", "D17", "State benefit processing per Second Schedule", "State and instrumentalities processing under s.7(b) follow Second Schedule standards (lawful, purpose-limited, necessary, accurate, retention-limited, secure, intimation, accountable).", "s.7(b)", "R5", "SCH2", "state", 3, "P7", {"basis": ["s7b"]}, ["Scheme-wise processing notes", "Intimation to beneficiaries"], 7),
    ("OBL-RES-01", "D17", "Research/statistics exemption conditions", "Research, archiving or statistical processing exempt only if not used for DP-specific decisions and follows Second Schedule standards.", "s.17(2)(b)", "R16", "SCH2", "data_fiduciary", 3, "", {"basis": ["ex17_2b"]}, ["Research protocol", "De-identification evidence"], 17),
    # ---- D18 Consent Manager operator
    ("OBL-CMO-01", "D18", "Register as Consent Manager", "Register with Board meeting Part A conditions (Indian company, net worth >= Rs 2 cr, capacity, fit & proper, certified interoperable platform).", "s.6(9)", "R4(1)", "SCH1-A", "consent_manager", 2, "P7", {"role": ["consent_manager"]}, ["Registration certificate"], 6),
    ("OBL-CMO-02", "D18", "Platform & data non-readability", "Enable DP to give/manage/review/withdraw consent; ensure personal data contents are not readable by CM.", "s.6(8)", "R4(2)", "SCH1-B1,B2", "consent_manager", 2, "P7", {"role": ["consent_manager"]}, ["Architecture review", "Crypto design"], 6),
    ("OBL-CMO-03", "D18", "Records for 7 years", "Maintain records of consents, notices and sharing; give DP machine-readable access; retain at least 7 years.", "s.6(8)", "R4(2)", "SCH1-B3,B4", "consent_manager", 2, "P7", {"role": ["consent_manager"]}, ["Record retention config"], 6),
    ("OBL-CMO-04", "D18", "No sub-contracting; security; fiduciary capacity", "No sub-contracting/assignment; reasonable security safeguards; act in fiduciary capacity for DP.", "s.6(8)", "R4(2)", "SCH1-B6,B7,B8", "consent_manager", 2, "P7", {"role": ["consent_manager"]}, ["Contracts", "ISMS"], 6),
    ("OBL-CMO-05", "D18", "Conflict of interest & transparency", "Avoid conflicts with DFs; director/KMP restrictions; publish promoters, directors, KMP and shareholding.", "s.6(8)", "R4(2)", "SCH1-B9,B10,B11", "consent_manager", 2, "P7", {"role": ["consent_manager"]}, ["COI policy", "Website disclosures"], 6),
    ("OBL-CMO-06", "D18", "Audit & change of control", "Effective audit mechanism reporting to Board; prior Board approval for transfer of control.", "s.6(8)", "R4(2)", "SCH1-B12,B13", "consent_manager", 2, "P7", {"role": ["consent_manager"]}, ["Audit reports", "Approval letters"], 6),
    # ---- Linked obligations from other Indian laws (apply in parallel)
    ("LNK-CERT-01", "D10", "CERT-In incident report within 6 hours", "Report cyber incidents in Annexure I (incl. data breach/leak) to CERT-In within 6 hours of noticing.", "IT Act s.70B(6)", "CERT-In Directions 28.04.2022 (ii)", "", "any", 0, "", {"always": True}, ["CERT-In reporting SOP", "Submission records"], 0),
    ("LNK-CERT-02", "D09", "ICT logs 180 days within India", "Maintain logs of all ICT systems securely for rolling 180 days within Indian jurisdiction.", "IT Act s.70B(6)", "CERT-In Directions (iv)", "", "any", 0, "", {"always": True}, ["Log retention config", "Log storage location"], 0),
    ("LNK-CERT-03", "D09", "Clock synchronisation", "Synchronise ICT system clocks to NTP of NIC/NPL or traceable source.", "IT Act s.70B(6)", "CERT-In Directions (i)", "", "any", 0, "", {"always": True}, ["NTP config"], 0),
    ("LNK-CERT-04", "D16", "CERT-In Point of Contact", "Designate a Point of Contact to interface with CERT-In.", "IT Act s.70B(6)", "CERT-In Directions (iii)", "", "any", 0, "", {"always": True}, ["PoC designation filed"], 0),
    ("LNK-SPDI-01", "D09", "SPDI Rules 2011 (until Phase 3)", "Until s.44(2) commences, body corporates handling sensitive personal data (passwords, financial, health, sexual orientation, biometrics, medical records) must follow SPDI Rules: privacy policy, written consent for SPD, reasonable security practices (e.g. ISO 27001), grievance officer (1 month).", "IT Act s.43A", "SPDI Rules 2011", "", "any", 0, "", {"always": True}, ["Privacy policy", "ISO 27001 certificate/audit"], 0),
    ("LNK-TRAI-01", "D06", "Commercial communication preferences", "Promotional SMS/voice to Indian numbers only via registered headers/templates on DLT, honour DND preferences and digital consent acquisition.", "TRAI Act", "TCCCPR 2018 (as amended)", "", "any", 0, "", {"flags": ["marketing"]}, ["DLT registrations", "Consent templates"], 0),
    ("LNK-CCPA-01", "D06", "No dark patterns in consent/UI", "Avoid dark patterns (false urgency, basket sneaking, confirm shaming, forced action, subscription traps, interface interference, nagging, drip pricing, disguised ads, bait & switch, SaaS billing, rogue malware, trick question).", "Consumer Protection Act 2019 s.18", "Guidelines for Prevention and Regulation of Dark Patterns 2023", "", "any", 0, "", {"flags": ["online_presence"]}, ["UX dark-pattern audit"], 0),
]
