"""Layer L5 - Control library. Each control satisfies one or more obligations.
Fields: id, domain, title, description, type (Preventive/Detective/Corrective/Directive),
nature (Manual/Automated/IT-dependent manual), frequency, owner_role, obligations,
test_procedure, evidence, iso27001 (2022 Annex A), iso27701 (2019 clause numbering), nist_csf (2.0)
"""

C = []
def ctl(id, dom, title, desc, typ, nat, freq, owner, obls, test, ev, iso, pims, nist):
    C.append(dict(id=id, domain=dom, title=title, description=desc, type=typ, nature=nat,
                  frequency=freq, owner_role=owner, obligations=obls, test=test, evidence=ev,
                  iso27001=iso, iso27701=pims, nist_csf=nist))

# ---------------- D01 Governance
ctl("CTL-GOV-01", "D01", "Privacy programme charter & RACI", "Board/management-approved DPDP programme charter defining scope, accountable executive, DPO/privacy lead, RACI across business, IT, legal, security.", "Directive", "Manual", "Annual review", "Accountable Executive", ["OBL-GOV-01", "OBL-GOV-02"], "Inspect charter approval and RACI; interview 3 process owners on awareness of role.", ["Charter", "RACI", "Approval minutes"], ["5.2", "5.4"], ["5.3", "6.3.1.1"], ["GV.RR-01", "GV.RR-02"])
ctl("CTL-GOV-02", "D01", "Data protection policy suite", "Privacy policy (internal), retention policy, rights handling SOP, breach policy, vendor privacy standard, children's data standard; version-controlled, reviewed annually.", "Directive", "Manual", "Annual", "DPO / Privacy Lead", ["OBL-GOV-02"], "Inspect policies for DPDP coverage vs obligation register; check review dates.", ["Policies with version history"], ["5.1", "5.34"], ["6.2", "6.15.1.4"], ["GV.PO-01", "GV.PO-02"])
ctl("CTL-GOV-03", "D01", "Designated contact person / DPO published", "Designate DPO (SDF) or responsible person; publish business contact on website/app, notices and rights responses.", "Directive", "Manual", "On change", "DPO / Privacy Lead", ["OBL-GOV-03", "OBL-GOV-04", "OBL-CON-03"], "Inspect website/app; sample 5 rights responses for contact details.", ["Screenshots", "Designation letter", "Response samples"], ["5.5"], ["6.3.1.1", "7.3.3"], ["GV.RR-02"])
ctl("CTL-GOV-04", "D01", "Privacy awareness & role-based training", "Induction + annual training for all staff; role-based modules for front-line collection staff, call centre, HR, developers, marketing.", "Preventive", "Manual", "Annual", "HR / Privacy Lead", ["OBL-GOV-02", "OBL-SEC-08"], "Inspect completion rates (target >=95%); sample content against DPDP.", ["LMS report", "Training content"], ["6.3"], ["6.4.2.2"], ["PR.AT-01", "PR.AT-02"])
ctl("CTL-GOV-05", "D01", "Privacy by design gate in change/SDLC", "New/changed processes, products, systems and vendors pass a privacy review (mini-DPIA) before go-live.", "Preventive", "IT-dependent manual", "Per change", "Product / IT Change Board", ["OBL-GOV-02", "OBL-LB-01", "OBL-LB-02"], "Sample 5 recent changes; verify privacy review completed pre-go-live.", ["Change tickets", "Privacy review forms"], ["8.25", "8.27", "5.8"], ["7.2.5", "7.4.1"], ["GV.RM-01", "ID.RA-01"])
ctl("CTL-GOV-06", "D01", "Management reporting & KPIs", "Quarterly privacy dashboard to management/board: readiness %, open findings, rights SLA, breaches, vendor coverage.", "Detective", "Manual", "Quarterly", "DPO / Privacy Lead", ["OBL-GOV-01"], "Inspect last 2 quarterly reports and minutes.", ["Dashboards", "Minutes"], ["5.35", "9.3"], ["5.6"], ["GV.OV-01", "GV.OV-03"])
ctl("CTL-GOV-07", "D01", "Lawful-purpose screening", "Legal screen that each purpose is not forbidden by law and has a basis (consent or s.7).", "Preventive", "Manual", "Per new purpose", "Legal", ["OBL-GOV-05", "OBL-LB-01"], "Sample purposes; verify legal screen recorded.", ["Purpose register entries"], ["5.31"], ["7.2.1", "7.2.2"], ["GV.OC-03"])

# ---------------- D02 Scoping
ctl("CTL-SCP-01", "D02", "Applicability & entity profile assessment", "Documented s.3 applicability, role(s), SDF likelihood, Third Schedule status, children/PwD exposure, sector regulators. Refreshed annually or on business change.", "Directive", "Manual", "Annual", "DPO / Legal", ["OBL-SCP-01", "OBL-SCP-04"], "Inspect entity profile; verify it matches business reality (products, geos, user counts).", ["Entity Applicability Profile"], ["5.31"], ["5.2.1"], ["GV.OC-01", "GV.OC-03"])
ctl("CTL-SCP-02", "D02", "Role determination per activity & contract", "For each activity and each third-party relationship record DF/processor/joint-DF status with rationale.", "Directive", "Manual", "Per activity/contract", "Legal / Privacy", ["OBL-SCP-02"], "Sample 10 vendor contracts; compare role recorded vs actual control of purpose/means.", ["Role register"], ["5.31"], ["7.2.7", "8.2.1"], ["GV.OC-02"])
ctl("CTL-SCP-03", "D02", "Exemption register", "Register of s.7/s.17/Sch4 reliance with clause, scope, residual obligations, legal owner and review date.", "Directive", "Manual", "Annual", "Legal", ["OBL-SCP-03", "OBL-CHD-06", "OBL-RES-01"], "Inspect entries; test that residual obligations (s.8(1),(5)) are still covered.", ["Exemption register"], ["5.31"], ["7.2.2"], ["GV.OC-03"])
ctl("CTL-SCP-04", "D02", "Regulatory change monitoring", "Track MeitY/Board notifications (SDF, restricted countries, s.17 notifications, FAQs), sector regulators and CERT-In; impact-assess within 30 days.", "Detective", "Manual", "Monthly", "Legal / Compliance", ["OBL-SCP-04", "OBL-XB-01", "OBL-XB-02"], "Inspect change log; verify last notification impact assessed.", ["Regulatory change log"], ["5.31", "5.6"], ["5.2.1"], ["GV.OC-03"])

# ---------------- D03 Inventory
ctl("CTL-MAP-01", "D03", "Processing activity register (RoPA)", "Graph-based register linking department > process > activity > data events > purpose > basis > data elements > systems > recipients > transfers > retention.", "Directive", "IT-dependent manual", "Semi-annual refresh", "Process Owners / Privacy", ["OBL-MAP-01", "OBL-CON-06"], "Select 3 processes; walkthrough and reconcile to register; check completeness of mandatory fields.", ["Register export", "Walkthrough notes"], ["5.9", "5.12"], ["7.2.8"], ["ID.AM-07", "ID.AM-08"])
ctl("CTL-MAP-02", "D03", "Data flow diagrams incl. digitisation points", "Level-1 data flows per process showing entry channels, digitisation, systems, internal/external recipients and cross-border hops.", "Directive", "Manual", "Semi-annual", "Process Owners / Architecture", ["OBL-MAP-01", "OBL-MAP-02"], "Compare DFD to system integration list and firewall/API gateway rules.", ["DFDs"], ["5.9", "5.14"], ["7.2.8", "7.5.3"], ["ID.AM-03"])
ctl("CTL-MAP-03", "D03", "System & shadow-data discovery", "Automated/semi-automated discovery of personal data in databases, file shares, email, SaaS, endpoints (DLP/data discovery scans) incl. Excel/WhatsApp/shadow IT.", "Detective", "Automated", "Quarterly", "IT Security", ["OBL-MAP-01", "OBL-SEC-01"], "Inspect last scan coverage and reconciliation of findings to register.", ["Scan reports", "Reconciliation log"], ["5.9", "8.12"], ["7.2.8"], ["ID.AM-07", "DE.CM-09"])
ctl("CTL-MAP-04", "D03", "Data element catalogue & classification", "Standard catalogue of data elements with category and context flags (health, financial, biometric, children, gov ID).", "Directive", "Manual", "Annual", "Data Governance", ["OBL-MAP-01", "OBL-LB-02"], "Sample 20 fields from 2 systems; verify mapped to catalogue.", ["Catalogue", "Mapping"], ["5.12", "5.13"], ["7.4.1"], ["ID.AM-07"])

# ---------------- D04 Lawful basis
ctl("CTL-LB-01", "D04", "Purpose register with lawful basis", "Each purpose recorded with basis: consent or specific s.7 clause, with justification memo for each s.7 reliance.", "Directive", "Manual", "Per purpose", "Legal / Privacy", ["OBL-LB-01", "OBL-LB-03", "OBL-LB-04", "OBL-LB-05", "OBL-GOV-05"], "Sample 10 purposes; verify basis and memo; challenge s.7 reliance.", ["Purpose register", "Memos"], ["5.31"], ["7.2.1", "7.2.2"], ["GV.OC-03"])
ctl("CTL-LB-02", "D04", "Data minimisation review", "Field-by-field necessity review of forms, APIs and system fields vs purpose; remove unnecessary fields.", "Preventive", "Manual", "Annual + per change", "Product / Process Owner", ["OBL-LB-02", "OBL-CON-01"], "Sample 3 forms; check each field has purpose link.", ["Minimisation worksheet"], ["5.34"], ["7.4.1", "7.4.4"], ["PR.DS-01"])
ctl("CTL-LB-03", "D04", "Employee data purpose boundary", "HR purpose register separating s.7(i) employment purposes from consent-based (e.g. wellness, marketing, photos on social media).", "Directive", "Manual", "Annual", "HR / Legal", ["OBL-LB-06"], "Inspect HR register and employee notice; sample 3 non-core HR uses for consent.", ["HR purpose register", "Employee notice"], ["6.1", "5.34"], ["7.2.2"], ["GV.OC-03"])
ctl("CTL-LB-04", "D04", "Secondary-use & repurposing control", "Any new use of existing data (analytics, AI training, cross-sell, sharing with group) requires purpose-compatibility review and new basis if needed.", "Preventive", "Manual", "Per request", "Privacy / Data Governance", ["OBL-LB-01", "OBL-CON-01"], "Sample analytics/AI projects; verify review.", ["Review records"], ["5.34"], ["7.4.2"], ["GV.PO-01"])

# ---------------- D05 Notice
ctl("CTL-NOT-01", "D05", "Rule 3 notice standard & templates", "Master notice template (standalone, itemised data, purposes, goods/services, withdraw/rights/Board complaint links) plus channel variants (web, app, paper, IVR, branch, field agent).", "Directive", "Manual", "Annual", "Privacy / Legal", ["OBL-NOT-01", "OBL-NOT-02", "OBL-NOT-03", "OBL-NOT-04"], "Inspect templates vs Rule 3 checklist; sample live notices on 3 channels.", ["Templates", "Screenshots", "Paper forms"], ["5.34"], ["7.3.2", "7.3.3"], ["GV.PO-01"])
ctl("CTL-NOT-02", "D05", "Notice-to-register reconciliation", "Each notice's itemised data and purposes reconciled to the purpose register; drift flagged on change.", "Detective", "Manual", "Semi-annual", "Privacy", ["OBL-NOT-03"], "Reconcile 3 notices with register.", ["Reconciliation sheet"], ["5.34"], ["7.3.2"], ["ID.IM-01"])
ctl("CTL-NOT-03", "D05", "Multilingual notice availability", "Notices available in English + Eighth Schedule languages relevant to customer base (based on geography/channel), with language selector.", "Preventive", "Manual", "Annual", "Marketing / Privacy", ["OBL-NOT-05", "OBL-CON-03"], "Check language coverage vs customer geography data.", ["Language versions"], ["5.34"], ["7.3.3"], ["GV.PO-01"])
ctl("CTL-NOT-04", "D05", "Notice versioning", "Notices versioned with effective dates; version ID stored with each consent record.", "Directive", "IT-dependent manual", "Per change", "Privacy / IT", ["OBL-CON-06", "OBL-NOT-01"], "Pick 5 consent records; trace to notice version text.", ["Version repository", "Consent records"], ["5.33"], ["7.2.8", "7.3.3"], ["PR.DS-01"])
ctl("CTL-NOT-05", "D05", "Legacy customer notice campaign", "Identify pre-commencement consent base; deliver s.5(2) notice via email/SMS/app/branch; log delivery and withdrawals.", "Corrective", "IT-dependent manual", "One-time + stragglers", "Marketing / Privacy", ["OBL-NOT-06"], "Inspect campaign coverage %, bounce handling, withdrawal handling.", ["Campaign logs"], ["5.34"], ["7.3.3"], ["GV.PO-01"])

# ---------------- D06 Consent
ctl("CTL-CON-01", "D06", "Consent capture design standard", "Granular per-purpose consent, unticked by default, affirmative action, not conditional on unnecessary purposes, no dark patterns; UX review checklist.", "Preventive", "Manual", "Per change", "Product / UX", ["OBL-CON-01", "OBL-CON-02", "LNK-CCPA-01"], "Walk through 3 journeys; check granularity, defaults, bundling, dark patterns.", ["UX review", "Screen recordings"], ["5.34"], ["7.2.3", "7.2.4"], ["PR.DS-01"])
ctl("CTL-CON-02", "D06", "Consent ledger (proof of consent)", "Central immutable log: principal ID, purpose(s), notice version, channel, timestamp, method, withdrawal events, CM reference.", "Preventive", "Automated", "Continuous", "IT / Privacy", ["OBL-CON-06", "OBL-CON-04"], "Sample 25 principals; verify complete ledger records; test tamper protection.", ["Ledger extract", "Integrity controls"], ["8.15", "5.33"], ["7.2.8", "7.2.4"], ["PR.DS-01", "PR.PS-04"])
ctl("CTL-CON-03", "D06", "Withdrawal with comparable ease", "Withdrawal available on same channel(s) as consent, same or fewer steps; offline equivalents (branch/IVR/SMS keyword).", "Preventive", "IT-dependent manual", "Per change", "Product", ["OBL-CON-04", "OBL-NOT-04"], "Count steps give vs withdraw on 3 channels.", ["Journey comparison"], ["5.34"], ["7.3.4"], ["PR.DS-01"])
ctl("CTL-CON-04", "D06", "Withdrawal propagation", "Withdrawal events propagate to all downstream systems and processors within defined SLA (e.g. 48-72h) with reconciliation.", "Corrective", "Automated", "Continuous + monthly recon", "IT / Data Engineering", ["OBL-CON-05", "OBL-PRC-03"], "Withdraw test consent; trace to CRM, marketing, data lake, processors.", ["Propagation logs", "Recon report"], ["5.14"], ["7.3.4", "7.3.7"], ["PR.DS-01"])
ctl("CTL-CON-05", "D06", "Consent Manager integration", "Integration with registered Consent Managers (APIs, event handling, reconciliation) once regime is live (Phase 2).", "Preventive", "Automated", "Continuous", "IT / Privacy", ["OBL-CON-07"], "Review integration spec and test events.", ["Integration spec", "Logs"], ["5.14"], ["7.3.4"], ["PR.DS-01"])
ctl("CTL-CON-06", "D06", "Marketing consent & DLT compliance", "Marketing uses separate consent; SMS/voice via DLT registered headers/templates; DND scrubbing; unsubscribe honoured.", "Preventive", "Automated", "Continuous", "Marketing", ["LNK-TRAI-01", "OBL-CON-01", "OBL-CON-05"], "Sample 3 campaigns; verify consent filter and DLT.", ["Campaign audience rules", "DLT records"], ["5.34"], ["7.3.4"], ["PR.DS-01"])

# ---------------- D07 Children & PwD
ctl("CTL-CHD-01", "D07", "Age assurance / age-gate", "Risk-based age assurance at onboarding (declaration + signals + verification where high risk).", "Preventive", "Automated", "Continuous", "Product", ["OBL-CHD-03"], "Attempt onboarding as minor on 2 channels.", ["Age-gate design", "Test results"], ["5.34"], ["7.2.3"], ["PR.AA-02"])
ctl("CTL-CHD-02", "D07", "Verifiable parental consent workflow", "Parent identity/age verified via held records, voluntary details or DigiLocker/authorised virtual token; parent-child link recorded.", "Preventive", "IT-dependent manual", "Per onboarding", "Product / Ops", ["OBL-CHD-01", "OBL-CHD-02"], "Sample 10 child accounts; verify parent verification evidence.", ["Workflow", "Verification logs"], ["5.34"], ["7.2.4"], ["PR.AA-02"])
ctl("CTL-CHD-03", "D07", "Child-safe processing configuration", "For child accounts: tracking/behavioural analytics & targeted ads disabled at SDK/ad-server level; profiling blocked.", "Preventive", "Automated", "Continuous", "Product / Ad-tech", ["OBL-CHD-04", "OBL-CHD-05"], "Inspect SDK/ad config; network capture on child account.", ["Config", "Traffic capture"], ["5.34", "8.9"], ["7.4.2"], ["PR.PS-01"])
ctl("CTL-CHD-04", "D07", "Fourth Schedule exemption scoping", "Where exemption relied on, processing limited to Sch4 condition; documented in exemption register.", "Directive", "Manual", "Annual", "Legal", ["OBL-CHD-06"], "Compare actual use vs Sch4 condition.", ["Exemption register"], ["5.31"], ["7.2.2"], ["GV.OC-03"])
ctl("CTL-PWD-01", "D07", "Lawful guardian verification", "Checklist to verify guardian appointment order (court/RPwD designated authority/National Trust LLC) before accepting consent.", "Preventive", "Manual", "Per case", "Ops", ["OBL-PWD-01", "OBL-PWD-02"], "Sample guardian cases; verify orders on file.", ["Orders", "Checklist"], ["5.34"], ["7.2.4"], ["PR.AA-02"])

# ---------------- D08 Data quality
ctl("CTL-DQ-01", "D08", "Data quality rules for decisioning & disclosures", "Validation, deduplication and reconciliation for data used in decisions (credit, eligibility, hiring, claims) or disclosed to other DFs (bureaus, regulators, partners).", "Preventive", "Automated", "Continuous", "Data Governance", ["OBL-DQ-01"], "Inspect DQ rules & exception reports for 2 decision systems.", ["DQ rules", "Exception reports"], ["8.28"], ["7.4.3"], ["PR.DS-01"])
ctl("CTL-DQ-02", "D08", "Correction propagation", "Corrections made on DP request propagate to systems and recipients who received the data.", "Corrective", "IT-dependent manual", "Per request", "Ops / IT", ["OBL-DQ-01", "OBL-RGT-03"], "Trace 3 corrections downstream.", ["Change logs"], ["5.14"], ["7.3.7"], ["PR.DS-01"])

# ---------------- D09 Security (Rule 6)
ctl("CTL-SEC-01", "D09", "ISMS & security risk assessment", "ISMS covering personal-data systems; annual risk assessment with personal data impact.", "Directive", "Manual", "Annual", "CISO", ["OBL-SEC-01", "OBL-SEC-08", "LNK-SPDI-01"], "Inspect ISMS scope includes all PD systems; risk register.", ["ISMS scope", "Risk register", "ISO cert"], ["5.1", "6.1.2", "8.2"], ["6.2"], ["GV.RM-01", "ID.RA-01"])
ctl("CTL-SEC-02", "D09", "Encryption at rest & in transit", "Personal data encrypted at rest (DB/storage/backups/endpoints) and in transit (TLS 1.2+); key management with rotation.", "Preventive", "Automated", "Continuous", "IT Security", ["OBL-SEC-02"], "Inspect configs for in-scope DBs, storage, laptops; TLS scan.", ["Config screenshots", "KMS policy", "TLS scan"], ["8.24"], ["6.7.1.1", "7.4.9"], ["PR.DS-01", "PR.DS-02"])
ctl("CTL-SEC-03", "D09", "Masking, tokenisation & pseudonymisation", "Masking in UIs/reports for non-need roles (e.g. Aadhaar, PAN, card, account); tokenisation for identifiers; masked data in non-prod.", "Preventive", "Automated", "Continuous", "IT / App Owners", ["OBL-SEC-02"], "Log in as low-privilege role; inspect non-prod data samples.", ["Screenshots", "Masking config"], ["8.11", "8.33"], ["7.4.5"], ["PR.DS-01"])
ctl("CTL-SEC-04", "D09", "Identity & access management", "RBAC/least privilege, MFA for remote and privileged access, joiner-mover-leaver, quarterly access reviews for PD systems.", "Preventive", "IT-dependent manual", "Quarterly review", "IT / System Owners", ["OBL-SEC-03"], "Sample leavers and movers; inspect last access review; MFA coverage.", ["Access reviews", "JML tickets", "MFA report"], ["5.15", "5.16", "5.18", "8.2", "8.3", "8.5"], ["6.6"], ["PR.AA-01", "PR.AA-05"])
ctl("CTL-SEC-05", "D09", "Privileged access management", "Vaulted privileged credentials, session recording for DB/admin access to PD stores.", "Preventive", "Automated", "Continuous", "IT Security", ["OBL-SEC-03", "OBL-SEC-04"], "Inspect PAM coverage of PD DBs; sample sessions.", ["PAM reports"], ["8.2", "8.18"], ["6.6.2"], ["PR.AA-05"])
ctl("CTL-SEC-06", "D09", "Logging & monitoring of personal data access", "Access logs for PD systems (who accessed what record) centralised in SIEM; use cases for bulk export, unusual access, privileged misuse; periodic review.", "Detective", "Automated", "Continuous", "SOC", ["OBL-SEC-04", "OBL-BRE-04"], "Inspect log source coverage and 3 alerts investigated.", ["SIEM coverage", "Alert tickets"], ["8.15", "8.16"], ["6.9.4"], ["DE.CM-01", "DE.CM-03", "DE.AE-02"])
ctl("CTL-SEC-07", "D09", "Log & data retention for investigation (1 yr / 180 d India)", "Logs and relevant PD retained >= 1 year (Rule 6(1)(e), Rule 8(3)); ICT logs rolling 180 days in India (CERT-In).", "Preventive", "Automated", "Continuous", "IT / SOC", ["OBL-SEC-06", "OBL-RET-05", "LNK-CERT-02"], "Inspect retention settings and storage region.", ["Retention config"], ["8.15"], ["7.4.7"], ["PR.PS-04"])
ctl("CTL-SEC-08", "D09", "Backup & restore", "Backups of PD systems, encrypted, tested restores, DR aligned to RTO/RPO.", "Corrective", "Automated", "Per schedule; restore test quarterly", "IT Ops", ["OBL-SEC-05"], "Inspect backup jobs and last restore test.", ["Backup reports", "Restore tests"], ["8.13", "5.30"], ["6.9.3"], ["PR.DS-11", "RC.RP-03"])
ctl("CTL-SEC-09", "D09", "Vulnerability & patch management", "Scanning and patching of PD-hosting systems; annual VAPT of internet-facing apps.", "Preventive", "Automated", "Monthly scans; annual VAPT", "IT Security", ["OBL-SEC-01"], "Inspect scan/VAPT reports and closure.", ["Reports", "Closure evidence"], ["8.8"], ["6.9.6"], ["ID.RA-01", "PR.PS-02"])
ctl("CTL-SEC-10", "D09", "DLP & data exfiltration controls", "DLP on email/web/endpoint/USB for PD patterns (Aadhaar, PAN, card, health terms); block/alert.", "Detective", "Automated", "Continuous", "IT Security", ["OBL-SEC-01", "OBL-SEC-04"], "Inspect policies; test with dummy data.", ["DLP policies", "Incidents"], ["8.12"], ["6.5.3"], ["PR.DS-01", "DE.CM-01"])
ctl("CTL-SEC-11", "D09", "Physical & paper record security", "Secure storage, access registers and shredding for paper forms/files before and after digitisation.", "Preventive", "Manual", "Continuous", "Admin / Facilities", ["OBL-SEC-01"], "Site walkthrough; inspect storage and shredding logs.", ["Walkthrough notes", "Shredding certificates"], ["7.1", "7.2", "7.10", "7.14"], ["6.8"], ["PR.AA-06"])
ctl("CTL-SEC-12", "D09", "Secure SDLC & non-prod data", "Secure coding, privacy test cases, no production PD in dev/test without masking.", "Preventive", "IT-dependent manual", "Per release", "Engineering", ["OBL-SEC-01", "OBL-SEC-02"], "Sample releases; inspect test data sources.", ["SDLC artefacts"], ["8.25", "8.28", "8.31", "8.33"], ["6.11.3.1"], ["PR.PS-06"])
ctl("CTL-SEC-13", "D09", "Clock synchronisation", "All ICT systems synchronised to NIC/NPL NTP or traceable source.", "Preventive", "Automated", "Continuous", "IT Ops", ["LNK-CERT-03", "OBL-SEC-04"], "Sample 10 systems' NTP config.", ["NTP config"], ["8.17"], [], ["PR.PS-04"])
ctl("CTL-SEC-14", "D09", "Endpoint & mobile device security", "Disk encryption, EDR, MDM for devices handling PD incl. field-agent tablets and BYOD.", "Preventive", "Automated", "Continuous", "IT", ["OBL-SEC-02", "OBL-SEC-03"], "Inspect MDM/EDR coverage report.", ["Coverage reports"], ["8.1", "8.7"], ["6.3.2"], ["PR.PS-01"])

# ---------------- D10 Breach
ctl("CTL-BRE-01", "D10", "Incident response plan with DPDP & CERT-In clocks", "IR plan with severity matrix, personal-data breach criteria, clocks (CERT-In 6h, Board without delay + 72h, DP without delay, sector regulators), roles and templates.", "Corrective", "Manual", "Annual review", "CISO / DPO", ["OBL-BRE-01", "OBL-BRE-02", "OBL-BRE-03", "OBL-BRE-04", "LNK-CERT-01"], "Inspect plan; verify clocks and templates present.", ["IR plan", "Templates"], ["5.24", "5.25", "5.26"], ["6.13.1.1", "6.13.1.5"], ["RS.MA-01", "RS.CO-02"])
ctl("CTL-BRE-02", "D10", "Breach register & decision log", "Log of all incidents with PD impact assessment, awareness timestamp, notification decisions and timestamps per regulator/DP.", "Detective", "Manual", "Per incident", "DPO", ["OBL-BRE-01", "OBL-BRE-02", "OBL-BRE-03"], "Sample incidents; verify timestamps vs clocks.", ["Breach register"], ["5.27", "5.28"], ["6.13.1.5"], ["RS.AN-03", "RS.MA-02"])
ctl("CTL-BRE-03", "D10", "DP notification capability", "Ability to identify affected principals and notify at scale (email/SMS/app/letters) within hours; content per Rule 7(1).", "Corrective", "IT-dependent manual", "Tested annually", "Privacy / Comms", ["OBL-BRE-01"], "Tabletop: produce affected list & notice in < 24h.", ["Tabletop report"], ["5.26"], ["6.13.1.5"], ["RS.CO-03"])
ctl("CTL-BRE-04", "D10", "Breach tabletop exercises", "Annual tabletop incl. processor-originated breach and ransomware scenario.", "Detective", "Manual", "Annual", "CISO / DPO", ["OBL-BRE-04"], "Inspect exercise report and actions.", ["Exercise reports"], ["5.24", "5.30"], ["6.13.1.1"], ["ID.IM-02", "RS.MA-01"])

# ---------------- D11 Retention
ctl("CTL-RET-01", "D11", "Reconciled retention schedule", "Retention schedule per record type/purpose citing DPDP (purpose end, 1-yr floor, Sch3) and sector/tax/labour laws; legal hold process.", "Directive", "Manual", "Annual", "Legal / Records", ["OBL-RET-01", "OBL-RET-05", "OBL-RET-06"], "Inspect schedule; sample 5 record types for legal basis.", ["Retention schedule"], ["5.33"], ["7.4.7"], ["GV.PO-01"])
ctl("CTL-RET-02", "D11", "Automated deletion / anonymisation jobs", "System-level deletion or irreversible anonymisation at retention expiry incl. data lake, backups (expiry), archives, logs.", "Corrective", "Automated", "Scheduled", "IT / App Owners", ["OBL-RET-01", "OBL-RGT-04"], "Inspect job configs; query for records past expiry.", ["Job logs", "Expiry query"], ["8.10"], ["7.4.5", "7.4.8"], ["PR.DS-01"])
ctl("CTL-RET-03", "D11", "Third Schedule inactivity engine", "Track last-approach date; 48h pre-erasure notice; erase at 3 years (exclude account access & wallet tokens).", "Corrective", "Automated", "Daily", "Product / IT", ["OBL-RET-03", "OBL-RET-04"], "Inspect logic and sample notices.", ["Job config", "Notice logs"], ["8.10"], ["7.4.7"], ["PR.DS-01"])
ctl("CTL-RET-04", "D11", "Processor erasure certification", "Processors return/erase data at contract end or instruction; certificate obtained.", "Corrective", "Manual", "Per event", "Procurement / Privacy", ["OBL-RET-02", "OBL-PRC-03"], "Sample 3 terminated vendors for certificates.", ["Certificates"], ["5.20", "8.10"], ["8.4.2"], ["GV.SC-10"])
ctl("CTL-RET-05", "D11", "Paper record disposal", "Paper forms destroyed after digitisation/retention per schedule with shredding records.", "Corrective", "Manual", "Scheduled", "Admin", ["OBL-RET-01"], "Inspect shredding logs vs schedule.", ["Logs"], ["7.14"], ["7.4.8"], ["PR.DS-01"])

# ---------------- D12 Rights
ctl("CTL-RGT-01", "D12", "Rights & grievance intake channels", "Published channels (web form, app, email, branch, call centre) with required identifiers; all route to a single tracked queue.", "Directive", "IT-dependent manual", "Continuous", "Customer Service / DPO", ["OBL-RGT-01", "OBL-RGT-05"], "Submit test requests on 2 channels; verify logged.", ["Rights page", "Queue"], ["5.34"], ["7.3.9"], ["GV.PO-01"])
ctl("CTL-RGT-02", "D12", "Rights handling SOP & SLA tracking", "SOP per right (access, correction, erasure, nomination, grievance) with internal SLA well within 90 days, ageing report and escalation.", "Directive", "IT-dependent manual", "Weekly ageing", "DPO", ["OBL-RGT-02", "OBL-RGT-03", "OBL-RGT-04", "OBL-RGT-05", "OBL-RGT-06", "OBL-RGT-08"], "Sample 15 requests; verify SLA, completeness, response content.", ["Request log", "Responses"], ["5.34"], ["7.3.6", "7.3.9"], ["RS.MA-01"])
ctl("CTL-RGT-03", "D12", "Requester verification", "Verify requester using DF-issued identifiers; nominee verification (death certificate/incapacity proof).", "Preventive", "Manual", "Per request", "Customer Service", ["OBL-RGT-07", "OBL-RGT-06"], "Sample 10 requests for verification evidence.", ["Verification records"], ["5.16", "8.5"], ["7.3.9"], ["PR.AA-02"])
ctl("CTL-RGT-04", "D12", "Access-request data assembly", "Ability to compile summary of data, processing and recipients (DFs & processors) per principal across systems (identity resolution across systems).", "Preventive", "IT-dependent manual", "Per request", "IT / Privacy", ["OBL-RGT-02"], "Run test access request; check completeness vs register.", ["Output sample"], ["5.34"], ["7.3.8", "7.5.4"], ["ID.AM-07"])
ctl("CTL-RGT-05", "D12", "Erasure request workflow with legal-hold check", "Erasure fulfilment across systems and processors after checking retention obligations; partial erasure explained to DP.", "Corrective", "IT-dependent manual", "Per request", "Privacy / IT", ["OBL-RGT-04", "OBL-RET-01"], "Trace 3 erasures end-to-end.", ["Workflow records"], ["8.10"], ["7.3.6", "7.4.5"], ["PR.DS-01"])

# ---------------- D13 Processors / third parties
ctl("CTL-TPM-01", "D13", "Third-party inventory & classification", "Inventory of all third parties receiving PD with role (processor/DF/joint), data, purpose, location, sub-processors, criticality.", "Directive", "Manual", "Semi-annual", "Procurement / Privacy", ["OBL-PRC-01", "OBL-PRC-02", "OBL-SCP-02"], "Reconcile AP vendor master with inventory.", ["Inventory"], ["5.19", "5.20"], ["7.2.6", "7.5.4"], ["GV.SC-04"])
ctl("CTL-TPM-02", "D13", "Privacy due diligence before onboarding", "Risk-tiered questionnaire, certifications (ISO 27001/27701, SOC 2), data location, sub-processors before contract.", "Preventive", "Manual", "Per onboarding", "Procurement / Security", ["OBL-PRC-02"], "Sample 5 recent onboardings.", ["DD records"], ["5.19", "5.21"], ["7.2.6"], ["GV.SC-06"])
ctl("CTL-TPM-03", "D13", "DPDP data processing agreement (DPA)", "Standard DPA: process only on instruction, security (R6), breach notice SLA (e.g. 24h or less), cessation on withdrawal, erasure/return, sub-processor approval, audit rights, cross-border restrictions, cooperation on rights.", "Preventive", "Manual", "Per contract", "Legal", ["OBL-PRC-01", "OBL-PRC-03", "OBL-PRC-04", "OBL-SEC-07", "OBL-RET-02"], "Sample 10 contracts vs DPA checklist.", ["Executed DPAs"], ["5.20"], ["7.2.6", "8.2.1"], ["GV.SC-05"])
ctl("CTL-TPM-04", "D13", "Ongoing vendor monitoring", "Annual reassessment for critical vendors; SOC/ISO report review; right-to-audit exercised risk-based.", "Detective", "Manual", "Annual", "Vendor Risk", ["OBL-PRC-02"], "Inspect last reviews of top 10 vendors.", ["Review files"], ["5.22"], ["7.2.6"], ["GV.SC-07"])
ctl("CTL-TPM-05", "D13", "Data sharing with other Data Fiduciaries", "Sharing with independent DFs (insurers, banks, group cos, partners) has basis, notice disclosure, sharing agreement and accuracy check.", "Preventive", "Manual", "Per arrangement", "Legal / Privacy", ["OBL-DQ-01", "OBL-RGT-02", "OBL-LB-01"], "Sample 3 sharing arrangements.", ["Agreements", "Notices"], ["5.14"], ["7.5.4"], ["GV.SC-05"])

# ---------------- D14 Cross-border
ctl("CTL-XB-01", "D14", "Transfer register & negative-list check", "Register of cross-border transfers (vendor, country, data, purpose, basis, safeguards) checked against notified restricted list and sector localisation.", "Detective", "Manual", "Quarterly + on notification", "Privacy / Legal", ["OBL-XB-01", "OBL-XB-02", "OBL-XB-03"], "Reconcile transfer register with cloud regions/vendor locations.", ["Transfer register"], ["5.14", "5.23"], ["7.5.1", "7.5.2", "7.5.3"], ["GV.SC-04"])
ctl("CTL-XB-02", "D14", "Data residency architecture", "Region pinning and technical controls for data required to stay in India (RBI payments, IRDAI, SEBI, Govt, SDF-specified, CERT-In logs).", "Preventive", "Automated", "Continuous", "IT Architecture", ["OBL-XB-03", "OBL-SDF-07", "LNK-CERT-02"], "Inspect cloud region config & replication.", ["Architecture", "Config"], ["5.23"], ["7.5.1"], ["PR.DS-01"])

# ---------------- D15 SDF
ctl("CTL-SDF-01", "D15", "SDF governance (DPO & auditor)", "Board resolution appointing India-based DPO reporting to board; independent data auditor with independence checks.", "Directive", "Manual", "On notification; annual", "Board / Company Secretary", ["OBL-SDF-01", "OBL-SDF-02"], "Inspect resolutions and independence declarations.", ["Resolutions"], ["5.2", "5.35"], ["6.3.1.1"], ["GV.RR-01"])
ctl("CTL-SDF-02", "D15", "Annual DPIA & audit cycle", "DPIA methodology and annual cycle; audit plan; report of significant observations submitted to Board.", "Detective", "Manual", "Annual", "DPO", ["OBL-SDF-03", "OBL-SDF-04", "OBL-SDF-05"], "Inspect last DPIA/audit and submission.", ["DPIA", "Audit report"], ["5.35"], ["7.2.5"], ["ID.RA-01", "GV.OV-02"])
ctl("CTL-SDF-03", "D15", "Algorithm inventory & risk assessment", "Inventory of algorithms/AI models touching PD (ranking, recommendation, moderation, credit, fraud) with risk assessment of impact on DP rights.", "Detective", "Manual", "Annual + per model change", "Data Science / Risk", ["OBL-SDF-06"], "Sample 3 models for assessments.", ["Model inventory", "Assessments"], ["5.8"], ["7.3.10"], ["ID.RA-04"])

# ---------------- D16 Regulatory
ctl("CTL-REG-01", "D16", "Regulator & Government request handling", "Register and SOP for Board inquiries, Govt info calls (R23), law-enforcement requests, confidentiality directions and response timelines.", "Directive", "Manual", "Per request", "Legal", ["OBL-REG-01", "OBL-REG-02", "OBL-REG-03", "OBL-LB-04"], "Inspect register and sample responses.", ["Request register"], ["5.5", "5.31"], ["7.5.4"], ["GV.OC-03"])
ctl("CTL-REG-02", "D16", "Undertaking & appeal tracker", "Tracker for voluntary undertakings, Board orders, appeal deadlines (60 days).", "Detective", "Manual", "Monthly", "Legal", ["OBL-REG-04", "OBL-REG-05"], "Inspect tracker.", ["Tracker"], ["5.31"], [], ["GV.OC-03"])
ctl("CTL-REG-03", "D16", "CERT-In PoC & reporting channel", "Designated CERT-In PoC and tested reporting channel.", "Directive", "Manual", "Annual", "CISO", ["LNK-CERT-04", "LNK-CERT-01"], "Inspect PoC filing.", ["Filing"], ["5.5"], [], ["RS.CO-02"])

# ---------------- D17 State/Research
ctl("CTL-STA-01", "D17", "Second Schedule compliance for State schemes", "Scheme-wise note on lawful basis, necessity, accuracy, retention, security, intimation and accountability.", "Directive", "Manual", "Per scheme", "Department Head / Nodal Officer", ["OBL-STA-01"], "Inspect 2 schemes.", ["Scheme notes"], ["5.31"], ["7.2.1"], ["GV.OC-03"])
ctl("CTL-RES-01", "D17", "Research & statistics safeguards", "Protocol, ethics approval where applicable, de-identification, no DP-specific decisions.", "Preventive", "Manual", "Per project", "Research Lead", ["OBL-RES-01"], "Inspect 2 projects.", ["Protocols"], ["8.11"], ["7.4.5"], ["PR.DS-01"])

# ---------------- D18 Consent Manager operator
ctl("CTL-CMO-01", "D18", "Consent Manager registration & governance", "Registration file, net worth monitoring, fit & proper checks, COI policy, disclosures, change-of-control approvals.", "Directive", "Manual", "Annual", "Company Secretary", ["OBL-CMO-01", "OBL-CMO-05", "OBL-CMO-06"], "Inspect registration & disclosures.", ["Registration", "Disclosures"], ["5.31"], [], ["GV.OC-03"])
ctl("CTL-CMO-02", "D18", "Consent Manager platform controls", "Zero-knowledge data handling, interoperable APIs, 7-year records with DP machine-readable access, no sub-contracting, ISMS.", "Preventive", "Automated", "Continuous", "CTO", ["OBL-CMO-02", "OBL-CMO-03", "OBL-CMO-04"], "Architecture review; record retention test.", ["Architecture", "Retention config"], ["8.24", "5.33"], ["7.2.8"], ["PR.DS-01"])
