#!/usr/bin/env bash
# Builds the application's .env (repo root) from the service secrets in infra/.env.
# Generates the app database role password once. Prints no secrets.
set -euo pipefail
cd "$(dirname "$0")"
umask 077

if ! grep -q '^APP_DB_PASSWORD=' .env; then
  echo "APP_DB_PASSWORD=$(openssl rand -hex 24)" >> .env
fi
set -a
# shellcheck disable=SC1091
. ./.env
set +a

HOST_IP="${DUATF_HOST_IP:-$(hostname -I | awk '{print $1}')}"
PG="127.0.0.1:${POSTGRES_PORT}"

cat > ../.env <<EOF
# Generated by infra/make-app-env.sh from infra/.env. Do not commit.
NODE_ENV=development
HOST=0.0.0.0
WEB_PORT=53000
API_PORT=54000
PUBLIC_WEB_URL=http://${HOST_IP}:53000
PUBLIC_API_URL=http://${HOST_IP}:54000
DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${PG}/${POSTGRES_DB}
APP_DATABASE_URL=postgres://duatf_app:${APP_DB_PASSWORD}@${PG}/${POSTGRES_DB}
TEST_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${PG}/duatf_test
TEST_APP_DATABASE_URL=postgres://duatf_app:${APP_DB_PASSWORD}@${PG}/duatf_test
REDIS_URL=redis://:${REDIS_PASSWORD}@127.0.0.1:${REDIS_PORT}/0
S3_ENDPOINT=http://127.0.0.1:${MINIO_API_PORT}
S3_ACCESS_KEY=${MINIO_ROOT_USER}
S3_SECRET_KEY=${MINIO_ROOT_PASSWORD}
S3_BUCKET_EVIDENCE=duatf-evidence
S3_BUCKET_REPORTS=duatf-reports
SMTP_HOST=127.0.0.1
SMTP_PORT=${MAILPIT_SMTP_PORT}
AUTH_MODE=dev
SEED_VAULT_PATH=seed/DPDP-DUATF-Vault
EOF
echo "Wrote $(cd .. && pwd)/.env"
