#!/usr/bin/env bash
# Builds the application's .env (repo root) from the service secrets in infra/.env.
# Generates the app database password and the Keycloak client secrets once. Prints no secrets.
set -euo pipefail
cd "$(dirname "$0")"
umask 077

# The LAN address: the source address of the default route (not a Docker bridge).
lan_ip() {
  ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i = 1; i < NF; i++) if ($i == "src") { print $(i + 1); exit }}'
}
HOST_IP="${DUATF_HOST_IP:-$(lan_ip)}"
if [ -z "${HOST_IP}" ]; then
  echo "Could not work out the LAN address; set DUATF_HOST_IP." >&2
  exit 1
fi

ensure_secret() {
  grep -q "^$1=" .env || echo "$1=$(openssl rand -hex 24)" >> .env
}
ensure_secret APP_DB_PASSWORD
ensure_secret KC_WEB_CLIENT_SECRET
ensure_secret KC_ADMIN_CLIENT_SECRET
if ! grep -q '^KEYCLOAK_PUBLIC_URL=' .env; then
  echo "KEYCLOAK_PUBLIC_URL=http://${HOST_IP}:$(grep '^KEYCLOAK_PORT=' .env | cut -d= -f2)" >> .env
fi

set -a
# shellcheck disable=SC1091
. ./.env
set +a

PG="127.0.0.1:${POSTGRES_PORT}"
WEB_URL="http://${HOST_IP}:53000"

cat > ../.env <<ENV
# Generated by infra/make-app-env.sh from infra/.env. Do not commit.
NODE_ENV=development
HOST=0.0.0.0
WEB_PORT=53000
API_PORT=54000
PUBLIC_WEB_URL=${WEB_URL}
PUBLIC_API_URL=http://${HOST_IP}:54000
DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${PG}/${POSTGRES_DB}
APP_DATABASE_URL=postgres://duatf_app:${APP_DB_PASSWORD}@${PG}/${POSTGRES_DB}
TEST_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${PG}/duatf_test
TEST_APP_DATABASE_URL=postgres://duatf_app:${APP_DB_PASSWORD}@${PG}/duatf_test
REDIS_URL=redis://:${REDIS_PASSWORD}@127.0.0.1:${REDIS_PORT}/0
S3_ENDPOINT=http://127.0.0.1:${MINIO_API_PORT}
S3_PUBLIC_ENDPOINT=http://${HOST_IP}:${MINIO_API_PORT}
S3_ACCESS_KEY=${MINIO_ROOT_USER}
S3_SECRET_KEY=${MINIO_ROOT_PASSWORD}
S3_BUCKET_EVIDENCE=duatf-evidence
S3_BUCKET_REPORTS=duatf-reports
SMTP_HOST=127.0.0.1
SMTP_PORT=${MAILPIT_SMTP_PORT}
PUBLIC_KEYCLOAK_URL=${KEYCLOAK_PUBLIC_URL}
KEYCLOAK_URL=${KEYCLOAK_PUBLIC_URL}
KEYCLOAK_REALM=duatf
KEYCLOAK_MASTER_USER=${KEYCLOAK_ADMIN}
KEYCLOAK_MASTER_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
KEYCLOAK_ADMIN_CLIENT_ID=duatf-admin
KEYCLOAK_ADMIN_CLIENT_SECRET=${KC_ADMIN_CLIENT_SECRET}
OIDC_ISSUER=${KEYCLOAK_PUBLIC_URL}/realms/duatf
OIDC_CLIENT_ID=duatf-web
OIDC_CLIENT_SECRET=${KC_WEB_CLIENT_SECRET}
SESSION_TTL_HOURS=12
SEED_VAULT_PATH=seed/DPDP-DUATF-Vault
ENV
echo "Wrote $(cd .. && pwd)/.env"
