import {
  LEVEL_INFO,
  LEVELS,
  PERSONAL_DATA_CATEGORIES,
} from '@duatf/feature-compliance-api/personal-data'

// Knowledge-base entries drafted with AI assistance (phase C17.4) to fill gaps in the reference
// sections. Every entry lands in the open draft release labelled "AI draft, awaiting legal
// review"; nothing here is published until a firm administrator reviews and publishes the draft.
// Legal statements are kept to what the obligations already in the knowledge base say, and cite
// them, so a reviewer can check each claim against an existing entry and the official text.

/** Input for one entry, in the shape the knowledge-base editor accepts. */
export type EntryInput = Record<string, string | string[]>

export const BASES: EntryInput[] = [
  {
    code: 'ex17_4',
    name: 'Exempt (partial) - State: erasure and correction limits',
    reference: 's.17(4)',
    explanation: [
      '> s.17(4): for processing by the State or a State instrumentality, s.8(7) (erasure when the purpose ends) and s.12(3) (erasure on request) do not apply. Where the processing does not include making a decision that affects the Data Principal, s.12(2) (correction, completion and updating) does not apply either.',
      '',
      'Every other obligation still applies, including security safeguards (s.8(5)) and breach intimation (s.8(6)).',
    ].join('\n'),
  },
  {
    code: 'ex17_5',
    name: 'Exempt - notified Data Fiduciary or class, for a notified period',
    reference: 's.17(5)',
    explanation: [
      '> s.17(5): within five years of commencement, the Central Government may by notification declare that any provision of the Act does not apply to a Data Fiduciary or class of Data Fiduciaries for the period the notification specifies.',
      '',
      'Rely on it only with the notification in hand, and record which provisions it switches off and until when (see [OBL-SCP-03](ref:obligation/OBL-SCP-03)).',
    ].join('\n'),
  },
]

const GAP_DATA_ELEMENTS: EntryInput[] = [
  {
    code: 'DE-FAM-003',
    title: 'Parent or guardian identity and age proof (verifiable consent)',
    category: 'family',
    personalData: 'yes',
    contextTags: ['children', 'gov_id'],
    note: 'Collected to check that the person giving consent for a child is an identifiable adult (s.9(1), Rule 10). Keep only what the check needs.',
  },
  {
    code: 'DE-FAM-004',
    title: 'Lawful guardian appointment details (person with disability)',
    category: 'family',
    personalData: 'yes',
    contextTags: [],
    note: 'Order of a court, designated authority or local level committee, used to verify the guardian (Rule 11).',
  },
  {
    code: 'DE-ID-010',
    title: 'Age or age-assurance result',
    category: 'identity',
    personalData: 'yes',
    contextTags: ['children'],
    note: 'The outcome of an age check, such as a declared age or a verified token. Store the result rather than the proof where possible.',
  },
  {
    code: 'DE-GOV-012',
    title: 'UDID (disability) card number',
    category: 'gov_id',
    personalData: 'yes',
    contextTags: ['gov_id', 'health'],
  },
  {
    code: 'DE-GOV-013',
    title: 'Ration card number',
    category: 'gov_id',
    personalData: 'yes',
    contextTags: ['gov_id'],
  },
  {
    code: 'DE-FIN-011',
    title: 'Cancelled cheque or bank statement copy',
    category: 'financial',
    personalData: 'yes',
    contextTags: ['financial'],
    note: 'Often collected for refunds, payouts and vendor onboarding; holds more than the account number.',
  },
  {
    code: 'DE-HLT-012',
    title: 'Blood group',
    category: 'health',
    personalData: 'yes',
    contextTags: ['health'],
  },
  {
    code: 'DE-HLT-013',
    title: 'Insurance claim and TPA documents',
    category: 'health',
    personalData: 'yes',
    contextTags: ['health', 'financial'],
  },
  {
    code: 'DE-HLT-014',
    title: 'Blood, organ or tissue donor records',
    category: 'health',
    personalData: 'yes',
    contextTags: ['health'],
  },
  {
    code: 'DE-EMP-008',
    title: 'Workplace monitoring data (screen, email or keystroke monitoring)',
    category: 'behavioural',
    personalData: 'yes',
    contextTags: [],
    note: 'Without consent only for employment purposes or safeguarding the employer (s.7(i), see OBL-LB-06).',
  },
  {
    code: 'DE-EDU-004',
    title: 'Online proctoring recordings (face, screen, audio)',
    category: 'images_av',
    personalData: 'yes',
    contextTags: ['biometric'],
    note: 'Usually captured by a proctoring vendor acting as a processor.',
  },
  {
    code: 'DE-AV-005',
    title: 'Body-worn camera or dashcam footage',
    category: 'images_av',
    personalData: 'yes',
    contextTags: ['cctv'],
  },
  {
    code: 'DE-COM-004',
    title: 'Consent and notice records (consent artefacts)',
    newCategory: 'consent_record',
    personalData: 'yes',
    contextTags: [],
    note: 'Who consented to which notice version, when and how, and any withdrawal. The Data Fiduciary must be able to prove notice and consent (s.6(10)).',
  },
  {
    code: 'DE-DEV-009',
    title: 'Security and access logs (sign-ins, admin actions)',
    category: 'device_online',
    personalData: 'yes',
    contextTags: [],
    note: 'Kept at least one year under Rule 6(1)(e) and for a rolling 180 days in India under the CERT-In Directions.',
  },
]

const element = (
  code: string,
  title: string,
  category: string,
  contextTags: string[],
  note: string,
  personalData: 'yes' | 'no' = 'yes',
): EntryInput => ({ code, title, category, personalData, contextTags, note })

/**
 * Data elements for department data maps (phase C20). Drawn from ComplyX's personal data
 * classification table and common catalogues of personal data (SPDI Rules 2011 r.3, UIDAI's
 * list of supporting documents, RBI card and KYC directions, GDPR Art. 9 and 10 for the
 * sensitive kinds). The DPDP Act itself has no sensitive categories; the notes say why an
 * element needs care.
 */
const DATA_MAP_ELEMENTS: EntryInput[] = [
  element(
    'DE-ID-011',
    'Username or account handle',
    'identity',
    [],
    'Personal data when it can be linked to the person, as account names usually can.',
  ),
  element(
    'DE-ID-012',
    'Student roll or admission number',
    'identity',
    ['children'],
    'Identifies a student; for under-18s the children duties of s.9 apply to the processing.',
  ),
  element(
    'DE-ID-013',
    'Visitor register entry (name, purpose, time in and out)',
    'identity',
    [],
    'Paper or electronic visitor logs. Give visitors a notice and keep the register only as long as the security purpose needs.',
  ),
  element(
    'DE-ID-014',
    'Membership or loyalty number',
    'identity',
    [],
    'An internal identifier that links to the member’s profile and history.',
  ),
  element(
    'DE-CON-006',
    'Work email and phone of a business contact',
    'contact',
    [],
    'The contact details of a vendor’s or client’s employee are that person’s personal data, even when used only for business.',
  ),
  element('DE-CON-007', 'Alternate or landline number', 'contact', [], ''),
  element(
    'DE-DEM-001',
    'Preferred language',
    'demographic',
    [],
    'Useful for giving notices in the language the person chose (s.5(3)).',
  ),
  element(
    'DE-DEM-002',
    'Occupation (outside employment records)',
    'demographic',
    [],
    'For example the occupation recorded for KYC or insurance.',
  ),
  element(
    'DE-DEM-003',
    'Residential status (resident, NRI, foreign national)',
    'demographic',
    [],
    'Often collected for KYC and tax.',
  ),
  element(
    'DE-FAM-005',
    'Family members’ details (occupation, contact)',
    'family',
    [],
    'Personal data of the family members themselves; collect only what the purpose needs.',
  ),
  element(
    'DE-GOV-014',
    'Birth certificate details',
    'gov_id',
    ['gov_id'],
    'Often the age proof for a child; see the verifiable consent duties for children (s.9(1)).',
  ),
  element(
    'DE-GOV-015',
    'Offline Aadhaar e-KYC XML or DigiLocker documents',
    'gov_id',
    ['gov_id'],
    'Handle like the Aadhaar number (DE-GOV-001): store only what the purpose needs and mask the number where it is shown.',
  ),
  element(
    'DE-GOV-016',
    'NREGA job card or NPR letter',
    'gov_id',
    ['gov_id'],
    'Officially valid documents for KYC.',
  ),
  element(
    'DE-GOV-017',
    'Visa, OCI or FRRO registration details',
    'gov_id',
    ['gov_id'],
    'Held for foreign employees, students or guests.',
  ),
  element(
    'DE-GOV-018',
    'Domicile or income certificate',
    'gov_id',
    ['gov_id'],
    'Often collected for admissions, scholarships or schemes.',
  ),
  element(
    'DE-FIN-012',
    'Card security data (CVV, PIN)',
    'payment_card',
    ['financial'],
    'Must not be stored after the payment is authorised (PCI DSS). Under RBI’s card-on-file rules, merchants keep tokens, not card data.',
  ),
  element(
    'DE-FIN-013',
    'Card token or tokenised card reference',
    'payment_card',
    ['financial'],
    '',
  ),
  element('DE-FIN-014', 'Demat or trading account details', 'financial', ['financial'], ''),
  element('DE-FIN-015', 'Wallet or prepaid instrument ID', 'financial', ['financial'], ''),
  element(
    'DE-FIN-016',
    'Auto-debit mandate details (eNACH, UPI AutoPay)',
    'financial',
    ['financial'],
    '',
  ),
  element(
    'DE-FIN-017',
    'Assets, liabilities or net-worth declarations',
    'financial',
    ['financial'],
    'For example declarations under a code of conduct or for lending.',
  ),
  element(
    'DE-FIN-018',
    'Expense and reimbursement claims',
    'financial',
    ['financial'],
    'Bills and claims can reveal travel, health or family details; limit who sees them.',
  ),
  element(
    'DE-EMP-009',
    'CV and job application',
    'employment_history',
    [],
    'Keep unsuccessful applicants’ data only as long as the recruitment purpose needs (s.8(7)).',
  ),
  element('DE-EMP-010', 'Interview notes and evaluations', 'performance', [], ''),
  element('DE-EMP-011', 'Offer letter, appointment and contract terms', 'employment', [], ''),
  element(
    'DE-EMP-012',
    'Reference check details',
    'background_check',
    [],
    'Collected from third parties; tell the candidate before checking.',
  ),
  element(
    'DE-EMP-013',
    'Exit details (resignation reason, full and final settlement)',
    'employment',
    [],
    '',
  ),
  element(
    'DE-EMP-014',
    'Professional registration or licence number',
    'professional',
    [],
    'For example a medical council, ICAI or Bar Council registration.',
  ),
  element('DE-EMP-015', 'Shift rosters and overtime', 'attendance', [], ''),
  element('DE-EMP-016', 'Company assets issued (laptop, phone, access card)', 'employment', [], ''),
  element('DE-EDU-005', 'Training records and certifications', 'education', [], ''),
  element('DE-EDU-006', 'Student attendance', 'education', ['children'], ''),
  element(
    'DE-EDU-007',
    'Student disciplinary or behaviour records',
    'education',
    ['children'],
    'Behaviour records of children need particular care; behavioural monitoring of children is prohibited unless exempted (s.9(3)).',
  ),
  element(
    'DE-EDU-008',
    'Scholarship or fee concession details',
    'education',
    ['children', 'financial'],
    'Reveal family income or category; restrict access.',
  ),
  element('DE-HLT-015', 'Height, weight or BMI', 'health', ['health'], ''),
  element(
    'DE-HLT-016',
    'Family medical history',
    'health',
    ['health'],
    'Health data about relatives as well as the person.',
  ),
  element(
    'DE-HLT-017',
    'Allergies and dietary restrictions',
    'health',
    ['health'],
    'Collected by cafeterias, events and travel desks as well as clinics.',
  ),
  element(
    'DE-HLT-018',
    'Pre-employment or periodic medical examination report',
    'health',
    ['health'],
    '',
  ),
  element('DE-HLT-019', 'Medical certificate for sick leave', 'health', ['health'], ''),
  element('DE-HLT-020', 'Substance use or addiction treatment records', 'health', ['health'], ''),
  element('DE-HLT-021', 'Paternity or ancestry DNA test result', 'genetic', ['health'], ''),
  element('DE-BIO-005', 'Palm or finger-vein pattern', 'biometric', ['biometric'], ''),
  element(
    'DE-BIO-006',
    'Behavioural biometrics (keystroke, gait, signature dynamics)',
    'biometric',
    ['biometric'],
    '',
  ),
  element(
    'DE-BIO-007',
    'Selfie or liveness check for face matching',
    'biometric',
    ['biometric'],
    'Used in e-KYC and account recovery; keep the match result rather than the image where possible.',
  ),
  element('DE-DEV-010', 'MAC address or IMEI', 'device_online', [], ''),
  element(
    'DE-DEV-011',
    'Browser or device fingerprint',
    'device_online',
    [],
    'Built from the user agent, screen, fonts and similar signals; identifies a device without a cookie.',
  ),
  element('DE-DEV-012', 'Push notification token', 'device_online', [], ''),
  element('DE-DEV-013', 'Session identifiers', 'device_online', [], ''),
  element(
    'DE-AUT-001',
    'One-time passwords, MFA secrets and recovery codes',
    'credential',
    [],
    'Store secrets hashed or in a vault; never in logs.',
  ),
  element('DE-AUT-002', 'Security questions and answers', 'credential', [], ''),
  element('DE-AUT-003', 'Access tokens and API keys tied to a person', 'credential', [], ''),
  element(
    'DE-AUT-004',
    'Access card or badge ID',
    'credential',
    [],
    'Links physical access logs to the person.',
  ),
  element('DE-BEH-005', 'Search history', 'behavioural', [], ''),
  element('DE-BEH-006', 'Survey and feedback responses', 'behavioural', [], ''),
  element('DE-BEH-007', 'Loyalty points and rewards activity', 'behavioural', [], ''),
  element(
    'DE-BEH-008',
    'Social media profile and activity',
    'behavioural',
    [],
    'Publicly available data made public by the person is outside the Act (s.3(c)(ii)); data collected through the organisation’s own pages usually is not.',
  ),
  element('DE-BEH-009', 'Lead source and campaign responses', 'behavioural', [], ''),
  element('DE-LOC-004', 'Location history and check-ins', 'location', ['location'], ''),
  element('DE-LOC-005', 'Wi-Fi or Bluetooth beacon presence', 'location', ['location'], ''),
  element('DE-COM-005', 'SMS, WhatsApp and other message content', 'communication_content', [], ''),
  element(
    'DE-COM-006',
    'Chatbot and support chat transcripts',
    'communication_content',
    [],
    'Often sent to an AI provider; record it as a recipient.',
  ),
  element(
    'DE-COM-007',
    'Email and messaging metadata (sender, recipient, time)',
    'communication_metadata',
    [],
    '',
  ),
  element('DE-COM-008', 'Support ticket history', 'communication_content', [], ''),
  element(
    'DE-COM-009',
    'Marketing opt-in and opt-out choices',
    'consent_record',
    [],
    'Keep proof of the choice and act on a withdrawal across every channel (s.6(4)).',
  ),
  element('DE-AV-006', 'Visitor photograph', 'images_av', [], ''),
  element(
    'DE-AV-007',
    'Screen recordings or screenshots',
    'images_av',
    [],
    'For example from support sessions or monitoring tools.',
  ),
  element('DE-SEN-006', 'Police verification certificate', 'sensitive_allegations', [], ''),
  element(
    'DE-SEN-007',
    'Litigation, dispute or legal claim details',
    'sensitive_allegations',
    [],
    'Processing needed to enforce a legal right or claim is exempt from parts of the Act (s.17(1)(a)).',
  ),
  element(
    'DE-SEN-008',
    'Caste or community certificate',
    'sensitive_attributes',
    ['gov_id'],
    'Reveals caste; collect only where a law or scheme requires it.',
  ),
  element('DE-SEN-009', 'Ethnicity or tribe', 'sensitive_attributes', [], ''),
  element('DE-SEN-010', 'Trade union membership', 'sensitive_attributes', [], ''),
  element('DE-PRP-002', 'Rental or lease agreement details', 'property', [], ''),
  element(
    'DE-BUS-001',
    'Company PAN or TAN',
    'business',
    [],
    'Identifies a company, not a person. A sole proprietor’s PAN is the person’s own (DE-GOV-003).',
    'no',
  ),
  element(
    'DE-BUS-002',
    'CIN or LLPIN',
    'business',
    [],
    'Public company and LLP identifiers; not personal data.',
    'no',
  ),
  element(
    'DE-BUS-003',
    'Company GSTIN',
    'business',
    [],
    'Public on the GST portal. A proprietor’s GSTIN is personal data (DE-GOV-010).',
    'no',
  ),
  element(
    'DE-BUS-004',
    'Udyam (MSME) registration number',
    'business',
    [],
    'Personal data when the enterprise is a proprietorship.',
    'no',
  ),
  element(
    'DE-BUS-005',
    'Company bank account details',
    'business',
    [],
    'A company’s account is not personal data; an individual vendor’s is (DE-FIN-001).',
    'no',
  ),
]

/**
 * Data elements of schools and other educational institutions (phase C20.10), where most data
 * principals are children: a parent's or guardian's verifiable consent is needed where consent is
 * the ground (s.9(1)), and tracking, behavioural monitoring and targeted advertising are barred
 * except as the Fourth Schedule allows (s.9(3), Rule 12).
 */
const SCHOOL_ELEMENTS: EntryInput[] = [
  element(
    'DE-EDU-009',
    'Admission application and entrance test results',
    'education',
    ['children'],
    'Keep applicants not admitted only as long as the admission purpose needs (s.8(7)).',
  ),
  element('DE-EDU-010', 'Report cards and progress reports', 'education', ['children'], ''),
  element(
    'DE-EDU-011',
    'Transfer, migration or school leaving certificate',
    'education',
    ['children'],
    '',
  ),
  element('DE-EDU-012', 'Previous school records', 'education', ['children'], ''),
  element(
    'DE-EDU-013',
    'Answer scripts and examination records',
    'assessment_results',
    ['children'],
    'Boards and the school may set how long these are kept.',
  ),
  element(
    'DE-EDU-014',
    'Special educational needs or learning support plan',
    'education',
    ['children', 'health'],
    'Reveals a disability or learning difficulty; share only with the staff who support the student.',
  ),
  element('DE-EDU-015', 'Library borrowing records', 'education', ['children'], ''),
  element(
    'DE-EDU-016',
    'Sports, co-curricular and achievement records',
    'education',
    ['children'],
    '',
  ),
  element(
    'DE-EDU-017',
    'Teacher remarks and student observation notes',
    'education',
    ['children'],
    '',
  ),
  element(
    'DE-EDU-018',
    'Hostel or boarding details (room, leave, visitors)',
    'education',
    ['children'],
    '',
  ),
  element(
    'DE-EDU-019',
    'Learning platform activity and progress data',
    'behavioural',
    ['children', 'ai'],
    'Profiling children for anything beyond the educational activity risks the s.9(3) bar on behavioural monitoring.',
  ),
  element(
    'DE-FAM-006',
    'Parent or guardian occupation and income',
    'family',
    ['financial'],
    'Often collected for fee concessions or quota admissions; collect only where it is needed.',
  ),
  element('DE-FAM-007', 'Authorised pick-up persons and their photos', 'family', ['children'], ''),
  element('DE-FAM-008', 'Sibling details', 'family', ['children'], ''),
  element('DE-ID-015', 'Student ID card details', 'identity', ['children'], ''),
  element(
    'DE-GOV-019',
    'UDISE+ Permanent Education Number (PEN)',
    'gov_id',
    ['gov_id', 'children'],
    'Issued through the government school data system; disclose only as that system requires.',
  ),
  element(
    'DE-GOV-020',
    'RTE admission category proof (EWS or disadvantaged group)',
    'gov_id',
    ['gov_id', 'children', 'financial'],
    'Reveals family income or social group; restrict access to admissions and accounts staff.',
  ),
  element(
    'DE-LOC-006',
    'School bus route, stop and pick-up times',
    'location',
    ['location', 'children'],
    '',
  ),
  element(
    'DE-LOC-007',
    'School transport GPS tracking',
    'location',
    ['location', 'children'],
    "Location tracking of children while they are transported is one of the Fourth Schedule purposes (Rule 12); don't use it for anything else.",
  ),
  element(
    'DE-HLT-022',
    'Medical room visits and first-aid records',
    'health',
    ['health', 'children'],
    '',
  ),
  element(
    'DE-HLT-023',
    'Student health check-up and growth records',
    'health',
    ['health', 'children'],
    '',
  ),
  element(
    'DE-SEN-011',
    'Child protection or POCSO incident records',
    'sensitive_allegations',
    ['children'],
    'Keep with the designated child protection staff; mandatory reporting under POCSO applies alongside DPDP.',
  ),
  element(
    'DE-AV-008',
    'Classroom and campus CCTV footage',
    'images_av',
    ['cctv', 'children'],
    'Monitoring of students is allowed for educational activities or their safety under the Fourth Schedule; set a short retention.',
  ),
  element(
    'DE-AV-009',
    'Student photos and videos for events, website or social media',
    'images_av',
    ['children'],
    "Publish only with the parent's consent, and take down when it is withdrawn.",
  ),
  element('DE-AV-010', 'Online class recordings', 'images_av', ['children'], ''),
  element('DE-FIN-019', 'School fee payment records', 'financial', ['financial', 'children'], ''),
  element(
    'DE-AUT-005',
    'Student login credentials for school apps and platforms',
    'credential',
    ['children'],
    '',
  ),
  element('DE-EMP-017', 'Teacher eligibility certificate (TET or CTET)', 'professional', [], ''),
  element(
    'DE-EMP-018',
    'Driver and attendant verification (licence, police verification, medical fitness)',
    'background_check',
    ['gov_id'],
    'Kept for the safety of children in school transport.',
  ),
  element(
    'DE-COM-010',
    'Parent-teacher communications (diary, app messages)',
    'communication_content',
    ['children'],
    '',
  ),
]

export const DATA_ELEMENTS: EntryInput[] = [
  ...GAP_DATA_ELEMENTS,
  ...DATA_MAP_ELEMENTS,
  ...SCHOOL_ELEMENTS,
]

/** The data map's categories and levels, as reference vocabularies in the knowledge base. */
const DATA_MAP_VOCABULARIES: EntryInput[] = [
  {
    code: 'personal-data-categories',
    title: 'Personal data categories',
    intro:
      'The categories DUATF groups data elements into on department data maps and in the RoPA, with the sensitivity level each defaults to. A firm’s classification, not a legal one: the DPDP Act has no special categories, but the SPDI Rules 2011 treat passwords, financial, health, sexual orientation and biometric data as sensitive until 13 May 2027.',
    columns: 'Category\nWhat it covers\nExamples\nDefault level\nData element categories',
    terms: PERSONAL_DATA_CATEGORIES.map((category) =>
      [
        category.title,
        category.description,
        category.examples,
        `${category.level} ${LEVEL_INFO[category.level].label}`,
        category.kbCategories.join(', '),
      ].join(' | '),
    ).join('\n'),
  },
  {
    code: 'data-classification-levels',
    title: 'Data classification levels',
    intro:
      'How sensitive a data element is, and the handling it needs. An element tagged financial, health, biometric or government ID is Restricted whatever its category.',
    columns: 'Level\nMeaning\nBaseline handling',
    terms: LEVELS.map((level) =>
      [
        `${level} ${LEVEL_INFO[level].label}`,
        LEVEL_INFO[level].meaning,
        LEVEL_INFO[level].handling,
      ].join(' | '),
    ).join('\n'),
  },
]

/** Restores flag names whose underscores were lost when the vault was imported. */
export const ENGINE_FLAG_FIXES: Record<string, string> = {
  decisionordisclosure: 'decision_or_disclosure',
  consentmanagerused: 'consent_manager_used',
}

export const VOCABULARIES: EntryInput[] = [
  {
    code: 'notice-languages',
    title: 'Notice languages',
    intro:
      'A notice and a consent request must be available in English or any language in the Eighth Schedule to the Constitution (s.5(3), s.6(3)).',
    columns: 'Language\nBasis',
    terms: [
      'English | s.5(3)',
      ...[
        'Assamese',
        'Bengali',
        'Bodo',
        'Dogri',
        'Gujarati',
        'Hindi',
        'Kannada',
        'Kashmiri',
        'Konkani',
        'Maithili',
        'Malayalam',
        'Manipuri',
        'Marathi',
        'Nepali',
        'Odia',
        'Punjabi',
        'Sanskrit',
        'Santali',
        'Sindhi',
        'Tamil',
        'Telugu',
        'Urdu',
      ].map((language) => `${language} | Eighth Schedule`),
    ].join('\n'),
  },
  {
    code: 'data-principal-rights',
    title: 'Data Principal rights',
    intro: 'What a person can ask a Data Fiduciary for, and where it comes from.',
    columns: 'Right\nWhat the person can ask for\nReference',
    terms: [
      'Withdraw consent | Withdraw consent at any time, as easily as it was given | s.6(4)',
      'Access | A summary of their personal data and its processing, and who else it was shared with | s.11, R14',
      'Correction, completion and updating | Correct inaccurate or misleading data, complete or update it | s.12(1), s.12(2), R14',
      'Erasure | Erase data no longer needed, unless a law requires keeping it | s.12(3), R14',
      'Grievance redressal | A readily available way to complain, answered within the published period | s.8(10), s.13, R14(3)',
      'Nomination | Nominate someone to exercise these rights on death or incapacity | s.14, R14(4)',
      'Complaint to the Board | Complain to the Data Protection Board after the grievance route is exhausted | s.13(3)',
    ].join('\n'),
  },
  {
    code: 'retention-triggers',
    title: 'Retention triggers',
    intro: 'Events that end, extend or set the retention of personal data.',
    columns: 'Trigger\nWhat happens\nReference',
    terms: [
      'Specified purpose no longer served | Erase, unless a law requires keeping it | s.8(7)(a)',
      'Consent withdrawn | Stop processing within a reasonable time and erase, including at processors | s.6(6), s.8(7)',
      'Erasure request | Erase, unless needed for the purpose or required by law | s.12(3)',
      'Third Schedule inactivity | Erase after three years without the person approaching, after 48 hours notice | s.8(8), R8, Third Schedule',
      'Retention set by another law | Keep for the period that law sets, then erase | s.8(7)',
      'Investigation minimum | Keep data, traffic data and logs at least one year for Seventh Schedule purposes | R8(3)',
    ].join('\n'),
  },
  {
    code: 'consent-states',
    title: 'Consent states',
    intro: 'The states a consent record moves through, for consent logs and consent managers.',
    columns: 'State\nMeaning',
    terms: [
      'Requested | Notice shown and consent asked; no answer yet',
      'Given | A clear affirmative action recorded against a notice version',
      'Refused | The person declined; nothing is processed on consent for that purpose',
      'Withdrawn | Consent withdrawn; processing stops within a reasonable time',
      'Superseded | A new notice version replaced the one consented to',
      'Expired | The purpose ended or the agreed period ran out',
    ].join('\n'),
  },
  {
    code: 'verifiable-consent-methods',
    title: 'Verifiable consent methods (children)',
    intro:
      'Ways to check that the person consenting for a child is an identifiable adult (s.9(1), Rule 10). Check the current text of Rule 10 before relying on this list.',
    columns: 'Method\nWhen it fits\nReference',
    terms: [
      'Reliable identity and age details already held | The parent is already known to the Data Fiduciary as an adult | R10(1)(a)',
      'Details or a virtual token from an authorised entity | Identity and age details, or a token mapped to them, issued by an entity entrusted by law or the Government (for example through DigiLocker) and provided by the parent | R10(1)(b)',
    ].join('\n'),
  },
  ...DATA_MAP_VOCABULARIES,
]

type ProcessInput = EntryInput & { typicalLawfulBasis: string[]; flags: string[] }

/** Obligations are not listed here: the editor's suggestion from bases and flags fills them. */
export const PROCESSES: ProcessInput[] = [
  {
    code: 'HTA-04',
    title: 'Travel agency and OTA bookings',
    sectorCode: 'HTA',
    department: 'Bookings',
    activities: [
      'Flight, hotel and holiday bookings',
      'Visa and passport processing',
      'Forex and travel insurance',
      'Changes, cancellations and refunds',
    ].join('\n'),
    dataPrincipals: 'Traveller\nCo-traveller (incl. children)\nCorporate traveller',
    dataCategories: ['identity', 'contact', 'gov_id', 'travel', 'payment_card', 'financial'],
    typicalSystems: 'Booking engine\nGDS\nCRM',
    typicalThirdParties:
      'Airlines and hotels\nGDS provider\nVisa facilitation centres\nForex and insurance partners\nPayment gateway',
    typicalLawfulBasis: ['consent', 's7a'],
    flags: ['processor', 'children', 'cross_border', 'online_presence', 'marketing'],
    contextTags: ['gov_id', 'financial', 'location'],
    assessorNote:
      'Passport and visa copies often sit in email and messaging apps; confirm where they are kept and for how long.',
  },
  {
    code: 'HTA-05',
    title: 'Face-based check-in and boarding',
    sectorCode: 'HTA',
    department: 'Airport Operations',
    activities: [
      'Enrolment of face with ID and boarding pass',
      'Face matching at entry, security and boarding',
      'Deletion after departure',
    ].join('\n'),
    dataPrincipals: 'Passenger',
    dataCategories: ['identity', 'biometric', 'travel', 'gov_id'],
    typicalSystems: 'Face recognition gates\nPassenger app\nAirport operational systems',
    typicalThirdParties: 'Platform operator\nAirport operator\nAirline',
    typicalLawfulBasis: ['consent'],
    flags: ['processor', 'online_presence'],
    contextTags: ['biometric', 'gov_id'],
    assessorNote:
      'Confirm who is the Data Fiduciary at each step (airport, platform operator, airline) and the deletion timeline in the scheme policy in force.',
  },
  {
    code: 'LOG-04',
    title: 'Parcel pickup, delivery and proof of delivery',
    sectorCode: 'LOG',
    department: 'Delivery',
    activities: [
      'Pickup booking',
      'Address and phone verification',
      'Live tracking and delivery OTP',
      'Proof of delivery photo or signature',
      'Returns and cash on delivery',
    ].join('\n'),
    dataPrincipals: 'Sender\nRecipient\nDelivery partner',
    dataCategories: ['identity', 'contact', 'location', 'images_av', 'signature', 'transaction'],
    typicalSystems: 'Courier app\nRoute planning\nHandheld devices',
    typicalThirdParties: 'E-commerce merchant\nPayment collection partner\nCloud',
    typicalLawfulBasis: ['consent', 's7a'],
    flags: ['processor', 'online_presence'],
    contextTags: ['location'],
  },
  {
    code: 'UTL-03',
    title: 'EV charging app and sessions',
    sectorCode: 'UTL',
    department: 'EV Services',
    activities: [
      'Account and vehicle registration',
      'Finding chargers',
      'Charging sessions and billing',
      'Roaming with other networks',
    ].join('\n'),
    dataPrincipals: 'EV user',
    dataCategories: ['identity', 'contact', 'vehicle', 'location', 'payment_card', 'transaction'],
    typicalSystems: 'Charging app\nCharge-point management system',
    typicalThirdParties: 'Roaming partners\nPayment gateway\nCloud',
    typicalLawfulBasis: ['consent'],
    flags: ['processor', 'online_presence', 'marketing'],
    contextTags: ['location', 'financial'],
  },
  {
    code: 'REH-03',
    title: 'Tenant onboarding, rent and police verification',
    sectorCode: 'REH',
    department: 'Property Management',
    activities: [
      'Tenant application and KYC',
      'Police verification submission',
      'Rent agreement and registration',
      'Rent and deposit collection',
      'Move-out and deposit refund',
    ].join('\n'),
    dataPrincipals: 'Tenant\nCo-occupant\nGuarantor',
    dataCategories: ['identity', 'contact', 'gov_id', 'financial', 'family'],
    typicalSystems: 'Property management software\nPayment portal',
    typicalThirdParties: 'Local police\nSub-registrar or e-stamping\nPayment gateway',
    typicalLawfulBasis: ['consent', 's7d'],
    flags: ['processor'],
    contextTags: ['gov_id', 'financial'],
    assessorNote:
      'Police verification of tenants is required by local orders in many cities; record the order relied on for s.7(d).',
  },
  {
    code: 'PRO-03',
    title: 'Recruitment and staffing for client employers',
    sectorCode: 'PRO',
    department: 'Staffing',
    activities: [
      'Sourcing and candidate database',
      'Screening and interviews',
      'Sharing profiles with client employers',
      'Background checks',
      'Onboarding for client deployment',
    ].join('\n'),
    dataPrincipals: 'Candidate\nPlaced contractor\nReferee',
    dataCategories: [
      'identity',
      'contact',
      'education',
      'employment_history',
      'background_check',
      'gov_id',
    ],
    typicalSystems: 'Applicant tracking system\nJob portals',
    typicalThirdParties: 'Client employers\nJob boards\nBackground verification agencies',
    typicalLawfulBasis: ['consent', 's7a'],
    flags: ['processor', 'decision_or_disclosure', 'online_presence', 'marketing'],
    contextTags: ['gov_id'],
    assessorNote:
      'Candidate profiles shared with client employers make those employers separate Data Fiduciaries; check the consent covers the sharing.',
  },
  {
    code: 'ITS-04',
    title: 'Customer support with remote access',
    sectorCode: 'ITS',
    department: 'Support',
    activities: [
      'Ticket intake',
      'Remote screen sharing',
      'Access to customer production data for debugging',
      'Call and chat recording',
    ].join('\n'),
    dataPrincipals: 'Client end-customers\nClient employees',
    dataCategories: ['identity', 'contact', 'communication_content', 'device_online'],
    typicalSystems: 'Ticketing tool\nRemote access tool\nLogging',
    typicalThirdParties: 'Sub-processors\nOffshore support centre',
    typicalLawfulBasis: ['consent'],
    flags: ['processor', 'cross_border'],
    contextTags: [],
    assessorNote:
      'Usually done as a processor for the client; confirm the contract allows each kind of access and that it is logged.',
  },
  {
    code: 'CMN-DIG-04',
    title: 'AI assistants and chatbots using personal data',
    sectorCode: 'CMN',
    department: 'Digital / Product',
    activities: [
      'Chatbot conversations',
      'Using conversations to improve models',
      'Automated answers and hand-over to staff',
      'Calls to external AI model APIs',
    ].join('\n'),
    dataPrincipals: 'Customer\nWebsite/app visitor\nEmployee',
    dataCategories: ['identity', 'contact', 'communication_content', 'inferences'],
    typicalSystems: 'Chatbot platform\nAI model API\nCRM',
    typicalThirdParties: 'AI model provider\nCloud',
    typicalLawfulBasis: ['consent', 's7a'],
    flags: ['processor', 'cross_border', 'online_presence', 'decision_or_disclosure'],
    contextTags: ['ai'],
    assessorNote:
      'Check whether the model provider may use conversations for its own purposes; if so it is not only a processor.',
  },
  {
    code: 'EDU-07',
    title: 'Hostel and boarding',
    sectorCode: 'EDU',
    department: 'Student Welfare',
    activities: [
      'Hostel allotment',
      'Attendance, leave and out-passes',
      'Visitor logs',
      'Health and incident records',
      'CCTV in common areas',
    ].join('\n'),
    dataPrincipals: 'Student (minor)\nParent/guardian\nWarden and staff',
    dataCategories: ['identity', 'contact', 'health', 'images_av', 'attendance'],
    typicalSystems: 'Hostel management system\nCCTV',
    typicalThirdParties: 'Catering and security contractors\nHospital or clinic',
    typicalLawfulBasis: ['consent', 's7f'],
    flags: ['processor', 'children'],
    contextTags: ['health', 'cctv'],
  },
  {
    code: 'AGR-01',
    title: 'Farmer onboarding and advisory',
    sectorCode: 'AGR',
    department: 'Field Operations',
    activities: [
      'Farmer registration by field agents',
      'Land and crop details',
      'Advisory by app, SMS and voice',
      'Input sales and delivery',
    ].join('\n'),
    dataPrincipals: 'Farmer\nFarm worker\nField agent',
    dataCategories: ['identity', 'contact', 'gov_id', 'location', 'property', 'financial'],
    typicalSystems: 'Field agent app\nCRM\nIVR and SMS platform',
    typicalThirdParties: 'Input suppliers\nTelecom and SMS providers\nCloud',
    typicalLawfulBasis: ['consent'],
    flags: ['processor', 'marketing', 'legacy_data'],
    contextTags: ['location', 'gov_id'],
    assessorNote:
      'Field agents often collect data on paper first; find where it is digitised (s.3(a)) and how the notice reaches farmers in their language.',
  },
  {
    code: 'AGR-02',
    title: 'Agri-credit and crop insurance facilitation',
    sectorCode: 'AGR',
    department: 'Financial Services',
    activities: [
      'Loan and insurance applications',
      'Sharing farmer and land data with lenders and insurers',
      'Claim intimation and assessment',
      'Repayment and settlement tracking',
    ].join('\n'),
    dataPrincipals: 'Farmer\nCo-borrower\nNominee',
    dataCategories: ['identity', 'gov_id', 'financial', 'property', 'location', 'credit_history'],
    typicalSystems: 'Loan origination system\nScheme portals',
    typicalThirdParties: 'Banks and NBFCs\nInsurers\nCredit bureaus',
    typicalLawfulBasis: ['consent'],
    flags: ['processor', 'decision_or_disclosure'],
    contextTags: ['financial', 'gov_id'],
  },
  {
    code: 'FIT-01',
    title: 'Membership, fitness assessments and wearables',
    sectorCode: 'FIT',
    department: 'Membership',
    activities: [
      'Membership sign-up and renewal',
      'Fitness and body assessments',
      'Wearable and app data sync',
      'Biometric or app-based entry',
      'Classes, trainers and progress tracking',
    ].join('\n'),
    dataPrincipals: 'Member\nMinor athlete and parent\nTrainer or coach',
    dataCategories: ['identity', 'contact', 'health', 'biometric', 'payment_card', 'images_av'],
    typicalSystems: 'Gym management software\nMember app\nAccess control',
    typicalThirdParties: 'Wearable platforms\nPayment gateway\nCloud',
    typicalLawfulBasis: ['consent'],
    flags: ['processor', 'children', 'cross_border', 'online_presence', 'marketing'],
    contextTags: ['health', 'biometric', 'cctv'],
  },
]

export const SECTORS: EntryInput[] = [
  {
    code: 'AGR',
    title: 'Agriculture & Agritech',
    covers:
      'Agritech platforms, farmer producer organisations, input and seed companies, agri-lending and crop insurance intermediaries, warehousing',
    regulators:
      'Ministry of Agriculture & Farmers Welfare\nState agriculture departments\nRBI (agri-lending)\nCERT-In',
    keyPrincipals: 'Farmer\nFarm worker\nDealer or retailer\nField agent',
    localisation:
      'No sector-specific localisation rule identified; lending and payment data follow RBI rules (verify).',
    hotspots: [
      'Farmer data collected on paper by field agents, then digitised',
      'Land records and Aadhaar-linked scheme data',
      'Precise farm locations and imagery linked to individuals',
      'Sharing with lenders, insurers and buyers',
      'Notices that reach farmers in their language and by voice',
    ].join('\n'),
    laws: [
      'State agricultural produce marketing (APMC) Acts | Trader and farmer records in market transactions (verify per State)',
      'Crop insurance scheme operational guidelines | Farmer, land and claim data shared with insurers and the national portal (verify the current guidelines)',
    ].join('\n'),
    retention:
      'Crop insurance claim records | Per the scheme guidelines | Scheme operational guidelines | verify',
  },
  {
    code: 'FIT',
    title: 'Sports, Fitness & Wellness',
    covers:
      'Gyms and fitness chains, sports academies, wellness and diet apps, wearable-linked services',
    regulators:
      'Department of Consumer Affairs / CCPA\nMinistry of Youth Affairs & Sports (academies, federations)\nCERT-In',
    keyPrincipals: 'Member\nMinor athlete and parent\nTrainer or coach\nTrial user',
    localisation:
      'No sector-specific localisation rule identified; app and wearable data is often hosted abroad.',
    hotspots: [
      'Health and body data from assessments and wearables',
      'Minor athletes: parental consent and limits on monitoring',
      'CCTV and its boundaries near changing areas',
      'Biometric entry',
      'Auto-renewing memberships and marketing consent',
    ].join('\n'),
    laws: [
      'Consumer Protection Act 2019 and Dark Patterns Guidelines 2023 | Sign-up, renewal and cancellation flows',
      'National Sports Development Code | Athlete records held by federations and academies (verify applicability)',
    ].join('\n'),
    retention: '',
  },
]

const playbook = (lines: string[]) => lines.join('\n')

export const PLAYBOOKS: EntryInput[] = [
  {
    code: 'breach-response-runbook',
    title: 'Personal data breach response (s.8(6), Rule 7)',
    docType: 'guide',
    bodyMd: playbook([
      'What to check, and in what order, when a client has a personal data breach. Every step links to the obligation it comes from; the DPDP duties apply from 13 May 2027, the CERT-In duty applies now.',
      '',
      '## Before anything happens',
      '- A way to detect and escalate breaches, including from processors, so the clocks below can be met ([OBL-BRE-04](ref:obligation/OBL-BRE-04)).',
      '- Processor contracts that make processors report breaches to the client promptly ([OBL-PRC-04](ref:obligation/OBL-PRC-04)).',
      '- A named CERT-In point of contact ([LNK-CERT-04](ref:obligation/LNK-CERT-04)) and ICT logs kept for 180 days in India ([LNK-CERT-02](ref:obligation/LNK-CERT-02)).',
      '',
      '## When a breach is noticed',
      '1. **CERT-In, within 6 hours** of noticing a reportable incident, including a data breach or leak ([LNK-CERT-01](ref:obligation/LNK-CERT-01)).',
      '2. **Affected Data Principals, without delay**: what happened (nature, extent, timing), the likely consequences, what is being done, what they can do to protect themselves, and whom to contact ([OBL-BRE-01](ref:obligation/OBL-BRE-01)).',
      '3. **The Data Protection Board, without delay**: an initial intimation with the nature, extent, timing, location and likely impact ([OBL-BRE-02](ref:obligation/OBL-BRE-02)).',
      '4. **The Board, within 72 hours** of becoming aware (or longer if the Board allows on a written request): updated details, the circumstances, mitigation, findings on the cause, remedial measures and a report on the intimations to Data Principals ([OBL-BRE-03](ref:obligation/OBL-BRE-03)).',
      '',
      '## Evidence to ask for',
      '- The incident log with the time the breach was noticed, so the 6-hour and 72-hour clocks can be checked.',
      '- Copies of the CERT-In report, the intimations to Data Principals and both reports to the Board.',
      '- The processor notification, if a processor was involved.',
      '',
      '## Where assessments get stuck',
      '- No agreed moment of "awareness": write down who decides and how it is recorded.',
      '- Contact details for affected people are missing or stale, so intimation "without delay" is not possible.',
      '',
      'Check each step against [Rule 7](ref:law/R07) and [section 8](ref:law/S08) before advising a client.',
    ]),
  },
  {
    code: 'rights-requests-handling',
    title: 'Handling Data Principal requests (s.11 to s.14, Rule 14)',
    docType: 'guide',
    bodyMd: playbook([
      'How a client should receive, verify and answer requests from Data Principals. The duties apply from 13 May 2027.',
      '',
      '## Publish the way in',
      '- Publish on the website or app how to make a request and which identifiers are needed, such as a customer number, mobile or email ([OBL-RGT-01](ref:obligation/OBL-RGT-01)).',
      '- Publish the contact of the DPO or the person who answers questions on processing, and give it in every response ([OBL-GOV-03](ref:obligation/OBL-GOV-03), [OBL-GOV-04](ref:obligation/OBL-GOV-04)).',
      '',
      '## Verify the requester',
      'Check the requester against an identifier the client issued before acting ([OBL-RGT-07](ref:obligation/OBL-RGT-07)).',
      '',
      '## Answer each kind of request',
      '| Request | What the client must do | Obligation |',
      '|---|---|---|',
      '| Access | A summary of the personal data and processing, the other fiduciaries and processors it was shared with, and what was shared | [OBL-RGT-02](ref:obligation/OBL-RGT-02) |',
      '| Correction, completion, updating | Correct, complete or update the data | [OBL-RGT-03](ref:obligation/OBL-RGT-03) |',
      '| Erasure | Erase, unless needed for the purpose or required by law | [OBL-RGT-04](ref:obligation/OBL-RGT-04) |',
      '| Nomination | Let the person nominate someone to act on death or incapacity | [OBL-RGT-06](ref:obligation/OBL-RGT-06) |',
      '| Withdrawal of consent | Make it as easy as giving consent, then stop processing | [OBL-CON-04](ref:obligation/OBL-CON-04), [OBL-CON-05](ref:obligation/OBL-CON-05) |',
      '',
      '## Grievances',
      'Grievance redressal must be readily available and answered within the period the client publishes, which may not exceed 90 days ([OBL-RGT-05](ref:obligation/OBL-RGT-05)). The person can go to the Board only after using it.',
      '',
      '## Evidence to ask for',
      '- The published rights page and request form.',
      '- The request log: received, verified, answered, with dates.',
      '- Sample responses, including the contact details given.',
      '',
      'See the [Data Principal rights](ref:vocabulary/data-principal-rights) vocabulary for the list of rights.',
    ]),
  },
  {
    code: 'childrens-data-and-parental-consent',
    title: "Children's data and verifiable parental consent (s.9, Rules 10 to 12)",
    docType: 'guide',
    bodyMd: playbook([
      'What changes when a client processes the personal data of anyone under 18. The duties apply from 13 May 2027.',
      '',
      '## Find the children',
      'The client needs a way to tell whether a person is a child, proportionate to the risk ([OBL-CHD-03](ref:obligation/OBL-CHD-03)). Schools, paediatric care, gaming and social platforms should assume children are present.',
      '',
      '## Get verifiable parental consent',
      "- Obtain verifiable consent of the parent before processing a child's data ([OBL-CHD-01](ref:obligation/OBL-CHD-01)).",
      '- Check that the person claiming to be the parent is an identifiable adult, using reliable details already held, or details or a virtual token issued by an authorised entity such as through DigiLocker ([OBL-CHD-02](ref:obligation/OBL-CHD-02); see [Verifiable consent methods](ref:vocabulary/verifiable-consent-methods)).',
      '- For a person with disability who cannot take legally binding decisions, the same applies to the lawful guardian, whose appointment must be verified ([OBL-PWD-01](ref:obligation/OBL-PWD-01), [OBL-PWD-02](ref:obligation/OBL-PWD-02)).',
      '',
      '## What is not allowed',
      "- Processing likely to harm a child's well-being ([OBL-CHD-04](ref:obligation/OBL-CHD-04)).",
      '- Tracking, behavioural monitoring or targeted advertising directed at children ([OBL-CHD-05](ref:obligation/OBL-CHD-05)), unless a Fourth Schedule exemption applies, and then only within its conditions ([OBL-CHD-06](ref:obligation/OBL-CHD-06)).',
      '',
      '## Evidence to ask for',
      '- The age-check flow and the parental consent flow, with screenshots.',
      '- Records showing consent was given by a verified adult.',
      '- For any Fourth Schedule exemption: the class or purpose relied on and how processing is kept within it.',
      '',
      'Check against [section 9](ref:law/S09), [Rule 10](ref:law/R10), [Rule 11](ref:law/R11), [Rule 12](ref:law/R12) and the [Fourth Schedule](ref:law/SCH4).',
    ]),
  },
  {
    code: 'retention-and-erasure',
    title: 'Retention and erasure (s.8(7), s.8(8), Rule 8)',
    docType: 'guide',
    bodyMd: playbook([
      'How long a client may keep personal data, and when it must go. The duties apply from 13 May 2027.',
      '',
      '## The default',
      'Erase when consent is withdrawn or as soon as it is reasonable to assume the specified purpose is no longer served, whichever is earlier, unless a law requires keeping it ([OBL-RET-01](ref:obligation/OBL-RET-01)). Processors must erase too ([OBL-RET-02](ref:obligation/OBL-RET-02)).',
      '',
      '## Minimums and exceptions',
      '- Keep personal data, traffic data and processing logs for at least one year for the purposes in the Seventh Schedule ([OBL-RET-05](ref:obligation/OBL-RET-05)), and logs for investigation under the security rules ([OBL-SEC-06](ref:obligation/OBL-SEC-06)).',
      '- Large e-commerce, online gaming and social media platforms in the Third Schedule erase after three years without the person approaching them ([OBL-RET-03](ref:obligation/OBL-RET-03)), telling them at least 48 hours before ([OBL-RET-04](ref:obligation/OBL-RET-04)).',
      '- Sector laws often set longer periods; each sector overlay lists the ones known, marked verify where the text must be checked.',
      '',
      '## The retention schedule',
      'The client should keep one schedule that reconciles DPDP erasure with sector, tax and labour retention, per data category and purpose ([OBL-RET-06](ref:obligation/OBL-RET-06)). See [Retention triggers](ref:vocabulary/retention-triggers).',
      '',
      '## Evidence to ask for',
      '- The retention schedule and who owns it.',
      '- Proof that erasure runs: job logs, deletion certificates from processors.',
      '- For Third Schedule platforms: the inactivity rule and the 48-hour notice template.',
      '',
      'Check against [section 8](ref:law/S08), [Rule 8](ref:law/R08) and the [Third Schedule](ref:law/SCH3).',
    ]),
  },
  {
    code: 'notice-and-consent-design',
    title: 'Notice and consent design (s.5, s.6, Rule 3)',
    docType: 'guide',
    bodyMd: playbook([
      "What a valid notice and consent look like, for reviewing a client's forms, apps and scripts. The duties apply from 13 May 2027.",
      '',
      '## The notice',
      '- Every consent request comes with, or after, a notice ([OBL-NOT-01](ref:obligation/OBL-NOT-01)) that stands on its own in clear and plain language ([OBL-NOT-02](ref:obligation/OBL-NOT-02)).',
      '- It itemises the personal data and the specified purposes ([OBL-NOT-03](ref:obligation/OBL-NOT-03)) and gives the means to withdraw consent, exercise rights and complain to the Board ([OBL-NOT-04](ref:obligation/OBL-NOT-04)).',
      '- It is available in English or any Eighth Schedule language ([OBL-NOT-05](ref:obligation/OBL-NOT-05); see [Notice languages](ref:vocabulary/notice-languages)).',
      '- People who consented before commencement get a notice as soon as reasonably practicable ([OBL-NOT-06](ref:obligation/OBL-NOT-06)).',
      '',
      '## The consent',
      '- Free, specific, informed, unconditional and unambiguous, by a clear affirmative action: no pre-ticked boxes and no bundling of unrelated purposes ([OBL-CON-01](ref:obligation/OBL-CON-01)).',
      '- Limited to the data needed for the purpose ([OBL-LB-02](ref:obligation/OBL-LB-02)).',
      '- In plain language with the contact of the DPO or an authorised person ([OBL-CON-03](ref:obligation/OBL-CON-03)).',
      '- As easy to withdraw as to give ([OBL-CON-04](ref:obligation/OBL-CON-04)).',
      '- Provable: the client carries the burden of proof ([OBL-CON-06](ref:obligation/OBL-CON-06); see [Consent states](ref:vocabulary/consent-states)).',
      '- No dark patterns in the interface ([LNK-CCPA-01](ref:obligation/LNK-CCPA-01)).',
      '',
      '## Evidence to ask for',
      '- Every notice version with dates, in each language offered.',
      '- Screenshots or recordings of each consent flow, including withdrawal.',
      '- Consent records linking each person to a notice version.',
      '',
      'Check against [section 5](ref:law/S05), [section 6](ref:law/S06) and [Rule 3](ref:law/R03).',
    ]),
  },
  {
    code: 'significant-data-fiduciary-readiness',
    title: 'Significant Data Fiduciary readiness (s.10, Rule 13)',
    docType: 'guide',
    bodyMd: playbook([
      'Extra duties for a client the Central Government notifies as a Significant Data Fiduciary. They start from notification, on top of every other obligation.',
      '',
      '## Watch for notification',
      'Monitor notifications under s.10(1) and start the programme when the client or its class is notified ([OBL-SCP-04](ref:obligation/OBL-SCP-04)).',
      '',
      '## The duties',
      '| Duty | Obligation |',
      '|---|---|',
      '| A DPO based in India, responsible to the board and the point of contact for grievances | [OBL-SDF-01](ref:obligation/OBL-SDF-01) |',
      '| An independent data auditor | [OBL-SDF-02](ref:obligation/OBL-SDF-02) |',
      '| A Data Protection Impact Assessment every 12 months | [OBL-SDF-03](ref:obligation/OBL-SDF-03) |',
      '| An audit every 12 months | [OBL-SDF-04](ref:obligation/OBL-SDF-04) |',
      '| Significant observations of the DPIA and audit reported to the Board | [OBL-SDF-05](ref:obligation/OBL-SDF-05) |',
      "| Due diligence that algorithmic software does not risk Data Principals' rights | [OBL-SDF-06](ref:obligation/OBL-SDF-06) |",
      '| Specified personal data and its traffic data kept in India, if the Government so specifies | [OBL-SDF-07](ref:obligation/OBL-SDF-07) |',
      '',
      '## Evidence to ask for',
      '- The DPO appointment and reporting line.',
      '- The auditor engagement letter and the last audit and DPIA reports.',
      '- The algorithm review records for systems that host, display or share personal data.',
      '',
      'Check against [section 10](ref:law/S10) and [Rule 13](ref:law/R13).',
    ]),
  },
]
