import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { networkInterfaces } from 'node:os'
import { join } from 'node:path'

// The two environment files of an installation. infra/.env holds the service secrets (created
// once, never overwritten); the root .env is generated from it for the apps.

export type ServicesMode = 'docker' | 'external'

export type EnvOptions = {
  root: string
  services: ServicesMode
  webPort: number
  apiPort: number
  database: string
  hostIp?: string
}

/** KEY=value lines into a map (comments and blank lines ignored). */
export const parseEnvFile = (text: string): Record<string, string> =>
  Object.fromEntries(
    text
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#') && line.includes('='))
      .map((line) => {
        const at = line.indexOf('=')
        return [line.slice(0, at).trim(), line.slice(at + 1).trim()]
      }),
  )

const secret = () => randomBytes(24).toString('hex')

/** Defaults for a stack started by this installer (docker mode); ports avoid the main stack. */
export const DOCKER_DEFAULTS: Record<string, () => string> = {
  POSTGRES_USER: () => 'duatf',
  POSTGRES_PASSWORD: secret,
  POSTGRES_DB: () => 'duatf_self',
  POSTGRES_PORT: () => '55433',
  REDIS_PASSWORD: secret,
  REDIS_PORT: () => '56380',
  MINIO_ROOT_USER: () => 'duatf',
  MINIO_ROOT_PASSWORD: secret,
  MINIO_API_PORT: () => '59010',
  MINIO_CONSOLE_PORT: () => '59011',
  MAILPIT_SMTP_PORT: () => '51026',
}

const REQUIRED = [
  'POSTGRES_USER',
  'POSTGRES_PASSWORD',
  'POSTGRES_PORT',
  'REDIS_PASSWORD',
  'REDIS_PORT',
  'MINIO_ROOT_USER',
  'MINIO_ROOT_PASSWORD',
  'MINIO_API_PORT',
]

/**
 * Makes sure infra/.env has every service secret. In docker mode missing values are generated;
 * in external mode (services already running) they must be there. Existing values are kept.
 */
export const ensureServiceEnv = (options: EnvOptions): { file: string; added: string[] } => {
  const file = join(options.root, 'infra', '.env')
  const current = existsSync(file) ? parseEnvFile(readFileSync(file, 'utf8')) : {}
  const added: string[] = []
  if (options.services === 'docker') {
    for (const [key, make] of Object.entries(DOCKER_DEFAULTS)) {
      if (!current[key]) {
        current[key] = make()
        added.push(key)
      }
    }
  }
  if (!current.APP_DB_PASSWORD) {
    current.APP_DB_PASSWORD = secret()
    added.push('APP_DB_PASSWORD')
  }
  const missing = REQUIRED.filter((key) => !current[key])
  if (missing.length) {
    throw new Error(
      `infra/.env lacks ${missing.join(', ')}. Use --services docker to generate them, or fill them in for the services you run.`,
    )
  }
  if (added.length) {
    const lines = existsSync(file) ? readFileSync(file, 'utf8').replace(/\s*$/, '\n') : ''
    writeFileSync(file, lines + added.map((key) => `${key}=${current[key]}`).join('\n') + '\n', {
      mode: 0o600,
    })
  }
  return { file, added }
}

// Interfaces of containers, virtual machines and VPNs: never the address other machines use.
const VIRTUAL =
  /^(docker|br-|veth|virbr|vmnet|vboxnet|vethernet|lxc|lxd|cni|flannel|tun|tap|wg|zt)/i

/** Private ranges, the likeliest LAN first: 192.168/16, then 10/8, others, then 172.16/12. */
const rank = (address: string) =>
  address.startsWith('192.168.')
    ? 0
    : address.startsWith('10.')
      ? 1
      : /^172\.(1[6-9]|2\d|3[01])\./.test(address)
        ? 3
        : 2

/**
 * The LAN address of this machine: an IPv4 address of a physical interface, not loopback,
 * Docker, a virtual machine or a VPN. Give --host-ip when the guess is wrong.
 */
export const lanAddress = (): string => {
  const addresses = Object.entries(networkInterfaces())
    .filter(([name]) => !VIRTUAL.test(name))
    .flatMap(([, entries]) => entries ?? [])
    .filter((entry) => entry.family === 'IPv4' && !entry.internal)
    .map((entry) => entry.address)
    .sort((a, b) => rank(a) - rank(b))
  return addresses[0] ?? '127.0.0.1'
}

/** Writes the root .env the apps read, from infra/.env and the chosen ports and database. */
export const writeAppEnv = (options: EnvOptions): string => {
  const services = parseEnvFile(readFileSync(join(options.root, 'infra', '.env'), 'utf8'))
  const host = options.hostIp ?? lanAddress()
  const pg = `127.0.0.1:${services.POSTGRES_PORT ?? '5432'}`
  const owner = `${encodeURIComponent(services.POSTGRES_USER ?? '')}:${encodeURIComponent(services.POSTGRES_PASSWORD ?? '')}`
  const app = `duatf_app:${encodeURIComponent(services.APP_DB_PASSWORD ?? '')}`
  const db = options.database
  const lines = [
    '# Generated by `pnpm duatf env` from infra/.env. Do not commit.',
    'NODE_ENV=development',
    'HOST=0.0.0.0',
    `WEB_PORT=${options.webPort}`,
    `API_PORT=${options.apiPort}`,
    `PUBLIC_WEB_URL=http://${host}:${options.webPort}`,
    `PUBLIC_API_URL=http://${host}:${options.apiPort}`,
    `DATABASE_URL=postgres://${owner}@${pg}/${db}`,
    `APP_DATABASE_URL=postgres://${app}@${pg}/${db}`,
    `TEST_DATABASE_URL=postgres://${owner}@${pg}/${db}_test`,
    `TEST_APP_DATABASE_URL=postgres://${app}@${pg}/${db}_test`,
    `REDIS_URL=redis://:${encodeURIComponent(services.REDIS_PASSWORD ?? '')}@127.0.0.1:${services.REDIS_PORT ?? '6379'}/1`,
    `S3_ENDPOINT=http://127.0.0.1:${services.MINIO_API_PORT ?? '9000'}`,
    `S3_PUBLIC_ENDPOINT=http://${host}:${services.MINIO_API_PORT ?? '9000'}`,
    `S3_ACCESS_KEY=${services.MINIO_ROOT_USER ?? ''}`,
    `S3_SECRET_KEY=${services.MINIO_ROOT_PASSWORD ?? ''}`,
    'S3_BUCKET_EVIDENCE=duatf-self-evidence',
    'S3_BUCKET_REPORTS=duatf-self-reports',
    'SMTP_HOST=127.0.0.1',
    `SMTP_PORT=${services.MAILPIT_SMTP_PORT ?? '1025'}`,
    'SESSION_TTL_HOURS=12',
    'SEED_VAULT_PATH=seed/DPDP-DUATF-Vault',
  ]
  const file = join(options.root, '.env')
  writeFileSync(file, lines.join('\n') + '\n', { mode: 0o600 })
  return `http://${host}:${options.webPort}`
}

/** The settings an existing installation was made with (from its .env), for later commands. */
export const installedSettings = (root: string) => {
  const file = join(root, '.env')
  if (!existsSync(file)) return null
  const values = parseEnvFile(readFileSync(file, 'utf8'))
  return {
    webPort: Number(values.WEB_PORT ?? 53500),
    apiPort: Number(values.API_PORT ?? 54500),
    database: /\/([^/?]+)(\?.*)?$/.exec(values.DATABASE_URL ?? '')?.[1] ?? 'duatf_self',
    webUrl: values.PUBLIC_WEB_URL ?? '',
    databaseUrl: values.DATABASE_URL ?? '',
  }
}
