import type { Evaluation } from './evaluate'

const escapeCell = (text: string) => text.replaceAll('|', '\\|').replaceAll('\n', ' ')

export const renderStatusMarkdown = (evaluation: Evaluation): string => {
  const lines = [
    '# DUATF build status',
    '',
    'Generated by `pnpm trace` from test results. Do not edit by hand.',
    '',
    `Gate: **${evaluation.gate.ok ? 'passing' : 'blocked'}**`,
    '',
  ]
  if (!evaluation.gate.ok) {
    lines.push('Blocking:', '', ...evaluation.gate.blocking.map((item) => `- ${item}`), '')
  }

  lines.push(
    '## Phases',
    '',
    '| Phase | Title | Release | Status | Reviews |',
    '|---|---|---|---|---|',
  )
  for (const phase of evaluation.phases) {
    const reviews = phase.reviewsRequired.length
      ? phase.reviewsRequired
          .map((role) => `${role} ${phase.reviewsRecorded.includes(role) ? 'approved' : 'pending'}`)
          .join(', ')
      : '-'
    lines.push(`| ${phase.id} | ${phase.title} | ${phase.release} | ${phase.status} | ${reviews} |`)
  }

  const activeTests = evaluation.tests.filter((test) => test.status !== 'PLANNED')
  lines.push(
    '',
    '## Tests in active sub-phases',
    '',
    '| Test | Sub-phase | What | Expected | Source | Status |',
    '|---|---|---|---|---|---|',
    ...activeTests.map(
      (test) =>
        `| ${test.id} | ${test.subphase} | ${escapeCell(test.title)} | ${escapeCell(test.expected)} | ${test.source} | ${test.status} |`,
    ),
  )

  if (evaluation.untraced.length) {
    lines.push('', '## Untraced test IDs', '', ...evaluation.untraced.map((id) => `- ${id}`))
  }
  const planned = evaluation.tests.length - activeTests.length
  lines.push('', `${planned} further tests are planned in later sub-phases.`, '')
  return lines.join('\n')
}
